apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-go
  labels:
    app: backend-go
    app.kubernetes.io/part-of: pegasusx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-go
  minReplicas: 3
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
