// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: optimizer_core.proto

package optimizercorepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OptimizerCoreService_CalculateRoute_FullMethodName    = "/pegasus.optimizer.core.v1.OptimizerCoreService/CalculateRoute"
	OptimizerCoreService_ResolveConstraint_FullMethodName = "/pegasus.optimizer.core.v1.OptimizerCoreService/ResolveConstraint"
	OptimizerCoreService_HealthCheck_FullMethodName       = "/pegasus.optimizer.core.v1.OptimizerCoreService/HealthCheck"
)

// OptimizerCoreServiceClient is the client API for OptimizerCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptimizerCoreServiceClient interface {
	CalculateRoute(ctx context.Context, in *VRPRequest, opts ...grpc.CallOption) (*VRPResponse, error)
	ResolveConstraint(ctx context.Context, in *CPSATRequest, opts ...grpc.CallOption) (*CPSATResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type optimizerCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizerCoreServiceClient(cc grpc.ClientConnInterface) OptimizerCoreServiceClient {
	return &optimizerCoreServiceClient{cc}
}

func (c *optimizerCoreServiceClient) CalculateRoute(ctx context.Context, in *VRPRequest, opts ...grpc.CallOption) (*VRPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VRPResponse)
	err := c.cc.Invoke(ctx, OptimizerCoreService_CalculateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerCoreServiceClient) ResolveConstraint(ctx context.Context, in *CPSATRequest, opts ...grpc.CallOption) (*CPSATResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CPSATResponse)
	err := c.cc.Invoke(ctx, OptimizerCoreService_ResolveConstraint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerCoreServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, OptimizerCoreService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizerCoreServiceServer is the server API for OptimizerCoreService service.
// All implementations must embed UnimplementedOptimizerCoreServiceServer
// for forward compatibility.
type OptimizerCoreServiceServer interface {
	CalculateRoute(context.Context, *VRPRequest) (*VRPResponse, error)
	ResolveConstraint(context.Context, *CPSATRequest) (*CPSATResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedOptimizerCoreServiceServer()
}

// UnimplementedOptimizerCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptimizerCoreServiceServer struct{}

func (UnimplementedOptimizerCoreServiceServer) CalculateRoute(context.Context, *VRPRequest) (*VRPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateRoute not implemented")
}
func (UnimplementedOptimizerCoreServiceServer) ResolveConstraint(context.Context, *CPSATRequest) (*CPSATResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveConstraint not implemented")
}
func (UnimplementedOptimizerCoreServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedOptimizerCoreServiceServer) mustEmbedUnimplementedOptimizerCoreServiceServer() {}
func (UnimplementedOptimizerCoreServiceServer) testEmbeddedByValue()                              {}

// UnsafeOptimizerCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizerCoreServiceServer will
// result in compilation errors.
type UnsafeOptimizerCoreServiceServer interface {
	mustEmbedUnimplementedOptimizerCoreServiceServer()
}

func RegisterOptimizerCoreServiceServer(s grpc.ServiceRegistrar, srv OptimizerCoreServiceServer) {
	// If the following call panics, it indicates UnimplementedOptimizerCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OptimizerCoreService_ServiceDesc, srv)
}

func _OptimizerCoreService_CalculateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VRPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerCoreServiceServer).CalculateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerCoreService_CalculateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerCoreServiceServer).CalculateRoute(ctx, req.(*VRPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizerCoreService_ResolveConstraint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CPSATRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerCoreServiceServer).ResolveConstraint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerCoreService_ResolveConstraint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerCoreServiceServer).ResolveConstraint(ctx, req.(*CPSATRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizerCoreService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerCoreServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerCoreService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerCoreServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OptimizerCoreService_ServiceDesc is the grpc.ServiceDesc for OptimizerCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OptimizerCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pegasus.optimizer.core.v1.OptimizerCoreService",
	HandlerType: (*OptimizerCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateRoute",
			Handler:    _OptimizerCoreService_CalculateRoute_Handler,
		},
		{
			MethodName: "ResolveConstraint",
			Handler:    _OptimizerCoreService_ResolveConstraint_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _OptimizerCoreService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optimizer_core.proto",
}
