// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: optimizer_core.proto

package optimizercorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED        JobType = 0
	JobType_JOB_TYPE_CTP                JobType = 1
	JobType_JOB_TYPE_MEIO               JobType = 2
	JobType_JOB_TYPE_FACTORY_SCHEDULING JobType = 3
	JobType_JOB_TYPE_FLEET_ROUTING      JobType = 4
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_CTP",
		2: "JOB_TYPE_MEIO",
		3: "JOB_TYPE_FACTORY_SCHEDULING",
		4: "JOB_TYPE_FLEET_ROUTING",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED":        0,
		"JOB_TYPE_CTP":                1,
		"JOB_TYPE_MEIO":               2,
		"JOB_TYPE_FACTORY_SCHEDULING": 3,
		"JOB_TYPE_FLEET_ROUTING":      4,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_core_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_optimizer_core_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{0}
}

type SolverStatus int32

const (
	SolverStatus_OPTIMAL       SolverStatus = 0
	SolverStatus_FEASIBLE      SolverStatus = 1
	SolverStatus_INFEASIBLE    SolverStatus = 2
	SolverStatus_MODEL_INVALID SolverStatus = 3
)

// Enum value maps for SolverStatus.
var (
	SolverStatus_name = map[int32]string{
		0: "OPTIMAL",
		1: "FEASIBLE",
		2: "INFEASIBLE",
		3: "MODEL_INVALID",
	}
	SolverStatus_value = map[string]int32{
		"OPTIMAL":       0,
		"FEASIBLE":      1,
		"INFEASIBLE":    2,
		"MODEL_INVALID": 3,
	}
)

func (x SolverStatus) Enum() *SolverStatus {
	p := new(SolverStatus)
	*p = x
	return p
}

func (x SolverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SolverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_core_proto_enumTypes[1].Descriptor()
}

func (SolverStatus) Type() protoreflect.EnumType {
	return &file_optimizer_core_proto_enumTypes[1]
}

func (x SolverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SolverStatus.Descriptor instead.
func (SolverStatus) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{1}
}

type SolverMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobId             string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TraceId           string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SupplierId        string                 `protobuf:"bytes,3,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	JobType           JobType                `protobuf:"varint,4,opt,name=job_type,json=jobType,proto3,enum=pegasus.optimizer.core.v1.JobType" json:"job_type,omitempty"`
	ScaleFactor       int64                  `protobuf:"varint,5,opt,name=scale_factor,json=scaleFactor,proto3" json:"scale_factor,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	SourceEventType   string                 `protobuf:"bytes,7,opt,name=source_event_type,json=sourceEventType,proto3" json:"source_event_type,omitempty"`
	RequestedAtUnixMs int64                  `protobuf:"varint,8,opt,name=requested_at_unix_ms,json=requestedAtUnixMs,proto3" json:"requested_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SolverMetadata) Reset() {
	*x = SolverMetadata{}
	mi := &file_optimizer_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolverMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolverMetadata) ProtoMessage() {}

func (x *SolverMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolverMetadata.ProtoReflect.Descriptor instead.
func (*SolverMetadata) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{0}
}

func (x *SolverMetadata) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SolverMetadata) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SolverMetadata) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *SolverMetadata) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *SolverMetadata) GetScaleFactor() int64 {
	if x != nil {
		return x.ScaleFactor
	}
	return 0
}

func (x *SolverMetadata) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SolverMetadata) GetSourceEventType() string {
	if x != nil {
		return x.SourceEventType
	}
	return ""
}

func (x *SolverMetadata) GetRequestedAtUnixMs() int64 {
	if x != nil {
		return x.RequestedAtUnixMs
	}
	return 0
}

type Int64Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64Row) Reset() {
	*x = Int64Row{}
	mi := &file_optimizer_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Row) ProtoMessage() {}

func (x *Int64Row) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Row.ProtoReflect.Descriptor instead.
func (*Int64Row) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{1}
}

func (x *Int64Row) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Vehicle struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	VehicleUuid           string                 `protobuf:"bytes,1,opt,name=vehicle_uuid,json=vehicleUuid,proto3" json:"vehicle_uuid,omitempty"`
	DriverUuid            string                 `protobuf:"bytes,2,opt,name=driver_uuid,json=driverUuid,proto3" json:"driver_uuid,omitempty"`
	CapacityScaled        int64                  `protobuf:"varint,3,opt,name=capacity_scaled,json=capacityScaled,proto3" json:"capacity_scaled,omitempty"`
	StartTimeWindowScaled int64                  `protobuf:"varint,4,opt,name=start_time_window_scaled,json=startTimeWindowScaled,proto3" json:"start_time_window_scaled,omitempty"`
	EndTimeWindowScaled   int64                  `protobuf:"varint,5,opt,name=end_time_window_scaled,json=endTimeWindowScaled,proto3" json:"end_time_window_scaled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_optimizer_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{2}
}

func (x *Vehicle) GetVehicleUuid() string {
	if x != nil {
		return x.VehicleUuid
	}
	return ""
}

func (x *Vehicle) GetDriverUuid() string {
	if x != nil {
		return x.DriverUuid
	}
	return ""
}

func (x *Vehicle) GetCapacityScaled() int64 {
	if x != nil {
		return x.CapacityScaled
	}
	return 0
}

func (x *Vehicle) GetStartTimeWindowScaled() int64 {
	if x != nil {
		return x.StartTimeWindowScaled
	}
	return 0
}

func (x *Vehicle) GetEndTimeWindowScaled() int64 {
	if x != nil {
		return x.EndTimeWindowScaled
	}
	return 0
}

type NodeDemand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeUuid      string                 `protobuf:"bytes,1,opt,name=node_uuid,json=nodeUuid,proto3" json:"node_uuid,omitempty"`
	DemandScaled  int64                  `protobuf:"varint,2,opt,name=demand_scaled,json=demandScaled,proto3" json:"demand_scaled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDemand) Reset() {
	*x = NodeDemand{}
	mi := &file_optimizer_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDemand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDemand) ProtoMessage() {}

func (x *NodeDemand) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDemand.ProtoReflect.Descriptor instead.
func (*NodeDemand) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{3}
}

func (x *NodeDemand) GetNodeUuid() string {
	if x != nil {
		return x.NodeUuid
	}
	return ""
}

func (x *NodeDemand) GetDemandScaled() int64 {
	if x != nil {
		return x.DemandScaled
	}
	return 0
}

type NodeTimeWindow struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NodeUuid              string                 `protobuf:"bytes,1,opt,name=node_uuid,json=nodeUuid,proto3" json:"node_uuid,omitempty"`
	StartTimeWindowScaled int64                  `protobuf:"varint,2,opt,name=start_time_window_scaled,json=startTimeWindowScaled,proto3" json:"start_time_window_scaled,omitempty"`
	EndTimeWindowScaled   int64                  `protobuf:"varint,3,opt,name=end_time_window_scaled,json=endTimeWindowScaled,proto3" json:"end_time_window_scaled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NodeTimeWindow) Reset() {
	*x = NodeTimeWindow{}
	mi := &file_optimizer_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeTimeWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeTimeWindow) ProtoMessage() {}

func (x *NodeTimeWindow) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeTimeWindow.ProtoReflect.Descriptor instead.
func (*NodeTimeWindow) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{4}
}

func (x *NodeTimeWindow) GetNodeUuid() string {
	if x != nil {
		return x.NodeUuid
	}
	return ""
}

func (x *NodeTimeWindow) GetStartTimeWindowScaled() int64 {
	if x != nil {
		return x.StartTimeWindowScaled
	}
	return 0
}

func (x *NodeTimeWindow) GetEndTimeWindowScaled() int64 {
	if x != nil {
		return x.EndTimeWindowScaled
	}
	return 0
}

type VRPRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Meta                 *SolverMetadata        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	DepotNodeUuid        string                 `protobuf:"bytes,2,opt,name=depot_node_uuid,json=depotNodeUuid,proto3" json:"depot_node_uuid,omitempty"`
	DropOffNodeUuids     []string               `protobuf:"bytes,3,rep,name=drop_off_node_uuids,json=dropOffNodeUuids,proto3" json:"drop_off_node_uuids,omitempty"`
	DistanceMatrixScaled []*Int64Row            `protobuf:"bytes,4,rep,name=distance_matrix_scaled,json=distanceMatrixScaled,proto3" json:"distance_matrix_scaled,omitempty"`
	Vehicles             []*Vehicle             `protobuf:"bytes,5,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	NodeDemands          []*NodeDemand          `protobuf:"bytes,6,rep,name=node_demands,json=nodeDemands,proto3" json:"node_demands,omitempty"`
	NodeTimeWindows      []*NodeTimeWindow      `protobuf:"bytes,7,rep,name=node_time_windows,json=nodeTimeWindows,proto3" json:"node_time_windows,omitempty"`
	SolverTimeLimitMs    int64                  `protobuf:"varint,8,opt,name=solver_time_limit_ms,json=solverTimeLimitMs,proto3" json:"solver_time_limit_ms,omitempty"`
	ReturnBestEffort     bool                   `protobuf:"varint,9,opt,name=return_best_effort,json=returnBestEffort,proto3" json:"return_best_effort,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VRPRequest) Reset() {
	*x = VRPRequest{}
	mi := &file_optimizer_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VRPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VRPRequest) ProtoMessage() {}

func (x *VRPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VRPRequest.ProtoReflect.Descriptor instead.
func (*VRPRequest) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{5}
}

func (x *VRPRequest) GetMeta() *SolverMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *VRPRequest) GetDepotNodeUuid() string {
	if x != nil {
		return x.DepotNodeUuid
	}
	return ""
}

func (x *VRPRequest) GetDropOffNodeUuids() []string {
	if x != nil {
		return x.DropOffNodeUuids
	}
	return nil
}

func (x *VRPRequest) GetDistanceMatrixScaled() []*Int64Row {
	if x != nil {
		return x.DistanceMatrixScaled
	}
	return nil
}

func (x *VRPRequest) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *VRPRequest) GetNodeDemands() []*NodeDemand {
	if x != nil {
		return x.NodeDemands
	}
	return nil
}

func (x *VRPRequest) GetNodeTimeWindows() []*NodeTimeWindow {
	if x != nil {
		return x.NodeTimeWindows
	}
	return nil
}

func (x *VRPRequest) GetSolverTimeLimitMs() int64 {
	if x != nil {
		return x.SolverTimeLimitMs
	}
	return 0
}

func (x *VRPRequest) GetReturnBestEffort() bool {
	if x != nil {
		return x.ReturnBestEffort
	}
	return false
}

type VehicleRoute struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VehicleUuid      string                 `protobuf:"bytes,1,opt,name=vehicle_uuid,json=vehicleUuid,proto3" json:"vehicle_uuid,omitempty"`
	DriverUuid       string                 `protobuf:"bytes,2,opt,name=driver_uuid,json=driverUuid,proto3" json:"driver_uuid,omitempty"`
	OrderedNodeUuids []string               `protobuf:"bytes,3,rep,name=ordered_node_uuids,json=orderedNodeUuids,proto3" json:"ordered_node_uuids,omitempty"`
	LoadScaled       int64                  `protobuf:"varint,4,opt,name=load_scaled,json=loadScaled,proto3" json:"load_scaled,omitempty"`
	RouteCostScaled  int64                  `protobuf:"varint,5,opt,name=route_cost_scaled,json=routeCostScaled,proto3" json:"route_cost_scaled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VehicleRoute) Reset() {
	*x = VehicleRoute{}
	mi := &file_optimizer_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleRoute) ProtoMessage() {}

func (x *VehicleRoute) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleRoute.ProtoReflect.Descriptor instead.
func (*VehicleRoute) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{6}
}

func (x *VehicleRoute) GetVehicleUuid() string {
	if x != nil {
		return x.VehicleUuid
	}
	return ""
}

func (x *VehicleRoute) GetDriverUuid() string {
	if x != nil {
		return x.DriverUuid
	}
	return ""
}

func (x *VehicleRoute) GetOrderedNodeUuids() []string {
	if x != nil {
		return x.OrderedNodeUuids
	}
	return nil
}

func (x *VehicleRoute) GetLoadScaled() int64 {
	if x != nil {
		return x.LoadScaled
	}
	return 0
}

func (x *VehicleRoute) GetRouteCostScaled() int64 {
	if x != nil {
		return x.RouteCostScaled
	}
	return 0
}

type VRPResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Meta                *SolverMetadata        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Feasible            bool                   `protobuf:"varint,2,opt,name=feasible,proto3" json:"feasible,omitempty"`
	TimedOut            bool                   `protobuf:"varint,3,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	ObjectiveCostScaled int64                  `protobuf:"varint,4,opt,name=objective_cost_scaled,json=objectiveCostScaled,proto3" json:"objective_cost_scaled,omitempty"`
	Routes              []*VehicleRoute        `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	UnassignedNodeUuids []string               `protobuf:"bytes,6,rep,name=unassigned_node_uuids,json=unassignedNodeUuids,proto3" json:"unassigned_node_uuids,omitempty"`
	Warnings            []string               `protobuf:"bytes,7,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Status              SolverStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=pegasus.optimizer.core.v1.SolverStatus" json:"status,omitempty"`
	MatrixSize          int32                  `protobuf:"varint,9,opt,name=matrix_size,json=matrixSize,proto3" json:"matrix_size,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VRPResponse) Reset() {
	*x = VRPResponse{}
	mi := &file_optimizer_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VRPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VRPResponse) ProtoMessage() {}

func (x *VRPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VRPResponse.ProtoReflect.Descriptor instead.
func (*VRPResponse) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{7}
}

func (x *VRPResponse) GetMeta() *SolverMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *VRPResponse) GetFeasible() bool {
	if x != nil {
		return x.Feasible
	}
	return false
}

func (x *VRPResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *VRPResponse) GetObjectiveCostScaled() int64 {
	if x != nil {
		return x.ObjectiveCostScaled
	}
	return 0
}

func (x *VRPResponse) GetRoutes() []*VehicleRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *VRPResponse) GetUnassignedNodeUuids() []string {
	if x != nil {
		return x.UnassignedNodeUuids
	}
	return nil
}

func (x *VRPResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *VRPResponse) GetStatus() SolverStatus {
	if x != nil {
		return x.Status
	}
	return SolverStatus_OPTIMAL
}

func (x *VRPResponse) GetMatrixSize() int32 {
	if x != nil {
		return x.MatrixSize
	}
	return 0
}

type FactorySlot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FactoryNodeUuid    string                 `protobuf:"bytes,1,opt,name=factory_node_uuid,json=factoryNodeUuid,proto3" json:"factory_node_uuid,omitempty"`
	SlotCapacityScaled int64                  `protobuf:"varint,2,opt,name=slot_capacity_scaled,json=slotCapacityScaled,proto3" json:"slot_capacity_scaled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FactorySlot) Reset() {
	*x = FactorySlot{}
	mi := &file_optimizer_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorySlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorySlot) ProtoMessage() {}

func (x *FactorySlot) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorySlot.ProtoReflect.Descriptor instead.
func (*FactorySlot) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{8}
}

func (x *FactorySlot) GetFactoryNodeUuid() string {
	if x != nil {
		return x.FactoryNodeUuid
	}
	return ""
}

func (x *FactorySlot) GetSlotCapacityScaled() int64 {
	if x != nil {
		return x.SlotCapacityScaled
	}
	return 0
}

type ManifestRequirement struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ManifestId               string                 `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	RequiredCapacityScaled   int64                  `protobuf:"varint,2,opt,name=required_capacity_scaled,json=requiredCapacityScaled,proto3" json:"required_capacity_scaled,omitempty"`
	PriorityScoreScaled      int64                  `protobuf:"varint,3,opt,name=priority_score_scaled,json=priorityScoreScaled,proto3" json:"priority_score_scaled,omitempty"`
	EligibleFactoryNodeUuids []string               `protobuf:"bytes,4,rep,name=eligible_factory_node_uuids,json=eligibleFactoryNodeUuids,proto3" json:"eligible_factory_node_uuids,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ManifestRequirement) Reset() {
	*x = ManifestRequirement{}
	mi := &file_optimizer_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequirement) ProtoMessage() {}

func (x *ManifestRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequirement.ProtoReflect.Descriptor instead.
func (*ManifestRequirement) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{9}
}

func (x *ManifestRequirement) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

func (x *ManifestRequirement) GetRequiredCapacityScaled() int64 {
	if x != nil {
		return x.RequiredCapacityScaled
	}
	return 0
}

func (x *ManifestRequirement) GetPriorityScoreScaled() int64 {
	if x != nil {
		return x.PriorityScoreScaled
	}
	return 0
}

func (x *ManifestRequirement) GetEligibleFactoryNodeUuids() []string {
	if x != nil {
		return x.EligibleFactoryNodeUuids
	}
	return nil
}

type CPSATRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Meta                 *SolverMetadata        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	FactorySlots         []*FactorySlot         `protobuf:"bytes,2,rep,name=factory_slots,json=factorySlots,proto3" json:"factory_slots,omitempty"`
	ManifestRequirements []*ManifestRequirement `protobuf:"bytes,3,rep,name=manifest_requirements,json=manifestRequirements,proto3" json:"manifest_requirements,omitempty"`
	SolverTimeLimitMs    int64                  `protobuf:"varint,4,opt,name=solver_time_limit_ms,json=solverTimeLimitMs,proto3" json:"solver_time_limit_ms,omitempty"`
	ReturnBestEffort     bool                   `protobuf:"varint,5,opt,name=return_best_effort,json=returnBestEffort,proto3" json:"return_best_effort,omitempty"`
	NumSearchWorkers     int32                  `protobuf:"varint,6,opt,name=num_search_workers,json=numSearchWorkers,proto3" json:"num_search_workers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CPSATRequest) Reset() {
	*x = CPSATRequest{}
	mi := &file_optimizer_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPSATRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPSATRequest) ProtoMessage() {}

func (x *CPSATRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPSATRequest.ProtoReflect.Descriptor instead.
func (*CPSATRequest) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{10}
}

func (x *CPSATRequest) GetMeta() *SolverMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CPSATRequest) GetFactorySlots() []*FactorySlot {
	if x != nil {
		return x.FactorySlots
	}
	return nil
}

func (x *CPSATRequest) GetManifestRequirements() []*ManifestRequirement {
	if x != nil {
		return x.ManifestRequirements
	}
	return nil
}

func (x *CPSATRequest) GetSolverTimeLimitMs() int64 {
	if x != nil {
		return x.SolverTimeLimitMs
	}
	return 0
}

func (x *CPSATRequest) GetReturnBestEffort() bool {
	if x != nil {
		return x.ReturnBestEffort
	}
	return false
}

func (x *CPSATRequest) GetNumSearchWorkers() int32 {
	if x != nil {
		return x.NumSearchWorkers
	}
	return 0
}

type Assignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ManifestId      string                 `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	FactoryNodeUuid string                 `protobuf:"bytes,2,opt,name=factory_node_uuid,json=factoryNodeUuid,proto3" json:"factory_node_uuid,omitempty"`
	Assigned        bool                   `protobuf:"varint,3,opt,name=assigned,proto3" json:"assigned,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_optimizer_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{11}
}

func (x *Assignment) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

func (x *Assignment) GetFactoryNodeUuid() string {
	if x != nil {
		return x.FactoryNodeUuid
	}
	return ""
}

func (x *Assignment) GetAssigned() bool {
	if x != nil {
		return x.Assigned
	}
	return false
}

type CPSATResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Meta                  *SolverMetadata        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Feasible              bool                   `protobuf:"varint,2,opt,name=feasible,proto3" json:"feasible,omitempty"`
	TimedOut              bool                   `protobuf:"varint,3,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	ObjectiveScoreScaled  int64                  `protobuf:"varint,4,opt,name=objective_score_scaled,json=objectiveScoreScaled,proto3" json:"objective_score_scaled,omitempty"`
	Assignments           []*Assignment          `protobuf:"bytes,5,rep,name=assignments,proto3" json:"assignments,omitempty"`
	UnassignedManifestIds []string               `protobuf:"bytes,6,rep,name=unassigned_manifest_ids,json=unassignedManifestIds,proto3" json:"unassigned_manifest_ids,omitempty"`
	Warnings              []string               `protobuf:"bytes,7,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Status                SolverStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=pegasus.optimizer.core.v1.SolverStatus" json:"status,omitempty"`
	MatrixSize            int32                  `protobuf:"varint,9,opt,name=matrix_size,json=matrixSize,proto3" json:"matrix_size,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CPSATResponse) Reset() {
	*x = CPSATResponse{}
	mi := &file_optimizer_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPSATResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPSATResponse) ProtoMessage() {}

func (x *CPSATResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPSATResponse.ProtoReflect.Descriptor instead.
func (*CPSATResponse) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{12}
}

func (x *CPSATResponse) GetMeta() *SolverMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CPSATResponse) GetFeasible() bool {
	if x != nil {
		return x.Feasible
	}
	return false
}

func (x *CPSATResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *CPSATResponse) GetObjectiveScoreScaled() int64 {
	if x != nil {
		return x.ObjectiveScoreScaled
	}
	return 0
}

func (x *CPSATResponse) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *CPSATResponse) GetUnassignedManifestIds() []string {
	if x != nil {
		return x.UnassignedManifestIds
	}
	return nil
}

func (x *CPSATResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *CPSATResponse) GetStatus() SolverStatus {
	if x != nil {
		return x.Status
	}
	return SolverStatus_OPTIMAL
}

func (x *CPSATResponse) GetMatrixSize() int32 {
	if x != nil {
		return x.MatrixSize
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_optimizer_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{13}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_optimizer_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_optimizer_core_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_optimizer_core_proto protoreflect.FileDescriptor

const file_optimizer_core_proto_rawDesc = "" +
	"\n" +
	"\x14optimizer_core.proto\x12\x19pegasus.optimizer.core.v1\"\xcb\x02\n" +
	"\x0eSolverMetadata\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1f\n" +
	"\vsupplier_id\x18\x03 \x01(\tR\n" +
	"supplierId\x12=\n" +
	"\bjob_type\x18\x04 \x01(\x0e2\".pegasus.optimizer.core.v1.JobTypeR\ajobType\x12!\n" +
	"\fscale_factor\x18\x05 \x01(\x03R\vscaleFactor\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12*\n" +
	"\x11source_event_type\x18\a \x01(\tR\x0fsourceEventType\x12/\n" +
	"\x14requested_at_unix_ms\x18\b \x01(\x03R\x11requestedAtUnixMs\"\"\n" +
	"\bInt64Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06values\"\xe4\x01\n" +
	"\aVehicle\x12!\n" +
	"\fvehicle_uuid\x18\x01 \x01(\tR\vvehicleUuid\x12\x1f\n" +
	"\vdriver_uuid\x18\x02 \x01(\tR\n" +
	"driverUuid\x12'\n" +
	"\x0fcapacity_scaled\x18\x03 \x01(\x03R\x0ecapacityScaled\x127\n" +
	"\x18start_time_window_scaled\x18\x04 \x01(\x03R\x15startTimeWindowScaled\x123\n" +
	"\x16end_time_window_scaled\x18\x05 \x01(\x03R\x13endTimeWindowScaled\"N\n" +
	"\n" +
	"NodeDemand\x12\x1b\n" +
	"\tnode_uuid\x18\x01 \x01(\tR\bnodeUuid\x12#\n" +
	"\rdemand_scaled\x18\x02 \x01(\x03R\fdemandScaled\"\x9b\x01\n" +
	"\x0eNodeTimeWindow\x12\x1b\n" +
	"\tnode_uuid\x18\x01 \x01(\tR\bnodeUuid\x127\n" +
	"\x18start_time_window_scaled\x18\x02 \x01(\x03R\x15startTimeWindowScaled\x123\n" +
	"\x16end_time_window_scaled\x18\x03 \x01(\x03R\x13endTimeWindowScaled\"\xbd\x04\n" +
	"\n" +
	"VRPRequest\x12=\n" +
	"\x04meta\x18\x01 \x01(\v2).pegasus.optimizer.core.v1.SolverMetadataR\x04meta\x12&\n" +
	"\x0fdepot_node_uuid\x18\x02 \x01(\tR\rdepotNodeUuid\x12-\n" +
	"\x13drop_off_node_uuids\x18\x03 \x03(\tR\x10dropOffNodeUuids\x12Y\n" +
	"\x16distance_matrix_scaled\x18\x04 \x03(\v2#.pegasus.optimizer.core.v1.Int64RowR\x14distanceMatrixScaled\x12>\n" +
	"\bvehicles\x18\x05 \x03(\v2\".pegasus.optimizer.core.v1.VehicleR\bvehicles\x12H\n" +
	"\fnode_demands\x18\x06 \x03(\v2%.pegasus.optimizer.core.v1.NodeDemandR\vnodeDemands\x12U\n" +
	"\x11node_time_windows\x18\a \x03(\v2).pegasus.optimizer.core.v1.NodeTimeWindowR\x0fnodeTimeWindows\x12/\n" +
	"\x14solver_time_limit_ms\x18\b \x01(\x03R\x11solverTimeLimitMs\x12,\n" +
	"\x12return_best_effort\x18\t \x01(\bR\x10returnBestEffort\"\xcd\x01\n" +
	"\fVehicleRoute\x12!\n" +
	"\fvehicle_uuid\x18\x01 \x01(\tR\vvehicleUuid\x12\x1f\n" +
	"\vdriver_uuid\x18\x02 \x01(\tR\n" +
	"driverUuid\x12,\n" +
	"\x12ordered_node_uuids\x18\x03 \x03(\tR\x10orderedNodeUuids\x12\x1f\n" +
	"\vload_scaled\x18\x04 \x01(\x03R\n" +
	"loadScaled\x12*\n" +
	"\x11route_cost_scaled\x18\x05 \x01(\x03R\x0frouteCostScaled\"\xac\x03\n" +
	"\vVRPResponse\x12=\n" +
	"\x04meta\x18\x01 \x01(\v2).pegasus.optimizer.core.v1.SolverMetadataR\x04meta\x12\x1a\n" +
	"\bfeasible\x18\x02 \x01(\bR\bfeasible\x12\x1b\n" +
	"\ttimed_out\x18\x03 \x01(\bR\btimedOut\x122\n" +
	"\x15objective_cost_scaled\x18\x04 \x01(\x03R\x13objectiveCostScaled\x12?\n" +
	"\x06routes\x18\x05 \x03(\v2'.pegasus.optimizer.core.v1.VehicleRouteR\x06routes\x122\n" +
	"\x15unassigned_node_uuids\x18\x06 \x03(\tR\x13unassignedNodeUuids\x12\x1a\n" +
	"\bwarnings\x18\a \x03(\tR\bwarnings\x12?\n" +
	"\x06status\x18\b \x01(\x0e2'.pegasus.optimizer.core.v1.SolverStatusR\x06status\x12\x1f\n" +
	"\vmatrix_size\x18\t \x01(\x05R\n" +
	"matrixSize\"k\n" +
	"\vFactorySlot\x12*\n" +
	"\x11factory_node_uuid\x18\x01 \x01(\tR\x0ffactoryNodeUuid\x120\n" +
	"\x14slot_capacity_scaled\x18\x02 \x01(\x03R\x12slotCapacityScaled\"\xe3\x01\n" +
	"\x13ManifestRequirement\x12\x1f\n" +
	"\vmanifest_id\x18\x01 \x01(\tR\n" +
	"manifestId\x128\n" +
	"\x18required_capacity_scaled\x18\x02 \x01(\x03R\x16requiredCapacityScaled\x122\n" +
	"\x15priority_score_scaled\x18\x03 \x01(\x03R\x13priorityScoreScaled\x12=\n" +
	"\x1beligible_factory_node_uuids\x18\x04 \x03(\tR\x18eligibleFactoryNodeUuids\"\x8c\x03\n" +
	"\fCPSATRequest\x12=\n" +
	"\x04meta\x18\x01 \x01(\v2).pegasus.optimizer.core.v1.SolverMetadataR\x04meta\x12K\n" +
	"\rfactory_slots\x18\x02 \x03(\v2&.pegasus.optimizer.core.v1.FactorySlotR\ffactorySlots\x12c\n" +
	"\x15manifest_requirements\x18\x03 \x03(\v2..pegasus.optimizer.core.v1.ManifestRequirementR\x14manifestRequirements\x12/\n" +
	"\x14solver_time_limit_ms\x18\x04 \x01(\x03R\x11solverTimeLimitMs\x12,\n" +
	"\x12return_best_effort\x18\x05 \x01(\bR\x10returnBestEffort\x12,\n" +
	"\x12num_search_workers\x18\x06 \x01(\x05R\x10numSearchWorkers\"u\n" +
	"\n" +
	"Assignment\x12\x1f\n" +
	"\vmanifest_id\x18\x01 \x01(\tR\n" +
	"manifestId\x12*\n" +
	"\x11factory_node_uuid\x18\x02 \x01(\tR\x0ffactoryNodeUuid\x12\x1a\n" +
	"\bassigned\x18\x03 \x01(\bR\bassigned\"\xbc\x03\n" +
	"\rCPSATResponse\x12=\n" +
	"\x04meta\x18\x01 \x01(\v2).pegasus.optimizer.core.v1.SolverMetadataR\x04meta\x12\x1a\n" +
	"\bfeasible\x18\x02 \x01(\bR\bfeasible\x12\x1b\n" +
	"\ttimed_out\x18\x03 \x01(\bR\btimedOut\x124\n" +
	"\x16objective_score_scaled\x18\x04 \x01(\x03R\x14objectiveScoreScaled\x12G\n" +
	"\vassignments\x18\x05 \x03(\v2%.pegasus.optimizer.core.v1.AssignmentR\vassignments\x126\n" +
	"\x17unassigned_manifest_ids\x18\x06 \x03(\tR\x15unassignedManifestIds\x12\x1a\n" +
	"\bwarnings\x18\a \x03(\tR\bwarnings\x12?\n" +
	"\x06status\x18\b \x01(\x0e2'.pegasus.optimizer.core.v1.SolverStatusR\x06status\x12\x1f\n" +
	"\vmatrix_size\x18\t \x01(\x05R\n" +
	"matrixSize\"\x14\n" +
	"\x12HealthCheckRequest\"?\n" +
	"\x13HealthCheckResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice*\x85\x01\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fJOB_TYPE_CTP\x10\x01\x12\x11\n" +
	"\rJOB_TYPE_MEIO\x10\x02\x12\x1f\n" +
	"\x1bJOB_TYPE_FACTORY_SCHEDULING\x10\x03\x12\x1a\n" +
	"\x16JOB_TYPE_FLEET_ROUTING\x10\x04*L\n" +
	"\fSolverStatus\x12\v\n" +
	"\aOPTIMAL\x10\x00\x12\f\n" +
	"\bFEASIBLE\x10\x01\x12\x0e\n" +
	"\n" +
	"INFEASIBLE\x10\x02\x12\x11\n" +
	"\rMODEL_INVALID\x10\x032\xcd\x02\n" +
	"\x14OptimizerCoreService\x12_\n" +
	"\x0eCalculateRoute\x12%.pegasus.optimizer.core.v1.VRPRequest\x1a&.pegasus.optimizer.core.v1.VRPResponse\x12f\n" +
	"\x11ResolveConstraint\x12'.pegasus.optimizer.core.v1.CPSATRequest\x1a(.pegasus.optimizer.core.v1.CPSATResponse\x12l\n" +
	"\vHealthCheck\x12-.pegasus.optimizer.core.v1.HealthCheckRequest\x1a..pegasus.optimizer.core.v1.HealthCheckResponseB;Z9optimizercoreadapter/internal/optimizerpb;optimizercorepbb\x06proto3"

var (
	file_optimizer_core_proto_rawDescOnce sync.Once
	file_optimizer_core_proto_rawDescData []byte
)

func file_optimizer_core_proto_rawDescGZIP() []byte {
	file_optimizer_core_proto_rawDescOnce.Do(func() {
		file_optimizer_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optimizer_core_proto_rawDesc), len(file_optimizer_core_proto_rawDesc)))
	})
	return file_optimizer_core_proto_rawDescData
}

var file_optimizer_core_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_optimizer_core_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_optimizer_core_proto_goTypes = []any{
	(JobType)(0),                // 0: pegasus.optimizer.core.v1.JobType
	(SolverStatus)(0),           // 1: pegasus.optimizer.core.v1.SolverStatus
	(*SolverMetadata)(nil),      // 2: pegasus.optimizer.core.v1.SolverMetadata
	(*Int64Row)(nil),            // 3: pegasus.optimizer.core.v1.Int64Row
	(*Vehicle)(nil),             // 4: pegasus.optimizer.core.v1.Vehicle
	(*NodeDemand)(nil),          // 5: pegasus.optimizer.core.v1.NodeDemand
	(*NodeTimeWindow)(nil),      // 6: pegasus.optimizer.core.v1.NodeTimeWindow
	(*VRPRequest)(nil),          // 7: pegasus.optimizer.core.v1.VRPRequest
	(*VehicleRoute)(nil),        // 8: pegasus.optimizer.core.v1.VehicleRoute
	(*VRPResponse)(nil),         // 9: pegasus.optimizer.core.v1.VRPResponse
	(*FactorySlot)(nil),         // 10: pegasus.optimizer.core.v1.FactorySlot
	(*ManifestRequirement)(nil), // 11: pegasus.optimizer.core.v1.ManifestRequirement
	(*CPSATRequest)(nil),        // 12: pegasus.optimizer.core.v1.CPSATRequest
	(*Assignment)(nil),          // 13: pegasus.optimizer.core.v1.Assignment
	(*CPSATResponse)(nil),       // 14: pegasus.optimizer.core.v1.CPSATResponse
	(*HealthCheckRequest)(nil),  // 15: pegasus.optimizer.core.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 16: pegasus.optimizer.core.v1.HealthCheckResponse
}
var file_optimizer_core_proto_depIdxs = []int32{
	0,  // 0: pegasus.optimizer.core.v1.SolverMetadata.job_type:type_name -> pegasus.optimizer.core.v1.JobType
	2,  // 1: pegasus.optimizer.core.v1.VRPRequest.meta:type_name -> pegasus.optimizer.core.v1.SolverMetadata
	3,  // 2: pegasus.optimizer.core.v1.VRPRequest.distance_matrix_scaled:type_name -> pegasus.optimizer.core.v1.Int64Row
	4,  // 3: pegasus.optimizer.core.v1.VRPRequest.vehicles:type_name -> pegasus.optimizer.core.v1.Vehicle
	5,  // 4: pegasus.optimizer.core.v1.VRPRequest.node_demands:type_name -> pegasus.optimizer.core.v1.NodeDemand
	6,  // 5: pegasus.optimizer.core.v1.VRPRequest.node_time_windows:type_name -> pegasus.optimizer.core.v1.NodeTimeWindow
	2,  // 6: pegasus.optimizer.core.v1.VRPResponse.meta:type_name -> pegasus.optimizer.core.v1.SolverMetadata
	8,  // 7: pegasus.optimizer.core.v1.VRPResponse.routes:type_name -> pegasus.optimizer.core.v1.VehicleRoute
	1,  // 8: pegasus.optimizer.core.v1.VRPResponse.status:type_name -> pegasus.optimizer.core.v1.SolverStatus
	2,  // 9: pegasus.optimizer.core.v1.CPSATRequest.meta:type_name -> pegasus.optimizer.core.v1.SolverMetadata
	10, // 10: pegasus.optimizer.core.v1.CPSATRequest.factory_slots:type_name -> pegasus.optimizer.core.v1.FactorySlot
	11, // 11: pegasus.optimizer.core.v1.CPSATRequest.manifest_requirements:type_name -> pegasus.optimizer.core.v1.ManifestRequirement
	2,  // 12: pegasus.optimizer.core.v1.CPSATResponse.meta:type_name -> pegasus.optimizer.core.v1.SolverMetadata
	13, // 13: pegasus.optimizer.core.v1.CPSATResponse.assignments:type_name -> pegasus.optimizer.core.v1.Assignment
	1,  // 14: pegasus.optimizer.core.v1.CPSATResponse.status:type_name -> pegasus.optimizer.core.v1.SolverStatus
	7,  // 15: pegasus.optimizer.core.v1.OptimizerCoreService.CalculateRoute:input_type -> pegasus.optimizer.core.v1.VRPRequest
	12, // 16: pegasus.optimizer.core.v1.OptimizerCoreService.ResolveConstraint:input_type -> pegasus.optimizer.core.v1.CPSATRequest
	15, // 17: pegasus.optimizer.core.v1.OptimizerCoreService.HealthCheck:input_type -> pegasus.optimizer.core.v1.HealthCheckRequest
	9,  // 18: pegasus.optimizer.core.v1.OptimizerCoreService.CalculateRoute:output_type -> pegasus.optimizer.core.v1.VRPResponse
	14, // 19: pegasus.optimizer.core.v1.OptimizerCoreService.ResolveConstraint:output_type -> pegasus.optimizer.core.v1.CPSATResponse
	16, // 20: pegasus.optimizer.core.v1.OptimizerCoreService.HealthCheck:output_type -> pegasus.optimizer.core.v1.HealthCheckResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_optimizer_core_proto_init() }
func file_optimizer_core_proto_init() {
	if File_optimizer_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optimizer_core_proto_rawDesc), len(file_optimizer_core_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optimizer_core_proto_goTypes,
		DependencyIndexes: file_optimizer_core_proto_depIdxs,
		EnumInfos:         file_optimizer_core_proto_enumTypes,
		MessageInfos:      file_optimizer_core_proto_msgTypes,
	}.Build()
	File_optimizer_core_proto = out.File
	file_optimizer_core_proto_goTypes = nil
	file_optimizer_core_proto_depIdxs = nil
}
