/** ISO 3166-1 alpha-2 country list with dialing prefixes for international registration. */
export interface Country {
  label: string;
  value: string; // ISO alpha-2
  code: string;  // dialing prefix with +
}

export const COUNTRIES: Country[] = [
  { label: 'Uzbekistan', value: 'UZ', code: '+998' },
  { label: 'Kazakhstan', value: 'KZ', code: '+7' },
  { label: 'Kyrgyzstan', value: 'KG', code: '+996' },
  { label: 'Tajikistan', value: 'TJ', code: '+992' },
  { label: 'Turkmenistan', value: 'TM', code: '+993' },
  { label: 'Russia', value: 'RU', code: '+7' },
  { label: 'Azerbaijan', value: 'AZ', code: '+994' },
  { label: 'Georgia', value: 'GE', code: '+995' },
  { label: 'Turkey', value: 'TR', code: '+90' },
  { label: 'United Arab Emirates', value: 'AE', code: '+971' },
  { label: 'Saudi Arabia', value: 'SA', code: '+966' },
  { label: 'Qatar', value: 'QA', code: '+974' },
  { label: 'Bahrain', value: 'BH', code: '+973' },
  { label: 'Kuwait', value: 'KW', code: '+965' },
  { label: 'Oman', value: 'OM', code: '+968' },
  { label: 'Iran', value: 'IR', code: '+98' },
  { label: 'Iraq', value: 'IQ', code: '+964' },
  { label: 'Afghanistan', value: 'AF', code: '+93' },
  { label: 'Pakistan', value: 'PK', code: '+92' },
  { label: 'India', value: 'IN', code: '+91' },
  { label: 'Bangladesh', value: 'BD', code: '+880' },
  { label: 'Sri Lanka', value: 'LK', code: '+94' },
  { label: 'Nepal', value: 'NP', code: '+977' },
  { label: 'China', value: 'CN', code: '+86' },
  { label: 'Japan', value: 'JP', code: '+81' },
  { label: 'South Korea', value: 'KR', code: '+82' },
  { label: 'Mongolia', value: 'MN', code: '+976' },
  { label: 'Thailand', value: 'TH', code: '+66' },
  { label: 'Vietnam', value: 'VN', code: '+84' },
  { label: 'Malaysia', value: 'MY', code: '+60' },
  { label: 'Indonesia', value: 'ID', code: '+62' },
  { label: 'Philippines', value: 'PH', code: '+63' },
  { label: 'Singapore', value: 'SG', code: '+65' },
  { label: 'Egypt', value: 'EG', code: '+20' },
  { label: 'Nigeria', value: 'NG', code: '+234' },
  { label: 'South Africa', value: 'ZA', code: '+27' },
  { label: 'Kenya', value: 'KE', code: '+254' },
  { label: 'Ethiopia', value: 'ET', code: '+251' },
  { label: 'Ghana', value: 'GH', code: '+233' },
  { label: 'Tanzania', value: 'TZ', code: '+255' },
  { label: 'Morocco', value: 'MA', code: '+212' },
  { label: 'Algeria', value: 'AL', code: '+213' },
  { label: 'Tunisia', value: 'TN', code: '+216' },
  { label: 'Ukraine', value: 'UA', code: '+380' },
  { label: 'Belarus', value: 'BY', code: '+375' },
  { label: 'Moldova', value: 'MD', code: '+373' },
  { label: 'Armenia', value: 'AM', code: '+374' },
  { label: 'Poland', value: 'PL', code: '+48' },
  { label: 'Germany', value: 'DE', code: '+49' },
  { label: 'France', value: 'FR', code: '+33' },
  { label: 'United Kingdom', value: 'GB', code: '+44' },
  { label: 'Italy', value: 'IT', code: '+39' },
  { label: 'Spain', value: 'ES', code: '+34' },
  { label: 'Netherlands', value: 'NL', code: '+31' },
  { label: 'Belgium', value: 'BE', code: '+32' },
  { label: 'Switzerland', value: 'CH', code: '+41' },
  { label: 'Austria', value: 'AT', code: '+43' },
  { label: 'Sweden', value: 'SE', code: '+46' },
  { label: 'Norway', value: 'NO', code: '+47' },
  { label: 'Denmark', value: 'DK', code: '+45' },
  { label: 'Finland', value: 'FI', code: '+358' },
  { label: 'Czech Republic', value: 'CZ', code: '+420' },
  { label: 'Romania', value: 'RO', code: '+40' },
  { label: 'Hungary', value: 'HU', code: '+36' },
  { label: 'Bulgaria', value: 'BG', code: '+359' },
  { label: 'Serbia', value: 'RS', code: '+381' },
  { label: 'Croatia', value: 'HR', code: '+385' },
  { label: 'Greece', value: 'GR', code: '+30' },
  { label: 'Portugal', value: 'PT', code: '+351' },
  { label: 'Ireland', value: 'IE', code: '+353' },
  { label: 'Canada', value: 'CA', code: '+1' },
  { label: 'United States', value: 'US', code: '+1' },
  { label: 'Mexico', value: 'MX', code: '+52' },
  { label: 'Brazil', value: 'BR', code: '+55' },
  { label: 'Argentina', value: 'AR', code: '+54' },
  { label: 'Colombia', value: 'CO', code: '+57' },
  { label: 'Chile', value: 'CL', code: '+56' },
  { label: 'Peru', value: 'PE', code: '+51' },
  { label: 'Australia', value: 'AU', code: '+61' },
  { label: 'New Zealand', value: 'NZ', code: '+64' },
  { label: 'Israel', value: 'IL', code: '+972' },
  { label: 'Jordan', value: 'JO', code: '+962' },
  { label: 'Lebanon', value: 'LB', code: '+961' },
  { label: 'Latvia', value: 'LV', code: '+371' },
  { label: 'Lithuania', value: 'LT', code: '+370' },
  { label: 'Estonia', value: 'EE', code: '+372' },
  { label: 'Slovakia', value: 'SK', code: '+421' },
  { label: 'Slovenia', value: 'SI', code: '+386' },
  { label: 'Cambodia', value: 'KH', code: '+855' },
  { label: 'Myanmar', value: 'MM', code: '+95' },
  { label: 'Laos', value: 'LA', code: '+856' },
];

export const DEFAULT_COUNTRY = 'UZ';

export function findCountry(code: string): Country | undefined {
  return COUNTRIES.find(c => c.value === code);
}

export function dialingPrefix(code: string): string {
  return findCountry(code)?.code ?? '+998';
}
