/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssuePartnerApiKeyRequest
 */
export interface IssuePartnerApiKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof IssuePartnerApiKeyRequest
     */
    tenantType?: IssuePartnerApiKeyRequestTenantTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof IssuePartnerApiKeyRequest
     */
    tenantId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IssuePartnerApiKeyRequest
     */
    scopes?: Array<string>;
}


/**
 * @export
 */
export const IssuePartnerApiKeyRequestTenantTypeEnum = {
    Retailer: 'RETAILER',
    Supplier: 'SUPPLIER'
} as const;
export type IssuePartnerApiKeyRequestTenantTypeEnum = typeof IssuePartnerApiKeyRequestTenantTypeEnum[keyof typeof IssuePartnerApiKeyRequestTenantTypeEnum];


/**
 * Check if a given object implements the IssuePartnerApiKeyRequest interface.
 */
export function instanceOfIssuePartnerApiKeyRequest(value: object): value is IssuePartnerApiKeyRequest {
    return true;
}

export function IssuePartnerApiKeyRequestFromJSON(json: any): IssuePartnerApiKeyRequest {
    return IssuePartnerApiKeyRequestFromJSONTyped(json, false);
}

export function IssuePartnerApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuePartnerApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantType': json['tenant_type'] == null ? undefined : json['tenant_type'],
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
    };
}

export function IssuePartnerApiKeyRequestToJSON(json: any): IssuePartnerApiKeyRequest {
    return IssuePartnerApiKeyRequestToJSONTyped(json, false);
}

export function IssuePartnerApiKeyRequestToJSONTyped(value?: IssuePartnerApiKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenant_type': value['tenantType'],
        'tenant_id': value['tenantId'],
        'scopes': value['scopes'],
    };
}

