/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartnerWebhookSubscription } from './PartnerWebhookSubscription';
import {
    PartnerWebhookSubscriptionFromJSON,
    PartnerWebhookSubscriptionFromJSONTyped,
    PartnerWebhookSubscriptionToJSON,
    PartnerWebhookSubscriptionToJSONTyped,
} from './PartnerWebhookSubscription';

/**
 * 
 * @export
 * @interface PartnerListWebhooks200Response
 */
export interface PartnerListWebhooks200Response {
    /**
     * 
     * @type {Array<PartnerWebhookSubscription>}
     * @memberof PartnerListWebhooks200Response
     */
    subscriptions?: Array<PartnerWebhookSubscription>;
}

/**
 * Check if a given object implements the PartnerListWebhooks200Response interface.
 */
export function instanceOfPartnerListWebhooks200Response(value: object): value is PartnerListWebhooks200Response {
    return true;
}

export function PartnerListWebhooks200ResponseFromJSON(json: any): PartnerListWebhooks200Response {
    return PartnerListWebhooks200ResponseFromJSONTyped(json, false);
}

export function PartnerListWebhooks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerListWebhooks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptions': json['subscriptions'] == null ? undefined : ((json['subscriptions'] as Array<any>).map(PartnerWebhookSubscriptionFromJSON)),
    };
}

export function PartnerListWebhooks200ResponseToJSON(json: any): PartnerListWebhooks200Response {
    return PartnerListWebhooks200ResponseToJSONTyped(json, false);
}

export function PartnerListWebhooks200ResponseToJSONTyped(value?: PartnerListWebhooks200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscriptions': value['subscriptions'] == null ? undefined : ((value['subscriptions'] as Array<any>).map(PartnerWebhookSubscriptionToJSON)),
    };
}

