/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerCreateOrderRequestLineItemsInner
 */
export interface PartnerCreateOrderRequestLineItemsInner {
    /**
     * 
     * @type {string}
     * @memberof PartnerCreateOrderRequestLineItemsInner
     */
    sku?: string;
    /**
     * 
     * @type {number}
     * @memberof PartnerCreateOrderRequestLineItemsInner
     */
    quantity?: number;
}

/**
 * Check if a given object implements the PartnerCreateOrderRequestLineItemsInner interface.
 */
export function instanceOfPartnerCreateOrderRequestLineItemsInner(value: object): value is PartnerCreateOrderRequestLineItemsInner {
    return true;
}

export function PartnerCreateOrderRequestLineItemsInnerFromJSON(json: any): PartnerCreateOrderRequestLineItemsInner {
    return PartnerCreateOrderRequestLineItemsInnerFromJSONTyped(json, false);
}

export function PartnerCreateOrderRequestLineItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerCreateOrderRequestLineItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'sku': json['sku'] == null ? undefined : json['sku'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function PartnerCreateOrderRequestLineItemsInnerToJSON(json: any): PartnerCreateOrderRequestLineItemsInner {
    return PartnerCreateOrderRequestLineItemsInnerToJSONTyped(json, false);
}

export function PartnerCreateOrderRequestLineItemsInnerToJSONTyped(value?: PartnerCreateOrderRequestLineItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sku': value['sku'],
        'quantity': value['quantity'],
    };
}

