/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerPOSDemandFeedRequestLinesInner
 */
export interface PartnerPOSDemandFeedRequestLinesInner {
    /**
     * 
     * @type {string}
     * @memberof PartnerPOSDemandFeedRequestLinesInner
     */
    externalId: string;
    /**
     * 
     * @type {number}
     * @memberof PartnerPOSDemandFeedRequestLinesInner
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof PartnerPOSDemandFeedRequestLinesInner
     */
    unit?: string;
}

/**
 * Check if a given object implements the PartnerPOSDemandFeedRequestLinesInner interface.
 */
export function instanceOfPartnerPOSDemandFeedRequestLinesInner(value: object): value is PartnerPOSDemandFeedRequestLinesInner {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function PartnerPOSDemandFeedRequestLinesInnerFromJSON(json: any): PartnerPOSDemandFeedRequestLinesInner {
    return PartnerPOSDemandFeedRequestLinesInnerFromJSONTyped(json, false);
}

export function PartnerPOSDemandFeedRequestLinesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerPOSDemandFeedRequestLinesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['external_id'],
        'quantity': json['quantity'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function PartnerPOSDemandFeedRequestLinesInnerToJSON(json: any): PartnerPOSDemandFeedRequestLinesInner {
    return PartnerPOSDemandFeedRequestLinesInnerToJSONTyped(json, false);
}

export function PartnerPOSDemandFeedRequestLinesInnerToJSONTyped(value?: PartnerPOSDemandFeedRequestLinesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_id': value['externalId'],
        'quantity': value['quantity'],
        'unit': value['unit'],
    };
}

