/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerExportJob
 */
export interface PartnerExportJob {
    /**
     * 
     * @type {string}
     * @memberof PartnerExportJob
     */
    jobId?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerExportJob
     */
    tenantType?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerExportJob
     */
    tenantId?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerExportJob
     */
    resource?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerExportJob
     */
    format?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerExportJob
     */
    status?: PartnerExportJobStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PartnerExportJob
     */
    rowCount?: number;
    /**
     * 
     * @type {string}
     * @memberof PartnerExportJob
     */
    sftpStatus?: PartnerExportJobSftpStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PartnerExportJob
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerExportJob
     */
    downloadUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerExportJob
     */
    objectPath?: string;
    /**
     * 
     * @type {Date}
     * @memberof PartnerExportJob
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PartnerExportJob
     */
    finishedAt?: Date;
}


/**
 * @export
 */
export const PartnerExportJobStatusEnum = {
    Pending: 'PENDING',
    Running: 'RUNNING',
    Succeeded: 'SUCCEEDED',
    Failed: 'FAILED'
} as const;
export type PartnerExportJobStatusEnum = typeof PartnerExportJobStatusEnum[keyof typeof PartnerExportJobStatusEnum];

/**
 * @export
 */
export const PartnerExportJobSftpStatusEnum = {
    Skipped: 'SKIPPED',
    Uploaded: 'UPLOADED',
    Failed: 'FAILED'
} as const;
export type PartnerExportJobSftpStatusEnum = typeof PartnerExportJobSftpStatusEnum[keyof typeof PartnerExportJobSftpStatusEnum];


/**
 * Check if a given object implements the PartnerExportJob interface.
 */
export function instanceOfPartnerExportJob(value: object): value is PartnerExportJob {
    return true;
}

export function PartnerExportJobFromJSON(json: any): PartnerExportJob {
    return PartnerExportJobFromJSONTyped(json, false);
}

export function PartnerExportJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerExportJob {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'] == null ? undefined : json['job_id'],
        'tenantType': json['tenant_type'] == null ? undefined : json['tenant_type'],
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'resource': json['resource'] == null ? undefined : json['resource'],
        'format': json['format'] == null ? undefined : json['format'],
        'status': json['status'] == null ? undefined : json['status'],
        'rowCount': json['row_count'] == null ? undefined : json['row_count'],
        'sftpStatus': json['sftp_status'] == null ? undefined : json['sftp_status'],
        'error': json['error'] == null ? undefined : json['error'],
        'downloadUrl': json['download_url'] == null ? undefined : json['download_url'],
        'objectPath': json['object_path'] == null ? undefined : json['object_path'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'finishedAt': json['finished_at'] == null ? undefined : (new Date(json['finished_at'])),
    };
}

export function PartnerExportJobToJSON(json: any): PartnerExportJob {
    return PartnerExportJobToJSONTyped(json, false);
}

export function PartnerExportJobToJSONTyped(value?: PartnerExportJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'tenant_type': value['tenantType'],
        'tenant_id': value['tenantId'],
        'resource': value['resource'],
        'format': value['format'],
        'status': value['status'],
        'row_count': value['rowCount'],
        'sftp_status': value['sftpStatus'],
        'error': value['error'],
        'download_url': value['downloadUrl'],
        'object_path': value['objectPath'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'finished_at': value['finishedAt'] == null ? undefined : ((value['finishedAt']).toISOString()),
    };
}

