/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerWebhookSubscription
 */
export interface PartnerWebhookSubscription {
    /**
     * 
     * @type {string}
     * @memberof PartnerWebhookSubscription
     */
    subscriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerWebhookSubscription
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PartnerWebhookSubscription
     */
    eventTypes?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerWebhookSubscription
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PartnerWebhookSubscription
     */
    secretPrefix?: string;
    /**
     * 
     * @type {Date}
     * @memberof PartnerWebhookSubscription
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the PartnerWebhookSubscription interface.
 */
export function instanceOfPartnerWebhookSubscription(value: object): value is PartnerWebhookSubscription {
    return true;
}

export function PartnerWebhookSubscriptionFromJSON(json: any): PartnerWebhookSubscription {
    return PartnerWebhookSubscriptionFromJSONTyped(json, false);
}

export function PartnerWebhookSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerWebhookSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptionId': json['subscription_id'] == null ? undefined : json['subscription_id'],
        'url': json['url'] == null ? undefined : json['url'],
        'eventTypes': json['event_types'] == null ? undefined : json['event_types'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'secretPrefix': json['secret_prefix'] == null ? undefined : json['secret_prefix'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function PartnerWebhookSubscriptionToJSON(json: any): PartnerWebhookSubscription {
    return PartnerWebhookSubscriptionToJSONTyped(json, false);
}

export function PartnerWebhookSubscriptionToJSONTyped(value?: PartnerWebhookSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscription_id': value['subscriptionId'],
        'url': value['url'],
        'event_types': value['eventTypes'],
        'is_active': value['isActive'],
        'secret_prefix': value['secretPrefix'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

