/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartnerPOSDemandFeedRequestLinesInner } from './PartnerPOSDemandFeedRequestLinesInner';
import {
    PartnerPOSDemandFeedRequestLinesInnerFromJSON,
    PartnerPOSDemandFeedRequestLinesInnerFromJSONTyped,
    PartnerPOSDemandFeedRequestLinesInnerToJSON,
    PartnerPOSDemandFeedRequestLinesInnerToJSONTyped,
} from './PartnerPOSDemandFeedRequestLinesInner';

/**
 * 
 * @export
 * @interface PartnerPOSDemandFeedRequest
 */
export interface PartnerPOSDemandFeedRequest {
    /**
     * 
     * @type {string}
     * @memberof PartnerPOSDemandFeedRequest
     */
    storeId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PartnerPOSDemandFeedRequest
     */
    observedAt?: Date;
    /**
     * 
     * @type {Array<PartnerPOSDemandFeedRequestLinesInner>}
     * @memberof PartnerPOSDemandFeedRequest
     */
    lines: Array<PartnerPOSDemandFeedRequestLinesInner>;
}

/**
 * Check if a given object implements the PartnerPOSDemandFeedRequest interface.
 */
export function instanceOfPartnerPOSDemandFeedRequest(value: object): value is PartnerPOSDemandFeedRequest {
    if (!('lines' in value) || value['lines'] === undefined) return false;
    return true;
}

export function PartnerPOSDemandFeedRequestFromJSON(json: any): PartnerPOSDemandFeedRequest {
    return PartnerPOSDemandFeedRequestFromJSONTyped(json, false);
}

export function PartnerPOSDemandFeedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerPOSDemandFeedRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'storeId': json['store_id'] == null ? undefined : json['store_id'],
        'observedAt': json['observed_at'] == null ? undefined : (new Date(json['observed_at'])),
        'lines': ((json['lines'] as Array<any>).map(PartnerPOSDemandFeedRequestLinesInnerFromJSON)),
    };
}

export function PartnerPOSDemandFeedRequestToJSON(json: any): PartnerPOSDemandFeedRequest {
    return PartnerPOSDemandFeedRequestToJSONTyped(json, false);
}

export function PartnerPOSDemandFeedRequestToJSONTyped(value?: PartnerPOSDemandFeedRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'store_id': value['storeId'],
        'observed_at': value['observedAt'] == null ? undefined : ((value['observedAt']).toISOString()),
        'lines': ((value['lines'] as Array<any>).map(PartnerPOSDemandFeedRequestLinesInnerToJSON)),
    };
}

