/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerStockUpsertRequestItemsInner
 */
export interface PartnerStockUpsertRequestItemsInner {
    /**
     * 
     * @type {string}
     * @memberof PartnerStockUpsertRequestItemsInner
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerStockUpsertRequestItemsInner
     */
    warehouseId: string;
    /**
     * 
     * @type {number}
     * @memberof PartnerStockUpsertRequestItemsInner
     */
    quantityOnHand: number;
    /**
     * 
     * @type {number}
     * @memberof PartnerStockUpsertRequestItemsInner
     */
    reorderThreshold?: number;
}

/**
 * Check if a given object implements the PartnerStockUpsertRequestItemsInner interface.
 */
export function instanceOfPartnerStockUpsertRequestItemsInner(value: object): value is PartnerStockUpsertRequestItemsInner {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('warehouseId' in value) || value['warehouseId'] === undefined) return false;
    if (!('quantityOnHand' in value) || value['quantityOnHand'] === undefined) return false;
    return true;
}

export function PartnerStockUpsertRequestItemsInnerFromJSON(json: any): PartnerStockUpsertRequestItemsInner {
    return PartnerStockUpsertRequestItemsInnerFromJSONTyped(json, false);
}

export function PartnerStockUpsertRequestItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerStockUpsertRequestItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['external_id'],
        'warehouseId': json['warehouse_id'],
        'quantityOnHand': json['quantity_on_hand'],
        'reorderThreshold': json['reorder_threshold'] == null ? undefined : json['reorder_threshold'],
    };
}

export function PartnerStockUpsertRequestItemsInnerToJSON(json: any): PartnerStockUpsertRequestItemsInner {
    return PartnerStockUpsertRequestItemsInnerToJSONTyped(json, false);
}

export function PartnerStockUpsertRequestItemsInnerToJSONTyped(value?: PartnerStockUpsertRequestItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_id': value['externalId'],
        'warehouse_id': value['warehouseId'],
        'quantity_on_hand': value['quantityOnHand'],
        'reorder_threshold': value['reorderThreshold'],
    };
}

