/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerOAuthTokenRequest
 */
export interface PartnerOAuthTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof PartnerOAuthTokenRequest
     */
    grantType: PartnerOAuthTokenRequestGrantTypeEnum;
    /**
     * PartnerApiKeys.KeyId or KeyPrefix
     * @type {string}
     * @memberof PartnerOAuthTokenRequest
     */
    clientId?: string;
    /**
     * Full pxk_… plaintext
     * @type {string}
     * @memberof PartnerOAuthTokenRequest
     */
    clientSecret: string;
    /**
     * Space-separated subset of key scopes
     * @type {string}
     * @memberof PartnerOAuthTokenRequest
     */
    scope?: string;
}


/**
 * @export
 */
export const PartnerOAuthTokenRequestGrantTypeEnum = {
    ClientCredentials: 'client_credentials'
} as const;
export type PartnerOAuthTokenRequestGrantTypeEnum = typeof PartnerOAuthTokenRequestGrantTypeEnum[keyof typeof PartnerOAuthTokenRequestGrantTypeEnum];


/**
 * Check if a given object implements the PartnerOAuthTokenRequest interface.
 */
export function instanceOfPartnerOAuthTokenRequest(value: object): value is PartnerOAuthTokenRequest {
    if (!('grantType' in value) || value['grantType'] === undefined) return false;
    if (!('clientSecret' in value) || value['clientSecret'] === undefined) return false;
    return true;
}

export function PartnerOAuthTokenRequestFromJSON(json: any): PartnerOAuthTokenRequest {
    return PartnerOAuthTokenRequestFromJSONTyped(json, false);
}

export function PartnerOAuthTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerOAuthTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'grantType': json['grant_type'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'clientSecret': json['client_secret'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function PartnerOAuthTokenRequestToJSON(json: any): PartnerOAuthTokenRequest {
    return PartnerOAuthTokenRequestToJSONTyped(json, false);
}

export function PartnerOAuthTokenRequestToJSONTyped(value?: PartnerOAuthTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grant_type': value['grantType'],
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
        'scope': value['scope'],
    };
}

