/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerOAuthTokenResponse
 */
export interface PartnerOAuthTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof PartnerOAuthTokenResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerOAuthTokenResponse
     */
    tokenType: string;
    /**
     * 
     * @type {number}
     * @memberof PartnerOAuthTokenResponse
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof PartnerOAuthTokenResponse
     */
    scope?: string;
}

/**
 * Check if a given object implements the PartnerOAuthTokenResponse interface.
 */
export function instanceOfPartnerOAuthTokenResponse(value: object): value is PartnerOAuthTokenResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function PartnerOAuthTokenResponseFromJSON(json: any): PartnerOAuthTokenResponse {
    return PartnerOAuthTokenResponseFromJSONTyped(json, false);
}

export function PartnerOAuthTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerOAuthTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'tokenType': json['token_type'],
        'expiresIn': json['expires_in'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function PartnerOAuthTokenResponseToJSON(json: any): PartnerOAuthTokenResponse {
    return PartnerOAuthTokenResponseToJSONTyped(json, false);
}

export function PartnerOAuthTokenResponseToJSONTyped(value?: PartnerOAuthTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
        'scope': value['scope'],
    };
}

