/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerCreateOrderResponse
 */
export interface PartnerCreateOrderResponse {
    /**
     * 
     * @type {string}
     * @memberof PartnerCreateOrderResponse
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerCreateOrderResponse
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof PartnerCreateOrderResponse
     */
    totalMinor?: number;
    /**
     * 
     * @type {string}
     * @memberof PartnerCreateOrderResponse
     */
    currency?: string;
}

/**
 * Check if a given object implements the PartnerCreateOrderResponse interface.
 */
export function instanceOfPartnerCreateOrderResponse(value: object): value is PartnerCreateOrderResponse {
    return true;
}

export function PartnerCreateOrderResponseFromJSON(json: any): PartnerCreateOrderResponse {
    return PartnerCreateOrderResponseFromJSONTyped(json, false);
}

export function PartnerCreateOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerCreateOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalMinor': json['total_minor'] == null ? undefined : json['total_minor'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function PartnerCreateOrderResponseToJSON(json: any): PartnerCreateOrderResponse {
    return PartnerCreateOrderResponseToJSONTyped(json, false);
}

export function PartnerCreateOrderResponseToJSONTyped(value?: PartnerCreateOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_id': value['orderId'],
        'status': value['status'],
        'total_minor': value['totalMinor'],
        'currency': value['currency'],
    };
}

