/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartnerExportJob } from './PartnerExportJob';
import {
    PartnerExportJobFromJSON,
    PartnerExportJobFromJSONTyped,
    PartnerExportJobToJSON,
    PartnerExportJobToJSONTyped,
} from './PartnerExportJob';

/**
 * 
 * @export
 * @interface PartnerListExports200Response
 */
export interface PartnerListExports200Response {
    /**
     * 
     * @type {Array<PartnerExportJob>}
     * @memberof PartnerListExports200Response
     */
    jobs?: Array<PartnerExportJob>;
}

/**
 * Check if a given object implements the PartnerListExports200Response interface.
 */
export function instanceOfPartnerListExports200Response(value: object): value is PartnerListExports200Response {
    return true;
}

export function PartnerListExports200ResponseFromJSON(json: any): PartnerListExports200Response {
    return PartnerListExports200ResponseFromJSONTyped(json, false);
}

export function PartnerListExports200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerListExports200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs': json['jobs'] == null ? undefined : ((json['jobs'] as Array<any>).map(PartnerExportJobFromJSON)),
    };
}

export function PartnerListExports200ResponseToJSON(json: any): PartnerListExports200Response {
    return PartnerListExports200ResponseToJSONTyped(json, false);
}

export function PartnerListExports200ResponseToJSONTyped(value?: PartnerListExports200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs': value['jobs'] == null ? undefined : ((value['jobs'] as Array<any>).map(PartnerExportJobToJSON)),
    };
}

