/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerProductUpsertRequestItemsInner
 */
export interface PartnerProductUpsertRequestItemsInner {
    /**
     * 
     * @type {string}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    categoryId?: string;
    /**
     * 
     * @type {number}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    priceMinor?: number;
    /**
     * 
     * @type {string}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    unit?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    barcode?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PartnerProductUpsertRequestItemsInner
     */
    handlingClass?: string;
}

/**
 * Check if a given object implements the PartnerProductUpsertRequestItemsInner interface.
 */
export function instanceOfPartnerProductUpsertRequestItemsInner(value: object): value is PartnerProductUpsertRequestItemsInner {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PartnerProductUpsertRequestItemsInnerFromJSON(json: any): PartnerProductUpsertRequestItemsInner {
    return PartnerProductUpsertRequestItemsInnerFromJSONTyped(json, false);
}

export function PartnerProductUpsertRequestItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerProductUpsertRequestItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['external_id'],
        'name': json['name'],
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'priceMinor': json['price_minor'] == null ? undefined : json['price_minor'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'barcode': json['barcode'] == null ? undefined : json['barcode'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'handlingClass': json['handling_class'] == null ? undefined : json['handling_class'],
    };
}

export function PartnerProductUpsertRequestItemsInnerToJSON(json: any): PartnerProductUpsertRequestItemsInner {
    return PartnerProductUpsertRequestItemsInnerToJSONTyped(json, false);
}

export function PartnerProductUpsertRequestItemsInnerToJSONTyped(value?: PartnerProductUpsertRequestItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_id': value['externalId'],
        'name': value['name'],
        'category_id': value['categoryId'],
        'price_minor': value['priceMinor'],
        'currency': value['currency'],
        'unit': value['unit'],
        'barcode': value['barcode'],
        'description': value['description'],
        'image_url': value['imageUrl'],
        'is_active': value['isActive'],
        'handling_class': value['handlingClass'],
    };
}

