/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartnerPriceUpsertRequestItemsInner } from './PartnerPriceUpsertRequestItemsInner';
import {
    PartnerPriceUpsertRequestItemsInnerFromJSON,
    PartnerPriceUpsertRequestItemsInnerFromJSONTyped,
    PartnerPriceUpsertRequestItemsInnerToJSON,
    PartnerPriceUpsertRequestItemsInnerToJSONTyped,
} from './PartnerPriceUpsertRequestItemsInner';

/**
 * 
 * @export
 * @interface PartnerPriceUpsertRequest
 */
export interface PartnerPriceUpsertRequest {
    /**
     * 
     * @type {Array<PartnerPriceUpsertRequestItemsInner>}
     * @memberof PartnerPriceUpsertRequest
     */
    items: Array<PartnerPriceUpsertRequestItemsInner>;
}

/**
 * Check if a given object implements the PartnerPriceUpsertRequest interface.
 */
export function instanceOfPartnerPriceUpsertRequest(value: object): value is PartnerPriceUpsertRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PartnerPriceUpsertRequestFromJSON(json: any): PartnerPriceUpsertRequest {
    return PartnerPriceUpsertRequestFromJSONTyped(json, false);
}

export function PartnerPriceUpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerPriceUpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PartnerPriceUpsertRequestItemsInnerFromJSON)),
    };
}

export function PartnerPriceUpsertRequestToJSON(json: any): PartnerPriceUpsertRequest {
    return PartnerPriceUpsertRequestToJSONTyped(json, false);
}

export function PartnerPriceUpsertRequestToJSONTyped(value?: PartnerPriceUpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PartnerPriceUpsertRequestItemsInnerToJSON)),
    };
}

