/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerAs2Config
 */
export interface PartnerAs2Config {
    /**
     * 
     * @type {boolean}
     * @memberof PartnerAs2Config
     */
    configured?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerAs2Config
     */
    as2Enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PartnerAs2Config
     */
    ourAs2Id?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerAs2Config
     */
    partnerAs2Id?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerAs2Config
     */
    partnerUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerAs2Config
     */
    ourCertSecretRef?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerAs2Config
     */
    ourKeySecretRef?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerAs2Config
     */
    partnerCertSecretRef?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerAs2Config
     */
    signRequired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerAs2Config
     */
    encryptRequired?: boolean;
}

/**
 * Check if a given object implements the PartnerAs2Config interface.
 */
export function instanceOfPartnerAs2Config(value: object): value is PartnerAs2Config {
    return true;
}

export function PartnerAs2ConfigFromJSON(json: any): PartnerAs2Config {
    return PartnerAs2ConfigFromJSONTyped(json, false);
}

export function PartnerAs2ConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerAs2Config {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'] == null ? undefined : json['configured'],
        'as2Enabled': json['as2_enabled'] == null ? undefined : json['as2_enabled'],
        'ourAs2Id': json['our_as2_id'] == null ? undefined : json['our_as2_id'],
        'partnerAs2Id': json['partner_as2_id'] == null ? undefined : json['partner_as2_id'],
        'partnerUrl': json['partner_url'] == null ? undefined : json['partner_url'],
        'ourCertSecretRef': json['our_cert_secret_ref'] == null ? undefined : json['our_cert_secret_ref'],
        'ourKeySecretRef': json['our_key_secret_ref'] == null ? undefined : json['our_key_secret_ref'],
        'partnerCertSecretRef': json['partner_cert_secret_ref'] == null ? undefined : json['partner_cert_secret_ref'],
        'signRequired': json['sign_required'] == null ? undefined : json['sign_required'],
        'encryptRequired': json['encrypt_required'] == null ? undefined : json['encrypt_required'],
    };
}

export function PartnerAs2ConfigToJSON(json: any): PartnerAs2Config {
    return PartnerAs2ConfigToJSONTyped(json, false);
}

export function PartnerAs2ConfigToJSONTyped(value?: PartnerAs2Config | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'as2_enabled': value['as2Enabled'],
        'our_as2_id': value['ourAs2Id'],
        'partner_as2_id': value['partnerAs2Id'],
        'partner_url': value['partnerUrl'],
        'our_cert_secret_ref': value['ourCertSecretRef'],
        'our_key_secret_ref': value['ourKeySecretRef'],
        'partner_cert_secret_ref': value['partnerCertSecretRef'],
        'sign_required': value['signRequired'],
        'encrypt_required': value['encryptRequired'],
    };
}

