/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerCoaMapUpdate
 */
export interface PartnerCoaMapUpdate {
    /**
     * 
     * @type {string}
     * @memberof PartnerCoaMapUpdate
     */
    accountAr?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerCoaMapUpdate
     */
    accountRevenue?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerCoaMapUpdate
     */
    accountBankCash?: string;
}

/**
 * Check if a given object implements the PartnerCoaMapUpdate interface.
 */
export function instanceOfPartnerCoaMapUpdate(value: object): value is PartnerCoaMapUpdate {
    return true;
}

export function PartnerCoaMapUpdateFromJSON(json: any): PartnerCoaMapUpdate {
    return PartnerCoaMapUpdateFromJSONTyped(json, false);
}

export function PartnerCoaMapUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerCoaMapUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'accountAr': json['account_ar'] == null ? undefined : json['account_ar'],
        'accountRevenue': json['account_revenue'] == null ? undefined : json['account_revenue'],
        'accountBankCash': json['account_bank_cash'] == null ? undefined : json['account_bank_cash'],
    };
}

export function PartnerCoaMapUpdateToJSON(json: any): PartnerCoaMapUpdate {
    return PartnerCoaMapUpdateToJSONTyped(json, false);
}

export function PartnerCoaMapUpdateToJSONTyped(value?: PartnerCoaMapUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_ar': value['accountAr'],
        'account_revenue': value['accountRevenue'],
        'account_bank_cash': value['accountBankCash'],
    };
}

