/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartnerProductUpsertRequestItemsInner } from './PartnerProductUpsertRequestItemsInner';
import {
    PartnerProductUpsertRequestItemsInnerFromJSON,
    PartnerProductUpsertRequestItemsInnerFromJSONTyped,
    PartnerProductUpsertRequestItemsInnerToJSON,
    PartnerProductUpsertRequestItemsInnerToJSONTyped,
} from './PartnerProductUpsertRequestItemsInner';

/**
 * 
 * @export
 * @interface PartnerProductUpsertRequest
 */
export interface PartnerProductUpsertRequest {
    /**
     * 
     * @type {Array<PartnerProductUpsertRequestItemsInner>}
     * @memberof PartnerProductUpsertRequest
     */
    items: Array<PartnerProductUpsertRequestItemsInner>;
}

/**
 * Check if a given object implements the PartnerProductUpsertRequest interface.
 */
export function instanceOfPartnerProductUpsertRequest(value: object): value is PartnerProductUpsertRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PartnerProductUpsertRequestFromJSON(json: any): PartnerProductUpsertRequest {
    return PartnerProductUpsertRequestFromJSONTyped(json, false);
}

export function PartnerProductUpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerProductUpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PartnerProductUpsertRequestItemsInnerFromJSON)),
    };
}

export function PartnerProductUpsertRequestToJSON(json: any): PartnerProductUpsertRequest {
    return PartnerProductUpsertRequestToJSONTyped(json, false);
}

export function PartnerProductUpsertRequestToJSONTyped(value?: PartnerProductUpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PartnerProductUpsertRequestItemsInnerToJSON)),
    };
}

