/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SFTP destination metadata (secret material never returned)
 * @export
 * @interface PartnerSftpConfig
 */
export interface PartnerSftpConfig {
    /**
     * 
     * @type {boolean}
     * @memberof PartnerSftpConfig
     */
    configured?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PartnerSftpConfig
     */
    host?: string;
    /**
     * 
     * @type {number}
     * @memberof PartnerSftpConfig
     */
    port?: number;
    /**
     * 
     * @type {string}
     * @memberof PartnerSftpConfig
     */
    username?: string;
    /**
     * GSM secret name (not plaintext)
     * @type {string}
     * @memberof PartnerSftpConfig
     */
    secretRef?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerSftpConfig
     */
    remoteDir?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerSftpConfig
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PartnerSftpConfig
     */
    inboundDir?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerSftpConfig
     */
    outboundDir?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerSftpConfig
     */
    archiveDir?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerSftpConfig
     */
    ediEnabled?: boolean;
    /**
     * Base64 SHA-256 of SSH host key (pin); required when PARTNER_SFTP_STRICT_HOSTKEY=true
     * @type {string}
     * @memberof PartnerSftpConfig
     */
    hostKeySha256?: string;
}

/**
 * Check if a given object implements the PartnerSftpConfig interface.
 */
export function instanceOfPartnerSftpConfig(value: object): value is PartnerSftpConfig {
    return true;
}

export function PartnerSftpConfigFromJSON(json: any): PartnerSftpConfig {
    return PartnerSftpConfigFromJSONTyped(json, false);
}

export function PartnerSftpConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerSftpConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'] == null ? undefined : json['configured'],
        'host': json['host'] == null ? undefined : json['host'],
        'port': json['port'] == null ? undefined : json['port'],
        'username': json['username'] == null ? undefined : json['username'],
        'secretRef': json['secret_ref'] == null ? undefined : json['secret_ref'],
        'remoteDir': json['remote_dir'] == null ? undefined : json['remote_dir'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'inboundDir': json['inbound_dir'] == null ? undefined : json['inbound_dir'],
        'outboundDir': json['outbound_dir'] == null ? undefined : json['outbound_dir'],
        'archiveDir': json['archive_dir'] == null ? undefined : json['archive_dir'],
        'ediEnabled': json['edi_enabled'] == null ? undefined : json['edi_enabled'],
        'hostKeySha256': json['host_key_sha256'] == null ? undefined : json['host_key_sha256'],
    };
}

export function PartnerSftpConfigToJSON(json: any): PartnerSftpConfig {
    return PartnerSftpConfigToJSONTyped(json, false);
}

export function PartnerSftpConfigToJSONTyped(value?: PartnerSftpConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'host': value['host'],
        'port': value['port'],
        'username': value['username'],
        'secret_ref': value['secretRef'],
        'remote_dir': value['remoteDir'],
        'is_active': value['isActive'],
        'inbound_dir': value['inboundDir'],
        'outbound_dir': value['outboundDir'],
        'archive_dir': value['archiveDir'],
        'edi_enabled': value['ediEnabled'],
        'host_key_sha256': value['hostKeySha256'],
    };
}

