/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerCreateOrder401Response
 */
export interface PartnerCreateOrder401Response {
    /**
     * 
     * @type {string}
     * @memberof PartnerCreateOrder401Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerCreateOrder401Response
     */
    code?: string;
}

/**
 * Check if a given object implements the PartnerCreateOrder401Response interface.
 */
export function instanceOfPartnerCreateOrder401Response(value: object): value is PartnerCreateOrder401Response {
    return true;
}

export function PartnerCreateOrder401ResponseFromJSON(json: any): PartnerCreateOrder401Response {
    return PartnerCreateOrder401ResponseFromJSONTyped(json, false);
}

export function PartnerCreateOrder401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerCreateOrder401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function PartnerCreateOrder401ResponseToJSON(json: any): PartnerCreateOrder401Response {
    return PartnerCreateOrder401ResponseToJSONTyped(json, false);
}

export function PartnerCreateOrder401ResponseToJSONTyped(value?: PartnerCreateOrder401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'code': value['code'],
    };
}

