/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerCoaMap
 */
export interface PartnerCoaMap {
    /**
     * 
     * @type {string}
     * @memberof PartnerCoaMap
     */
    accountAr?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerCoaMap
     */
    accountRevenue?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerCoaMap
     */
    accountBankCash?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerCoaMap
     */
    usingDefaults?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PartnerCoaMap
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PartnerCoaMap
     */
    updatedBy?: string;
}

/**
 * Check if a given object implements the PartnerCoaMap interface.
 */
export function instanceOfPartnerCoaMap(value: object): value is PartnerCoaMap {
    return true;
}

export function PartnerCoaMapFromJSON(json: any): PartnerCoaMap {
    return PartnerCoaMapFromJSONTyped(json, false);
}

export function PartnerCoaMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerCoaMap {
    if (json == null) {
        return json;
    }
    return {
        
        'accountAr': json['account_ar'] == null ? undefined : json['account_ar'],
        'accountRevenue': json['account_revenue'] == null ? undefined : json['account_revenue'],
        'accountBankCash': json['account_bank_cash'] == null ? undefined : json['account_bank_cash'],
        'usingDefaults': json['using_defaults'] == null ? undefined : json['using_defaults'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
    };
}

export function PartnerCoaMapToJSON(json: any): PartnerCoaMap {
    return PartnerCoaMapToJSONTyped(json, false);
}

export function PartnerCoaMapToJSONTyped(value?: PartnerCoaMap | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_ar': value['accountAr'],
        'account_revenue': value['accountRevenue'],
        'account_bank_cash': value['accountBankCash'],
        'using_defaults': value['usingDefaults'],
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'updated_by': value['updatedBy'],
    };
}

