/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartnerCreateOrderRequestLineItemsInner } from './PartnerCreateOrderRequestLineItemsInner';
import {
    PartnerCreateOrderRequestLineItemsInnerFromJSON,
    PartnerCreateOrderRequestLineItemsInnerFromJSONTyped,
    PartnerCreateOrderRequestLineItemsInnerToJSON,
    PartnerCreateOrderRequestLineItemsInnerToJSONTyped,
} from './PartnerCreateOrderRequestLineItemsInner';

/**
 * 
 * @export
 * @interface PartnerCreateOrderRequest
 */
export interface PartnerCreateOrderRequest {
    /**
     * Required for RETAILER keys
     * @type {string}
     * @memberof PartnerCreateOrderRequest
     */
    supplierId?: string;
    /**
     * Required for SUPPLIER keys
     * @type {string}
     * @memberof PartnerCreateOrderRequest
     */
    retailerId?: string;
    /**
     * 
     * @type {Array<PartnerCreateOrderRequestLineItemsInner>}
     * @memberof PartnerCreateOrderRequest
     */
    lineItems: Array<PartnerCreateOrderRequestLineItemsInner>;
    /**
     * 
     * @type {string}
     * @memberof PartnerCreateOrderRequest
     */
    h3Cell?: string;
    /**
     * 
     * @type {number}
     * @memberof PartnerCreateOrderRequest
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof PartnerCreateOrderRequest
     */
    lng: number;
}

/**
 * Check if a given object implements the PartnerCreateOrderRequest interface.
 */
export function instanceOfPartnerCreateOrderRequest(value: object): value is PartnerCreateOrderRequest {
    if (!('lineItems' in value) || value['lineItems'] === undefined) return false;
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lng' in value) || value['lng'] === undefined) return false;
    return true;
}

export function PartnerCreateOrderRequestFromJSON(json: any): PartnerCreateOrderRequest {
    return PartnerCreateOrderRequestFromJSONTyped(json, false);
}

export function PartnerCreateOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerCreateOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'supplierId': json['supplier_id'] == null ? undefined : json['supplier_id'],
        'retailerId': json['retailer_id'] == null ? undefined : json['retailer_id'],
        'lineItems': ((json['line_items'] as Array<any>).map(PartnerCreateOrderRequestLineItemsInnerFromJSON)),
        'h3Cell': json['h3_cell'] == null ? undefined : json['h3_cell'],
        'lat': json['lat'],
        'lng': json['lng'],
    };
}

export function PartnerCreateOrderRequestToJSON(json: any): PartnerCreateOrderRequest {
    return PartnerCreateOrderRequestToJSONTyped(json, false);
}

export function PartnerCreateOrderRequestToJSONTyped(value?: PartnerCreateOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'supplier_id': value['supplierId'],
        'retailer_id': value['retailerId'],
        'line_items': ((value['lineItems'] as Array<any>).map(PartnerCreateOrderRequestLineItemsInnerToJSON)),
        'h3_cell': value['h3Cell'],
        'lat': value['lat'],
        'lng': value['lng'],
    };
}

