/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerCreateWebhookRequest
 */
export interface PartnerCreateWebhookRequest {
    /**
     * 
     * @type {string}
     * @memberof PartnerCreateWebhookRequest
     */
    url: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PartnerCreateWebhookRequest
     */
    eventTypes?: Array<string>;
}

/**
 * Check if a given object implements the PartnerCreateWebhookRequest interface.
 */
export function instanceOfPartnerCreateWebhookRequest(value: object): value is PartnerCreateWebhookRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function PartnerCreateWebhookRequestFromJSON(json: any): PartnerCreateWebhookRequest {
    return PartnerCreateWebhookRequestFromJSONTyped(json, false);
}

export function PartnerCreateWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerCreateWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'eventTypes': json['event_types'] == null ? undefined : json['event_types'],
    };
}

export function PartnerCreateWebhookRequestToJSON(json: any): PartnerCreateWebhookRequest {
    return PartnerCreateWebhookRequestToJSONTyped(json, false);
}

export function PartnerCreateWebhookRequestToJSONTyped(value?: PartnerCreateWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'event_types': value['eventTypes'],
    };
}

