/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartnerPriceUpsertRequestItemsInner
 */
export interface PartnerPriceUpsertRequestItemsInner {
    /**
     * 
     * @type {string}
     * @memberof PartnerPriceUpsertRequestItemsInner
     */
    externalId: string;
    /**
     * 
     * @type {number}
     * @memberof PartnerPriceUpsertRequestItemsInner
     */
    priceMinor: number;
    /**
     * 
     * @type {string}
     * @memberof PartnerPriceUpsertRequestItemsInner
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof PartnerPriceUpsertRequestItemsInner
     */
    retailerId?: string | null;
}

/**
 * Check if a given object implements the PartnerPriceUpsertRequestItemsInner interface.
 */
export function instanceOfPartnerPriceUpsertRequestItemsInner(value: object): value is PartnerPriceUpsertRequestItemsInner {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('priceMinor' in value) || value['priceMinor'] === undefined) return false;
    return true;
}

export function PartnerPriceUpsertRequestItemsInnerFromJSON(json: any): PartnerPriceUpsertRequestItemsInner {
    return PartnerPriceUpsertRequestItemsInnerFromJSONTyped(json, false);
}

export function PartnerPriceUpsertRequestItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerPriceUpsertRequestItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['external_id'],
        'priceMinor': json['price_minor'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'retailerId': json['retailer_id'] == null ? undefined : json['retailer_id'],
    };
}

export function PartnerPriceUpsertRequestItemsInnerToJSON(json: any): PartnerPriceUpsertRequestItemsInner {
    return PartnerPriceUpsertRequestItemsInnerToJSONTyped(json, false);
}

export function PartnerPriceUpsertRequestItemsInnerToJSONTyped(value?: PartnerPriceUpsertRequestItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_id': value['externalId'],
        'price_minor': value['priceMinor'],
        'currency': value['currency'],
        'retailer_id': value['retailerId'],
    };
}

