/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartnerEdiDocument } from './PartnerEdiDocument';
import {
    PartnerEdiDocumentFromJSON,
    PartnerEdiDocumentFromJSONTyped,
    PartnerEdiDocumentToJSON,
    PartnerEdiDocumentToJSONTyped,
} from './PartnerEdiDocument';

/**
 * 
 * @export
 * @interface PartnerListEdiDocuments200Response
 */
export interface PartnerListEdiDocuments200Response {
    /**
     * 
     * @type {Array<PartnerEdiDocument>}
     * @memberof PartnerListEdiDocuments200Response
     */
    documents?: Array<PartnerEdiDocument>;
}

/**
 * Check if a given object implements the PartnerListEdiDocuments200Response interface.
 */
export function instanceOfPartnerListEdiDocuments200Response(value: object): value is PartnerListEdiDocuments200Response {
    return true;
}

export function PartnerListEdiDocuments200ResponseFromJSON(json: any): PartnerListEdiDocuments200Response {
    return PartnerListEdiDocuments200ResponseFromJSONTyped(json, false);
}

export function PartnerListEdiDocuments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartnerListEdiDocuments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'documents': json['documents'] == null ? undefined : ((json['documents'] as Array<any>).map(PartnerEdiDocumentFromJSON)),
    };
}

export function PartnerListEdiDocuments200ResponseToJSON(json: any): PartnerListEdiDocuments200Response {
    return PartnerListEdiDocuments200ResponseToJSONTyped(json, false);
}

export function PartnerListEdiDocuments200ResponseToJSONTyped(value?: PartnerListEdiDocuments200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documents': value['documents'] == null ? undefined : ((value['documents'] as Array<any>).map(PartnerEdiDocumentToJSON)),
    };
}

