package com.pegasus.design.ui

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val PegasusMonochromeLightColorScheme = lightColorScheme(
    primary = PegasusNeutralColors.Black,
    onPrimary = PegasusNeutralColors.White,
    primaryContainer = PegasusNeutralColors.Neutral94,
    onPrimaryContainer = PegasusNeutralColors.Neutral10,
    secondary = PegasusNeutralColors.Neutral40,
    onSecondary = PegasusNeutralColors.White,
    secondaryContainer = PegasusNeutralColors.Neutral92,
    onSecondaryContainer = PegasusNeutralColors.Neutral10,
    tertiary = PegasusNeutralColors.Neutral30,
    onTertiary = PegasusNeutralColors.White,
    tertiaryContainer = PegasusNeutralColors.Neutral90,
    onTertiaryContainer = PegasusNeutralColors.Neutral10,
    error = PegasusNeutralColors.StatusRed,
    onError = PegasusNeutralColors.White,
    errorContainer = PegasusNeutralColors.StatusRedSoft,
    onErrorContainer = PegasusNeutralColors.StatusRed,
    background = PegasusNeutralColors.Neutral95,
    onBackground = PegasusNeutralColors.Neutral10,
    surface = PegasusNeutralColors.White,
    onSurface = PegasusNeutralColors.Neutral10,
    surfaceVariant = PegasusNeutralColors.Neutral94,
    onSurfaceVariant = PegasusNeutralColors.Neutral40,
    outline = PegasusNeutralColors.Neutral70,
    outlineVariant = PegasusNeutralColors.Neutral87,
    surfaceContainerLowest = PegasusNeutralColors.White,
    surfaceContainerLow = PegasusNeutralColors.Neutral98,
    surfaceContainer = PegasusNeutralColors.Neutral96,
    surfaceContainerHigh = PegasusNeutralColors.Neutral94,
    surfaceContainerHighest = PegasusNeutralColors.Neutral92,
)

val PegasusMonochromeDarkColorScheme = darkColorScheme(
    primary = PegasusNeutralColors.White,
    onPrimary = PegasusNeutralColors.Black,
    primaryContainer = PegasusNeutralColors.Neutral17,
    onPrimaryContainer = PegasusNeutralColors.Neutral90,
    secondary = PegasusNeutralColors.Neutral60,
    onSecondary = PegasusNeutralColors.Neutral10,
    secondaryContainer = PegasusNeutralColors.Neutral22,
    onSecondaryContainer = PegasusNeutralColors.Neutral90,
    tertiary = PegasusNeutralColors.Neutral50,
    onTertiary = PegasusNeutralColors.Neutral10,
    tertiaryContainer = PegasusNeutralColors.Neutral24,
    onTertiaryContainer = PegasusNeutralColors.Neutral90,
    error = PegasusNeutralColors.StatusRed,
    onError = PegasusNeutralColors.White,
    errorContainer = PegasusNeutralColors.StatusRedSoft,
    onErrorContainer = PegasusNeutralColors.StatusRed,
    background = PegasusNeutralColors.Neutral6,
    onBackground = PegasusNeutralColors.Neutral90,
    surface = PegasusNeutralColors.Neutral10,
    onSurface = PegasusNeutralColors.Neutral90,
    surfaceVariant = PegasusNeutralColors.Neutral17,
    onSurfaceVariant = PegasusNeutralColors.Neutral60,
    outline = PegasusNeutralColors.Neutral40,
    outlineVariant = PegasusNeutralColors.Neutral22,
    surfaceContainerLowest = PegasusNeutralColors.Neutral4,
    surfaceContainerLow = PegasusNeutralColors.Neutral10,
    surfaceContainer = PegasusNeutralColors.Neutral12,
    surfaceContainerHigh = PegasusNeutralColors.Neutral17,
    surfaceContainerHighest = PegasusNeutralColors.Neutral22,
)
