/* tslint:disable */
/* eslint-disable */
/**
 * PegasusX Partner API
 * Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IssuePartnerApiKeyRequest,
  PartnerAs2Config,
  PartnerAs2ConfigUpdate,
  PartnerCoaMap,
  PartnerCoaMapUpdate,
  PartnerCreateExportRequest,
  PartnerCreateOrder401Response,
  PartnerCreateOrderRequest,
  PartnerCreateOrderResponse,
  PartnerCreateWebhookRequest,
  PartnerEdiDocument,
  PartnerExportJob,
  PartnerListEdiDocuments200Response,
  PartnerListExports200Response,
  PartnerListWebhooks200Response,
  PartnerOAuthError,
  PartnerOAuthTokenRequest,
  PartnerOAuthTokenResponse,
  PartnerPOSDemandFeedRequest,
  PartnerPriceUpsertRequest,
  PartnerProductUpsertRequest,
  PartnerStockUpsertRequest,
} from '../models/index';
import {
    IssuePartnerApiKeyRequestFromJSON,
    IssuePartnerApiKeyRequestToJSON,
    PartnerAs2ConfigFromJSON,
    PartnerAs2ConfigToJSON,
    PartnerAs2ConfigUpdateFromJSON,
    PartnerAs2ConfigUpdateToJSON,
    PartnerCoaMapFromJSON,
    PartnerCoaMapToJSON,
    PartnerCoaMapUpdateFromJSON,
    PartnerCoaMapUpdateToJSON,
    PartnerCreateExportRequestFromJSON,
    PartnerCreateExportRequestToJSON,
    PartnerCreateOrder401ResponseFromJSON,
    PartnerCreateOrder401ResponseToJSON,
    PartnerCreateOrderRequestFromJSON,
    PartnerCreateOrderRequestToJSON,
    PartnerCreateOrderResponseFromJSON,
    PartnerCreateOrderResponseToJSON,
    PartnerCreateWebhookRequestFromJSON,
    PartnerCreateWebhookRequestToJSON,
    PartnerEdiDocumentFromJSON,
    PartnerEdiDocumentToJSON,
    PartnerExportJobFromJSON,
    PartnerExportJobToJSON,
    PartnerListEdiDocuments200ResponseFromJSON,
    PartnerListEdiDocuments200ResponseToJSON,
    PartnerListExports200ResponseFromJSON,
    PartnerListExports200ResponseToJSON,
    PartnerListWebhooks200ResponseFromJSON,
    PartnerListWebhooks200ResponseToJSON,
    PartnerOAuthErrorFromJSON,
    PartnerOAuthErrorToJSON,
    PartnerOAuthTokenRequestFromJSON,
    PartnerOAuthTokenRequestToJSON,
    PartnerOAuthTokenResponseFromJSON,
    PartnerOAuthTokenResponseToJSON,
    PartnerPOSDemandFeedRequestFromJSON,
    PartnerPOSDemandFeedRequestToJSON,
    PartnerPriceUpsertRequestFromJSON,
    PartnerPriceUpsertRequestToJSON,
    PartnerProductUpsertRequestFromJSON,
    PartnerProductUpsertRequestToJSON,
    PartnerStockUpsertRequestFromJSON,
    PartnerStockUpsertRequestToJSON,
} from '../models/index';

export interface IssuePartnerApiKeyOperationRequest {
    issuePartnerApiKeyRequest?: IssuePartnerApiKeyRequest;
}

export interface PartnerCreateExportOperationRequest {
    partnerCreateExportRequest: PartnerCreateExportRequest;
}

export interface PartnerCreateOrderOperationRequest {
    idempotencyKey: string;
    partnerCreateOrderRequest: PartnerCreateOrderRequest;
}

export interface PartnerCreateWebhookOperationRequest {
    partnerCreateWebhookRequest: PartnerCreateWebhookRequest;
}

export interface PartnerDeactivateWebhookRequest {
    subscriptionID: string;
}

export interface PartnerGetEdiDocumentRequest {
    documentID: string;
}

export interface PartnerGetExportRequest {
    jobID: string;
}

export interface PartnerGetOrderRequest {
    orderID: string;
}

export interface PartnerInventoryAvailabilityRequest {
    supplierId?: string;
    retailerId?: string;
    productIds?: string;
}

export interface PartnerListCatalogRequest {
    supplierId?: string;
    retailerId?: string;
    categoryId?: string;
}

export interface PartnerOAuthTokenOperationRequest {
    partnerOAuthTokenRequest: PartnerOAuthTokenRequest;
}

export interface PartnerPOSDemandFeedOperationRequest {
    idempotencyKey: string;
    partnerPOSDemandFeedRequest: PartnerPOSDemandFeedRequest;
}

export interface PartnerPingWebhookRequest {
    subscriptionID: string;
}

export interface PartnerPutAs2ConfigRequest {
    partnerAs2ConfigUpdate: PartnerAs2ConfigUpdate;
}

export interface PartnerPutCoaRequest {
    partnerCoaMapUpdate: PartnerCoaMapUpdate;
}

export interface PartnerReplayDeadLetterRequest {
    attemptID: string;
}

export interface PartnerReplayEdiDocumentRequest {
    documentID: string;
}

export interface PartnerRotateWebhookSecretRequest {
    subscriptionID: string;
}

export interface PartnerUpsertPricesRequest {
    idempotencyKey: string;
    partnerPriceUpsertRequest: PartnerPriceUpsertRequest;
}

export interface PartnerUpsertProductsRequest {
    idempotencyKey: string;
    partnerProductUpsertRequest: PartnerProductUpsertRequest;
}

export interface PartnerUpsertStockRequest {
    idempotencyKey: string;
    partnerStockUpsertRequest: PartnerStockUpsertRequest;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * 
     * @summary Issue partner API key (human JWT)
     * @param {IssuePartnerApiKeyRequest} [issuePartnerApiKeyRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    issuePartnerApiKeyRaw(requestParameters: IssuePartnerApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Issue partner API key (human JWT)
     */
    issuePartnerApiKey(requestParameters: IssuePartnerApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary List partner keys for caller tenant
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listPartnerApiKeysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * List partner keys for caller tenant
     */
    listPartnerApiKeys(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Unauthenticated RFC 4130 receive; identity via AS2-From/AS2-To + PKCS7. Sync MDN response.
     * @summary AS2 receive (EDI-lite ORDERS)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerAs2ReceiveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Unauthenticated RFC 4130 receive; identity via AS2-From/AS2-To + PKCS7. Sync MDN response.
     * AS2 receive (EDI-lite ORDERS)
     */
    partnerAs2Receive(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Create async bulk export job
     * @param {PartnerCreateExportRequest} partnerCreateExportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerCreateExportRaw(requestParameters: PartnerCreateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerExportJob>>;

    /**
     * Create async bulk export job
     */
    partnerCreateExport(requestParameters: PartnerCreateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerExportJob>;

    /**
     * 
     * @summary Create order
     * @param {string} idempotencyKey 
     * @param {PartnerCreateOrderRequest} partnerCreateOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerCreateOrderRaw(requestParameters: PartnerCreateOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerCreateOrderResponse>>;

    /**
     * Create order
     */
    partnerCreateOrder(requestParameters: PartnerCreateOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerCreateOrderResponse>;

    /**
     * 
     * @summary Create outbound webhook subscription
     * @param {PartnerCreateWebhookRequest} partnerCreateWebhookRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerCreateWebhookRaw(requestParameters: PartnerCreateWebhookOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Create outbound webhook subscription
     */
    partnerCreateWebhook(requestParameters: PartnerCreateWebhookOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Deactivate webhook subscription
     * @param {string} subscriptionID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerDeactivateWebhookRaw(requestParameters: PartnerDeactivateWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deactivate webhook subscription
     */
    partnerDeactivateWebhook(requestParameters: PartnerDeactivateWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get tenant AS2 station config
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerGetAs2ConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerAs2Config>>;

    /**
     * Get tenant AS2 station config
     */
    partnerGetAs2Config(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerAs2Config>;

    /**
     * 
     * @summary Get tenant chart of accounts for journals exports
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerGetCoaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerCoaMap>>;

    /**
     * Get tenant chart of accounts for journals exports
     */
    partnerGetCoa(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerCoaMap>;

    /**
     * 
     * @summary Get EDI document status
     * @param {string} documentID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerGetEdiDocumentRaw(requestParameters: PartnerGetEdiDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerEdiDocument>>;

    /**
     * Get EDI document status
     */
    partnerGetEdiDocument(requestParameters: PartnerGetEdiDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerEdiDocument>;

    /**
     * 
     * @summary Get export job status (+ signed download_url when SUCCEEDED)
     * @param {string} jobID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerGetExportRaw(requestParameters: PartnerGetExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerExportJob>>;

    /**
     * Get export job status (+ signed download_url when SUCCEEDED)
     */
    partnerGetExport(requestParameters: PartnerGetExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerExportJob>;

    /**
     * 
     * @summary Get order (tenant-scoped; IDOR fail-closed)
     * @param {string} orderID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerGetOrderRaw(requestParameters: PartnerGetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get order (tenant-scoped; IDOR fail-closed)
     */
    partnerGetOrder(requestParameters: PartnerGetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary On-hand minus reserved availability
     * @param {string} [supplierId] 
     * @param {string} [retailerId] 
     * @param {string} [productIds] Comma-separated product IDs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerInventoryAvailabilityRaw(requestParameters: PartnerInventoryAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * On-hand minus reserved availability
     */
    partnerInventoryAvailability(requestParameters: PartnerInventoryAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Catalog with resolved prices / stock enrichment
     * @param {string} [supplierId] 
     * @param {string} [retailerId] 
     * @param {string} [categoryId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerListCatalogRaw(requestParameters: PartnerListCatalogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Catalog with resolved prices / stock enrichment
     */
    partnerListCatalog(requestParameters: PartnerListCatalogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary List dead-letter delivery attempts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerListDeadLetterRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * List dead-letter delivery attempts
     */
    partnerListDeadLetter(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary List recent EDI-lite documents for the key tenant
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerListEdiDocumentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerListEdiDocuments200Response>>;

    /**
     * List recent EDI-lite documents for the key tenant
     */
    partnerListEdiDocuments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerListEdiDocuments200Response>;

    /**
     * 
     * @summary List recent export jobs for the key tenant
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerListExportsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerListExports200Response>>;

    /**
     * List recent export jobs for the key tenant
     */
    partnerListExports(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerListExports200Response>;

    /**
     * 
     * @summary List webhook subscriptions (secret omitted; secret_prefix only)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerListWebhooksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerListWebhooks200Response>>;

    /**
     * List webhook subscriptions (secret omitted; secret_prefix only)
     */
    partnerListWebhooks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerListWebhooks200Response>;

    /**
     * 
     * @summary OAuth2 client_credentials token
     * @param {PartnerOAuthTokenRequest} partnerOAuthTokenRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerOAuthTokenRaw(requestParameters: PartnerOAuthTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerOAuthTokenResponse>>;

    /**
     * OAuth2 client_credentials token
     */
    partnerOAuthToken(requestParameters: PartnerOAuthTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerOAuthTokenResponse>;

    /**
     * 
     * @summary Ingest POS sell-through demand signals (retail chain → planning)
     * @param {string} idempotencyKey 
     * @param {PartnerPOSDemandFeedRequest} partnerPOSDemandFeedRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerPOSDemandFeedRaw(requestParameters: PartnerPOSDemandFeedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Ingest POS sell-through demand signals (retail chain → planning)
     */
    partnerPOSDemandFeed(requestParameters: PartnerPOSDemandFeedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Send signed test delivery
     * @param {string} subscriptionID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerPingWebhookRaw(requestParameters: PartnerPingWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Send signed test delivery
     */
    partnerPingWebhook(requestParameters: PartnerPingWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Upsert tenant AS2 station config
     * @param {PartnerAs2ConfigUpdate} partnerAs2ConfigUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerPutAs2ConfigRaw(requestParameters: PartnerPutAs2ConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerAs2Config>>;

    /**
     * Upsert tenant AS2 station config
     */
    partnerPutAs2Config(requestParameters: PartnerPutAs2ConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerAs2Config>;

    /**
     * 
     * @summary Upsert tenant chart of accounts for journals exports
     * @param {PartnerCoaMapUpdate} partnerCoaMapUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerPutCoaRaw(requestParameters: PartnerPutCoaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerCoaMap>>;

    /**
     * Upsert tenant chart of accounts for journals exports
     */
    partnerPutCoa(requestParameters: PartnerPutCoaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerCoaMap>;

    /**
     * 
     * @summary Requeue a DEAD delivery attempt (full retry budget)
     * @param {string} attemptID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerReplayDeadLetterRaw(requestParameters: PartnerReplayDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Requeue a DEAD delivery attempt (full retry budget)
     */
    partnerReplayDeadLetter(requestParameters: PartnerReplayDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Requeue FAILED/EMITTED EDI document
     * @param {string} documentID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerReplayEdiDocumentRaw(requestParameters: PartnerReplayEdiDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Requeue FAILED/EMITTED EDI document
     */
    partnerReplayEdiDocument(requestParameters: PartnerReplayEdiDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Rotate HMAC signing secret (returned once)
     * @param {string} subscriptionID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerRotateWebhookSecretRaw(requestParameters: PartnerRotateWebhookSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Rotate HMAC signing secret (returned once)
     */
    partnerRotateWebhookSecret(requestParameters: PartnerRotateWebhookSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Batch upsert list prices by external_id
     * @param {string} idempotencyKey 
     * @param {PartnerPriceUpsertRequest} partnerPriceUpsertRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerUpsertPricesRaw(requestParameters: PartnerUpsertPricesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Batch upsert list prices by external_id
     */
    partnerUpsertPrices(requestParameters: PartnerUpsertPricesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Batch upsert products by external_id (ProductId == external_id)
     * @param {string} idempotencyKey 
     * @param {PartnerProductUpsertRequest} partnerProductUpsertRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerUpsertProductsRaw(requestParameters: PartnerUpsertProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Batch upsert products by external_id (ProductId == external_id)
     */
    partnerUpsertProducts(requestParameters: PartnerUpsertProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Batch set absolute on-hand stock by external_id × warehouse
     * @param {string} idempotencyKey 
     * @param {PartnerStockUpsertRequest} partnerStockUpsertRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    partnerUpsertStockRaw(requestParameters: PartnerUpsertStockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Batch set absolute on-hand stock by external_id × warehouse
     */
    partnerUpsertStock(requestParameters: PartnerUpsertStockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * Issue partner API key (human JWT)
     */
    async issuePartnerApiKeyRaw(requestParameters: IssuePartnerApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/admin/partner-keys`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IssuePartnerApiKeyRequestToJSON(requestParameters['issuePartnerApiKeyRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Issue partner API key (human JWT)
     */
    async issuePartnerApiKey(requestParameters: IssuePartnerApiKeyOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.issuePartnerApiKeyRaw(requestParameters, initOverrides);
    }

    /**
     * List partner keys for caller tenant
     */
    async listPartnerApiKeysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/admin/partner-keys`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List partner keys for caller tenant
     */
    async listPartnerApiKeys(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listPartnerApiKeysRaw(initOverrides);
    }

    /**
     * Unauthenticated RFC 4130 receive; identity via AS2-From/AS2-To + PKCS7. Sync MDN response.
     * AS2 receive (EDI-lite ORDERS)
     */
    async partnerAs2ReceiveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/partner/v1/as2`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Unauthenticated RFC 4130 receive; identity via AS2-From/AS2-To + PKCS7. Sync MDN response.
     * AS2 receive (EDI-lite ORDERS)
     */
    async partnerAs2Receive(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerAs2ReceiveRaw(initOverrides);
    }

    /**
     * Create async bulk export job
     */
    async partnerCreateExportRaw(requestParameters: PartnerCreateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerExportJob>> {
        if (requestParameters['partnerCreateExportRequest'] == null) {
            throw new runtime.RequiredError(
                'partnerCreateExportRequest',
                'Required parameter "partnerCreateExportRequest" was null or undefined when calling partnerCreateExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/exports`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerCreateExportRequestToJSON(requestParameters['partnerCreateExportRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerExportJobFromJSON(jsonValue));
    }

    /**
     * Create async bulk export job
     */
    async partnerCreateExport(requestParameters: PartnerCreateExportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerExportJob> {
        const response = await this.partnerCreateExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create order
     */
    async partnerCreateOrderRaw(requestParameters: PartnerCreateOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerCreateOrderResponse>> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling partnerCreateOrder().'
            );
        }

        if (requestParameters['partnerCreateOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'partnerCreateOrderRequest',
                'Required parameter "partnerCreateOrderRequest" was null or undefined when calling partnerCreateOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["orders:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/orders`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerCreateOrderRequestToJSON(requestParameters['partnerCreateOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerCreateOrderResponseFromJSON(jsonValue));
    }

    /**
     * Create order
     */
    async partnerCreateOrder(requestParameters: PartnerCreateOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerCreateOrderResponse> {
        const response = await this.partnerCreateOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create outbound webhook subscription
     */
    async partnerCreateWebhookRaw(requestParameters: PartnerCreateWebhookOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['partnerCreateWebhookRequest'] == null) {
            throw new runtime.RequiredError(
                'partnerCreateWebhookRequest',
                'Required parameter "partnerCreateWebhookRequest" was null or undefined when calling partnerCreateWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["webhooks:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/webhooks`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerCreateWebhookRequestToJSON(requestParameters['partnerCreateWebhookRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create outbound webhook subscription
     */
    async partnerCreateWebhook(requestParameters: PartnerCreateWebhookOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerCreateWebhookRaw(requestParameters, initOverrides);
    }

    /**
     * Deactivate webhook subscription
     */
    async partnerDeactivateWebhookRaw(requestParameters: PartnerDeactivateWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['subscriptionID'] == null) {
            throw new runtime.RequiredError(
                'subscriptionID',
                'Required parameter "subscriptionID" was null or undefined when calling partnerDeactivateWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["webhooks:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/webhooks/{subscriptionID}`.replace(`{${"subscriptionID"}}`, encodeURIComponent(String(requestParameters['subscriptionID']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deactivate webhook subscription
     */
    async partnerDeactivateWebhook(requestParameters: PartnerDeactivateWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerDeactivateWebhookRaw(requestParameters, initOverrides);
    }

    /**
     * Get tenant AS2 station config
     */
    async partnerGetAs2ConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerAs2Config>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/as2/config`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerAs2ConfigFromJSON(jsonValue));
    }

    /**
     * Get tenant AS2 station config
     */
    async partnerGetAs2Config(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerAs2Config> {
        const response = await this.partnerGetAs2ConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get tenant chart of accounts for journals exports
     */
    async partnerGetCoaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerCoaMap>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/coa`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerCoaMapFromJSON(jsonValue));
    }

    /**
     * Get tenant chart of accounts for journals exports
     */
    async partnerGetCoa(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerCoaMap> {
        const response = await this.partnerGetCoaRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get EDI document status
     */
    async partnerGetEdiDocumentRaw(requestParameters: PartnerGetEdiDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerEdiDocument>> {
        if (requestParameters['documentID'] == null) {
            throw new runtime.RequiredError(
                'documentID',
                'Required parameter "documentID" was null or undefined when calling partnerGetEdiDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/edi/documents/{documentID}`.replace(`{${"documentID"}}`, encodeURIComponent(String(requestParameters['documentID']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerEdiDocumentFromJSON(jsonValue));
    }

    /**
     * Get EDI document status
     */
    async partnerGetEdiDocument(requestParameters: PartnerGetEdiDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerEdiDocument> {
        const response = await this.partnerGetEdiDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get export job status (+ signed download_url when SUCCEEDED)
     */
    async partnerGetExportRaw(requestParameters: PartnerGetExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerExportJob>> {
        if (requestParameters['jobID'] == null) {
            throw new runtime.RequiredError(
                'jobID',
                'Required parameter "jobID" was null or undefined when calling partnerGetExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/exports/{jobID}`.replace(`{${"jobID"}}`, encodeURIComponent(String(requestParameters['jobID']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerExportJobFromJSON(jsonValue));
    }

    /**
     * Get export job status (+ signed download_url when SUCCEEDED)
     */
    async partnerGetExport(requestParameters: PartnerGetExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerExportJob> {
        const response = await this.partnerGetExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get order (tenant-scoped; IDOR fail-closed)
     */
    async partnerGetOrderRaw(requestParameters: PartnerGetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['orderID'] == null) {
            throw new runtime.RequiredError(
                'orderID',
                'Required parameter "orderID" was null or undefined when calling partnerGetOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["orders:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/orders/{orderID}`.replace(`{${"orderID"}}`, encodeURIComponent(String(requestParameters['orderID']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get order (tenant-scoped; IDOR fail-closed)
     */
    async partnerGetOrder(requestParameters: PartnerGetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerGetOrderRaw(requestParameters, initOverrides);
    }

    /**
     * On-hand minus reserved availability
     */
    async partnerInventoryAvailabilityRaw(requestParameters: PartnerInventoryAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['supplierId'] != null) {
            queryParameters['supplier_id'] = requestParameters['supplierId'];
        }

        if (requestParameters['retailerId'] != null) {
            queryParameters['retailer_id'] = requestParameters['retailerId'];
        }

        if (requestParameters['productIds'] != null) {
            queryParameters['product_ids'] = requestParameters['productIds'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["inventory:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/inventory/availability`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * On-hand minus reserved availability
     */
    async partnerInventoryAvailability(requestParameters: PartnerInventoryAvailabilityRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerInventoryAvailabilityRaw(requestParameters, initOverrides);
    }

    /**
     * Catalog with resolved prices / stock enrichment
     */
    async partnerListCatalogRaw(requestParameters: PartnerListCatalogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['supplierId'] != null) {
            queryParameters['supplier_id'] = requestParameters['supplierId'];
        }

        if (requestParameters['retailerId'] != null) {
            queryParameters['retailer_id'] = requestParameters['retailerId'];
        }

        if (requestParameters['categoryId'] != null) {
            queryParameters['category_id'] = requestParameters['categoryId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["catalog:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/catalog`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Catalog with resolved prices / stock enrichment
     */
    async partnerListCatalog(requestParameters: PartnerListCatalogRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerListCatalogRaw(requestParameters, initOverrides);
    }

    /**
     * List dead-letter delivery attempts
     */
    async partnerListDeadLetterRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["webhooks:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/webhooks/dead-letter`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List dead-letter delivery attempts
     */
    async partnerListDeadLetter(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerListDeadLetterRaw(initOverrides);
    }

    /**
     * List recent EDI-lite documents for the key tenant
     */
    async partnerListEdiDocumentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerListEdiDocuments200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/edi/documents`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerListEdiDocuments200ResponseFromJSON(jsonValue));
    }

    /**
     * List recent EDI-lite documents for the key tenant
     */
    async partnerListEdiDocuments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerListEdiDocuments200Response> {
        const response = await this.partnerListEdiDocumentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * List recent export jobs for the key tenant
     */
    async partnerListExportsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerListExports200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/exports`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerListExports200ResponseFromJSON(jsonValue));
    }

    /**
     * List recent export jobs for the key tenant
     */
    async partnerListExports(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerListExports200Response> {
        const response = await this.partnerListExportsRaw(initOverrides);
        return await response.value();
    }

    /**
     * List webhook subscriptions (secret omitted; secret_prefix only)
     */
    async partnerListWebhooksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerListWebhooks200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["webhooks:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/webhooks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerListWebhooks200ResponseFromJSON(jsonValue));
    }

    /**
     * List webhook subscriptions (secret omitted; secret_prefix only)
     */
    async partnerListWebhooks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerListWebhooks200Response> {
        const response = await this.partnerListWebhooksRaw(initOverrides);
        return await response.value();
    }

    /**
     * OAuth2 client_credentials token
     */
    async partnerOAuthTokenRaw(requestParameters: PartnerOAuthTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerOAuthTokenResponse>> {
        if (requestParameters['partnerOAuthTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'partnerOAuthTokenRequest',
                'Required parameter "partnerOAuthTokenRequest" was null or undefined when calling partnerOAuthToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/partner/v1/oauth/token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerOAuthTokenRequestToJSON(requestParameters['partnerOAuthTokenRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerOAuthTokenResponseFromJSON(jsonValue));
    }

    /**
     * OAuth2 client_credentials token
     */
    async partnerOAuthToken(requestParameters: PartnerOAuthTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerOAuthTokenResponse> {
        const response = await this.partnerOAuthTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ingest POS sell-through demand signals (retail chain → planning)
     */
    async partnerPOSDemandFeedRaw(requestParameters: PartnerPOSDemandFeedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling partnerPOSDemandFeed().'
            );
        }

        if (requestParameters['partnerPOSDemandFeedRequest'] == null) {
            throw new runtime.RequiredError(
                'partnerPOSDemandFeedRequest',
                'Required parameter "partnerPOSDemandFeedRequest" was null or undefined when calling partnerPOSDemandFeed().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["demand:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/demand/pos-feed`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerPOSDemandFeedRequestToJSON(requestParameters['partnerPOSDemandFeedRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Ingest POS sell-through demand signals (retail chain → planning)
     */
    async partnerPOSDemandFeed(requestParameters: PartnerPOSDemandFeedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerPOSDemandFeedRaw(requestParameters, initOverrides);
    }

    /**
     * Send signed test delivery
     */
    async partnerPingWebhookRaw(requestParameters: PartnerPingWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['subscriptionID'] == null) {
            throw new runtime.RequiredError(
                'subscriptionID',
                'Required parameter "subscriptionID" was null or undefined when calling partnerPingWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["webhooks:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/webhooks/{subscriptionID}/ping`.replace(`{${"subscriptionID"}}`, encodeURIComponent(String(requestParameters['subscriptionID']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send signed test delivery
     */
    async partnerPingWebhook(requestParameters: PartnerPingWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerPingWebhookRaw(requestParameters, initOverrides);
    }

    /**
     * Upsert tenant AS2 station config
     */
    async partnerPutAs2ConfigRaw(requestParameters: PartnerPutAs2ConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerAs2Config>> {
        if (requestParameters['partnerAs2ConfigUpdate'] == null) {
            throw new runtime.RequiredError(
                'partnerAs2ConfigUpdate',
                'Required parameter "partnerAs2ConfigUpdate" was null or undefined when calling partnerPutAs2Config().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/as2/config`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerAs2ConfigUpdateToJSON(requestParameters['partnerAs2ConfigUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerAs2ConfigFromJSON(jsonValue));
    }

    /**
     * Upsert tenant AS2 station config
     */
    async partnerPutAs2Config(requestParameters: PartnerPutAs2ConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerAs2Config> {
        const response = await this.partnerPutAs2ConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upsert tenant chart of accounts for journals exports
     */
    async partnerPutCoaRaw(requestParameters: PartnerPutCoaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PartnerCoaMap>> {
        if (requestParameters['partnerCoaMapUpdate'] == null) {
            throw new runtime.RequiredError(
                'partnerCoaMapUpdate',
                'Required parameter "partnerCoaMapUpdate" was null or undefined when calling partnerPutCoa().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/coa`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerCoaMapUpdateToJSON(requestParameters['partnerCoaMapUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartnerCoaMapFromJSON(jsonValue));
    }

    /**
     * Upsert tenant chart of accounts for journals exports
     */
    async partnerPutCoa(requestParameters: PartnerPutCoaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PartnerCoaMap> {
        const response = await this.partnerPutCoaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Requeue a DEAD delivery attempt (full retry budget)
     */
    async partnerReplayDeadLetterRaw(requestParameters: PartnerReplayDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['attemptID'] == null) {
            throw new runtime.RequiredError(
                'attemptID',
                'Required parameter "attemptID" was null or undefined when calling partnerReplayDeadLetter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["webhooks:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/webhooks/dead-letter/{attemptID}/replay`.replace(`{${"attemptID"}}`, encodeURIComponent(String(requestParameters['attemptID']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requeue a DEAD delivery attempt (full retry budget)
     */
    async partnerReplayDeadLetter(requestParameters: PartnerReplayDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerReplayDeadLetterRaw(requestParameters, initOverrides);
    }

    /**
     * Requeue FAILED/EMITTED EDI document
     */
    async partnerReplayEdiDocumentRaw(requestParameters: PartnerReplayEdiDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['documentID'] == null) {
            throw new runtime.RequiredError(
                'documentID',
                'Required parameter "documentID" was null or undefined when calling partnerReplayEdiDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["exports:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/edi/documents/{documentID}/replay`.replace(`{${"documentID"}}`, encodeURIComponent(String(requestParameters['documentID']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requeue FAILED/EMITTED EDI document
     */
    async partnerReplayEdiDocument(requestParameters: PartnerReplayEdiDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerReplayEdiDocumentRaw(requestParameters, initOverrides);
    }

    /**
     * Rotate HMAC signing secret (returned once)
     */
    async partnerRotateWebhookSecretRaw(requestParameters: PartnerRotateWebhookSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['subscriptionID'] == null) {
            throw new runtime.RequiredError(
                'subscriptionID',
                'Required parameter "subscriptionID" was null or undefined when calling partnerRotateWebhookSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["webhooks:manage"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/webhooks/{subscriptionID}/rotate-secret`.replace(`{${"subscriptionID"}}`, encodeURIComponent(String(requestParameters['subscriptionID']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Rotate HMAC signing secret (returned once)
     */
    async partnerRotateWebhookSecret(requestParameters: PartnerRotateWebhookSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerRotateWebhookSecretRaw(requestParameters, initOverrides);
    }

    /**
     * Batch upsert list prices by external_id
     */
    async partnerUpsertPricesRaw(requestParameters: PartnerUpsertPricesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling partnerUpsertPrices().'
            );
        }

        if (requestParameters['partnerPriceUpsertRequest'] == null) {
            throw new runtime.RequiredError(
                'partnerPriceUpsertRequest',
                'Required parameter "partnerPriceUpsertRequest" was null or undefined when calling partnerUpsertPrices().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/catalog/prices`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerPriceUpsertRequestToJSON(requestParameters['partnerPriceUpsertRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Batch upsert list prices by external_id
     */
    async partnerUpsertPrices(requestParameters: PartnerUpsertPricesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerUpsertPricesRaw(requestParameters, initOverrides);
    }

    /**
     * Batch upsert products by external_id (ProductId == external_id)
     */
    async partnerUpsertProductsRaw(requestParameters: PartnerUpsertProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling partnerUpsertProducts().'
            );
        }

        if (requestParameters['partnerProductUpsertRequest'] == null) {
            throw new runtime.RequiredError(
                'partnerProductUpsertRequest',
                'Required parameter "partnerProductUpsertRequest" was null or undefined when calling partnerUpsertProducts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["catalog:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/catalog/products`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerProductUpsertRequestToJSON(requestParameters['partnerProductUpsertRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Batch upsert products by external_id (ProductId == external_id)
     */
    async partnerUpsertProducts(requestParameters: PartnerUpsertProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerUpsertProductsRaw(requestParameters, initOverrides);
    }

    /**
     * Batch set absolute on-hand stock by external_id × warehouse
     */
    async partnerUpsertStockRaw(requestParameters: PartnerUpsertStockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling partnerUpsertStock().'
            );
        }

        if (requestParameters['partnerStockUpsertRequest'] == null) {
            throw new runtime.RequiredError(
                'partnerStockUpsertRequest',
                'Required parameter "partnerStockUpsertRequest" was null or undefined when calling partnerUpsertStock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PartnerApiKey", ["inventory:write"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/partner/v1/inventory/stock`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PartnerStockUpsertRequestToJSON(requestParameters['partnerStockUpsertRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Batch set absolute on-hand stock by external_id × warehouse
     */
    async partnerUpsertStock(requestParameters: PartnerUpsertStockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.partnerUpsertStockRaw(requestParameters, initOverrides);
    }

}
