apiVersion: v1
kind: Service
metadata:
  name: backend-go-worker
  labels:
    app: backend-go-worker
    app.kubernetes.io/part-of: pegasusx
spec:
  type: ClusterIP
  selector:
    app: backend-go-worker
  ports:
    - name: health
      port: 8081
      targetPort: health
      protocol: TCP
