// Indexes for fast lookup
CREATE INDEX ON :ArchitectureNode(id);
CREATE INDEX ON :ArchitectureNode(kind);
CREATE INDEX ON :ArchitectureNode(path);
MERGE (n:ArchitectureNode {id: 'execution-plan'}) SET n.kind = 'context', n.language = 'md', n.path = 'context/plan.md';
MERGE (n:ArchitectureNode {id: 'ssmr-infra-workflow'}) SET n.kind = 'ci', n.language = 'yaml', n.path = '../.github/workflows/ssmr-infra.yml';
MERGE (n:ArchitectureNode {id: 'docker-compose-ssmr'}) SET n.kind = 'infra', n.language = 'yaml', n.path = 'infra/docker-compose.ssmr.yml';
MERGE (n:ArchitectureNode {id: 'ssmr-smoke-harness'}) SET n.kind = 'tooling', n.language = 'bash', n.path = 'scripts/smoke_ssmr.sh';
MERGE (n:ArchitectureNode {id: 'backend-go'}) SET n.kind = 'service', n.language = 'go', n.path = 'apps/backend-go';
MERGE (n:ArchitectureNode {id: 'order-spanner-repo'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/order/repository_spanner.go';
MERGE (n:ArchitectureNode {id: 'order-delivery-proof-store'}) SET n.kind = 'data', n.language = 'ddl', n.path = 'apps/backend-go/schema/spanner.ddl';
MERGE (n:ArchitectureNode {id: 'payment-service'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/payment/service.go';
MERGE (n:ArchitectureNode {id: 'bootstrap-runtime'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/bootstrap/bootstrap.go';
MERGE (n:ArchitectureNode {id: 'kafka-consumer'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/kafka/consumer.go';
MERGE (n:ArchitectureNode {id: 'kafka-dlq-writer'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/kafka/dlq_writer.go';
MERGE (n:ArchitectureNode {id: 'payment-routes'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/paymentroutes/routes.go';
MERGE (n:ArchitectureNode {id: 'payment-spanner-repo'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/payment/repository_spanner.go';
MERGE (n:ArchitectureNode {id: 'supplier-spanner-repo'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/supplier/repository_spanner.go';
MERGE (n:ArchitectureNode {id: 'retailer-spanner-repo'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/retailer/repository_spanner.go';
MERGE (n:ArchitectureNode {id: 'retailer-core-handlers'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/retailer/core_handlers.go';
MERGE (n:ArchitectureNode {id: 'order-service'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/order/service.go';
MERGE (n:ArchitectureNode {id: 'order-routes'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/orderroutes/routes.go';
MERGE (n:ArchitectureNode {id: 'telemetry-routes'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/telemetryroutes/routes.go';
MERGE (n:ArchitectureNode {id: 'telemetry-location-store'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/telemetry/location_store.go';
MERGE (n:ArchitectureNode {id: 'ws-handler'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/ws/handler.go';
MERGE (n:ArchitectureNode {id: 'ws-connection'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/ws/connection.go';
MERGE (n:ArchitectureNode {id: 'factory-service'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/factory/service.go';
MERGE (n:ArchitectureNode {id: 'payload-service'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/payload/service.go';
MERGE (n:ArchitectureNode {id: 'warehouse-service'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/warehouse/service.go';
MERGE (n:ArchitectureNode {id: 'order-warehouse-resolver-spanner'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/order/warehouse_resolver_spanner.go';
MERGE (n:ArchitectureNode {id: 'supplier-pricing-handlers'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/supplier/portal_handlers.go';
MERGE (n:ArchitectureNode {id: 'backend-setup'}) SET n.kind = 'tooling', n.language = 'go', n.path = 'apps/backend-go/cmd/setup';
MERGE (n:ArchitectureNode {id: 'ssmr-smokecheck'}) SET n.kind = 'tooling', n.language = 'go', n.path = 'apps/backend-go/cmd/ssmr-smokecheck';
MERGE (n:ArchitectureNode {id: 'retailer-proximity'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/retailer/proximity_service.go';
MERGE (n:ArchitectureNode {id: 'ai-worker'}) SET n.kind = 'service', n.language = 'go', n.path = 'apps/ai-worker';
MERGE (n:ArchitectureNode {id: 'ai-worker-monitoring'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/ai-worker/main.go';
MERGE (n:ArchitectureNode {id: 'ai-worker-k8s-configmap'}) SET n.kind = 'infra', n.language = 'yaml', n.path = 'infra/k8s/ai-worker/configmap.yaml';
MERGE (n:ArchitectureNode {id: 'ai-worker-k8s-deployment'}) SET n.kind = 'infra', n.language = 'yaml', n.path = 'infra/k8s/ai-worker/deployment.yaml';
MERGE (n:ArchitectureNode {id: 'ai-worker-k8s-service'}) SET n.kind = 'infra', n.language = 'yaml', n.path = 'infra/k8s/ai-worker/service.yaml';
MERGE (n:ArchitectureNode {id: 'ai-worker-k8s-gate'}) SET n.kind = 'tooling', n.language = 'bash', n.path = 'scripts/validate_ai_worker_k8s.sh';
MERGE (n:ArchitectureNode {id: 'terraform-observability'}) SET n.kind = 'infra', n.language = 'hcl', n.path = 'infra/terraform/observability.tf';
MERGE (n:ArchitectureNode {id: 'supplier-portal'}) SET n.kind = 'web', n.language = 'ts', n.path = 'apps/supplier-portal';
MERGE (n:ArchitectureNode {id: 'supplier-portal-api-proxy'}) SET n.kind = 'component', n.language = 'ts', n.path = 'apps/supplier-portal/app/api/[...path]/route.ts';
MERGE (n:ArchitectureNode {id: 'supplier-onboarding-handlers'}) SET n.kind = 'component', n.language = 'go', n.path = 'apps/backend-go/supplier/onboarding_handlers.go';
MERGE (n:ArchitectureNode {id: 'supplier-orders-page'}) SET n.kind = 'component', n.language = 'ts', n.path = 'apps/supplier-portal/app/orders/page.tsx';
MERGE (n:ArchitectureNode {id: 'supplier-org-fleet-page'}) SET n.kind = 'component', n.language = 'ts', n.path = 'apps/supplier-portal/app/org-fleet/page.tsx';
MERGE (n:ArchitectureNode {id: 'supplier-payments-page'}) SET n.kind = 'component', n.language = 'ts', n.path = 'apps/supplier-portal/app/payments/page.tsx';
MERGE (n:ArchitectureNode {id: 'retailer-app-android'}) SET n.kind = 'mobile', n.language = 'kotlin', n.path = 'apps/retailer-app-android';
MERGE (n:ArchitectureNode {id: 'retailer-android-build-files'}) SET n.kind = 'component', n.language = 'kotlin', n.path = 'apps/retailer-app-android/app/build.gradle.kts';
MERGE (n:ArchitectureNode {id: 'retailer-android-api-client'}) SET n.kind = 'component', n.language = 'kotlin', n.path = 'apps/retailer-app-android/app/src/main/kotlin/com/pegasusx/retailerappandroid/network/RetailerTrackingApiClient.kt';
MERGE (n:ArchitectureNode {id: 'retailer-android-tracking-screen'}) SET n.kind = 'component', n.language = 'kotlin', n.path = 'apps/retailer-app-android/app/src/main/kotlin/com/pegasusx/retailerappandroid/ui/TrackingDashboardScreen.kt';
MERGE (n:ArchitectureNode {id: 'retailer-app-ios'}) SET n.kind = 'mobile', n.language = 'swift', n.path = 'apps/retailer-app-ios';
MERGE (n:ArchitectureNode {id: 'retailer-ios-project-spec'}) SET n.kind = 'component', n.language = 'yaml', n.path = 'apps/retailer-app-ios/project.yml';
MERGE (n:ArchitectureNode {id: 'retailer-ios-api-client'}) SET n.kind = 'component', n.language = 'swift', n.path = 'apps/retailer-app-ios/Sources/Networking/RetailerAPIClient.swift';
MERGE (n:ArchitectureNode {id: 'retailer-ios-tracking-view'}) SET n.kind = 'component', n.language = 'swift', n.path = 'apps/retailer-app-ios/Sources/Views/TrackingDashboardView.swift';
MERGE (n:ArchitectureNode {id: 'retailer-app-desktop'}) SET n.kind = 'desktop', n.language = 'ts', n.path = 'apps/retailer-app-desktop';
MERGE (n:ArchitectureNode {id: 'retailer-desktop-api-proxy'}) SET n.kind = 'component', n.language = 'ts', n.path = 'apps/retailer-app-desktop/app/api/[...path]/route.ts';
MERGE (n:ArchitectureNode {id: 'retailer-desktop-tracking-page'}) SET n.kind = 'component', n.language = 'ts', n.path = 'apps/retailer-app-desktop/app/page.tsx';
MERGE (n:ArchitectureNode {id: 'driver-app-android'}) SET n.kind = 'mobile', n.language = 'kotlin', n.path = 'apps/driver-app-android';
MERGE (n:ArchitectureNode {id: 'driver-android-build-files'}) SET n.kind = 'component', n.language = 'kotlin', n.path = 'apps/driver-app-android/app/build.gradle.kts';
MERGE (n:ArchitectureNode {id: 'driver-android-api-client'}) SET n.kind = 'component', n.language = 'kotlin', n.path = 'apps/driver-app-android/app/src/main/kotlin/com/pegasusx/driver/network/DriverApiClient.kt';
MERGE (n:ArchitectureNode {id: 'driver-android-live-ops-screen'}) SET n.kind = 'component', n.language = 'kotlin', n.path = 'apps/driver-app-android/app/src/main/kotlin/com/pegasusx/driver/ui/DriverLiveOpsScreen.kt';
MERGE (n:ArchitectureNode {id: 'driverappios'}) SET n.kind = 'mobile', n.language = 'swift', n.path = 'apps/driver-app-ios/driverappios';
MERGE (n:ArchitectureNode {id: 'warehouse-portal'}) SET n.kind = 'web', n.language = 'ts', n.path = 'apps/warehouse-portal';
MERGE (n:ArchitectureNode {id: 'warehouse-desktop-dashboard-page'}) SET n.kind = 'component', n.language = 'ts', n.path = 'apps/warehouse-portal/app/page.tsx';
MERGE (n:ArchitectureNode {id: 'warehouse-desktop-tauri-config'}) SET n.kind = 'component', n.language = 'json', n.path = 'apps/warehouse-portal/src-tauri/tauri.conf.json';
MERGE (n:ArchitectureNode {id: 'warehouse-app-android'}) SET n.kind = 'mobile', n.language = 'kotlin', n.path = 'apps/warehouse-app-android';
MERGE (n:ArchitectureNode {id: 'warehouse-android-build-files'}) SET n.kind = 'component', n.language = 'kotlin', n.path = 'apps/warehouse-app-android/app/build.gradle.kts';
MERGE (n:ArchitectureNode {id: 'warehouse-android-api-client'}) SET n.kind = 'component', n.language = 'kotlin', n.path = 'apps/warehouse-app-android/app/src/main/kotlin/com/pegasusx/warehouseappandroid/network/WarehouseApiClient.kt';
MERGE (n:ArchitectureNode {id: 'warehouse-android-dashboard-screen'}) SET n.kind = 'component', n.language = 'kotlin', n.path = 'apps/warehouse-app-android/app/src/main/kotlin/com/pegasusx/warehouseappandroid/ui/WarehouseDashboardScreen.kt';
MERGE (n:ArchitectureNode {id: 'warehouse-app-ios'}) SET n.kind = 'mobile', n.language = 'swift', n.path = 'apps/warehouse-app-ios';
MERGE (n:ArchitectureNode {id: 'warehouse-ios-project-spec'}) SET n.kind = 'component', n.language = 'yaml', n.path = 'apps/warehouse-app-ios/project.yml';
MERGE (n:ArchitectureNode {id: 'warehouse-ios-api-client'}) SET n.kind = 'component', n.language = 'swift', n.path = 'apps/warehouse-app-ios/Sources/Networking/WarehouseAPIClient.swift';
MERGE (n:ArchitectureNode {id: 'warehouse-ios-dashboard-view'}) SET n.kind = 'component', n.language = 'swift', n.path = 'apps/warehouse-app-ios/Sources/Views/WarehouseDashboardView.swift';
MERGE (n:ArchitectureNode {id: 'factory-portal'}) SET n.kind = 'web', n.language = 'ts', n.path = 'apps/factory-portal';
MERGE (n:ArchitectureNode {id: 'factory-app-android'}) SET n.kind = 'mobile', n.language = 'kotlin', n.path = 'apps/factory-app-android';
MERGE (n:ArchitectureNode {id: 'factory-app-ios'}) SET n.kind = 'mobile', n.language = 'swift', n.path = 'apps/factory-app-ios';
MERGE (n:ArchitectureNode {id: 'payload-terminal'}) SET n.kind = 'mobile', n.language = 'ts', n.path = 'apps/payload-terminal';
MERGE (n:ArchitectureNode {id: 'payload-app-ios'}) SET n.kind = 'mobile', n.language = 'swift', n.path = 'apps/payload-app-ios';
MERGE (n:ArchitectureNode {id: 'payload-app-android'}) SET n.kind = 'mobile', n.language = 'kotlin', n.path = 'apps/payload-app-android';
MERGE (n:ArchitectureNode {id: 'pkg-types'}) SET n.kind = 'package', n.language = 'ts', n.path = 'packages/types';
MERGE (n:ArchitectureNode {id: 'pkg-api-client'}) SET n.kind = 'package', n.language = 'ts', n.path = 'packages/api-client';
MERGE (n:ArchitectureNode {id: 'pkg-validation'}) SET n.kind = 'package', n.language = 'ts', n.path = 'packages/validation';
MERGE (n:ArchitectureNode {id: 'pkg-i18n'}) SET n.kind = 'package', n.language = 'ts', n.path = 'packages/i18n';
MERGE (n:ArchitectureNode {id: 'pkg-ui-kit'}) SET n.kind = 'package', n.language = 'ts', n.path = 'packages/ui-kit';
MERGE (n:ArchitectureNode {id: 'pkg-config'}) SET n.kind = 'package', n.language = 'go', n.path = 'packages/config';
MERGE (n:ArchitectureNode {id: 'contracts-events'}) SET n.kind = 'contract', n.language = 'json', n.path = 'contracts/events.schema.json';
MERGE (n:ArchitectureNode {id: 'spanner'}) SET n.kind = 'infra', n.language = 'ddl', n.path = 'apps/backend-go/schema/spanner.ddl';
MERGE (n:ArchitectureNode {id: 'redis'}) SET n.kind = 'infra', n.language = '', n.path = '';
MERGE (n:ArchitectureNode {id: 'kafka'}) SET n.kind = 'infra', n.language = '', n.path = '';
MERGE (n:ArchitectureNode {id: 'firebase-auth'}) SET n.kind = 'infra', n.language = '', n.path = '';
MERGE (n:ArchitectureNode {id: 'terraform'}) SET n.kind = 'infra', n.language = '', n.path = 'infra/terraform';
MATCH (a:ArchitectureNode {id: 'execution-plan'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'governs-delivery'}]->(b);
MATCH (a:ArchitectureNode {id: 'execution-plan'}), (b:ArchitectureNode {id: 'supplier-portal'}) MERGE (a)-[r:ARCH_REL {kind: 'governs-delivery'}]->(b);
MATCH (a:ArchitectureNode {id: 'execution-plan'}), (b:ArchitectureNode {id: 'ai-worker'}) MERGE (a)-[r:ARCH_REL {kind: 'governs-delivery'}]->(b);
MATCH (a:ArchitectureNode {id: 'execution-plan'}), (b:ArchitectureNode {id: 'terraform'}) MERGE (a)-[r:ARCH_REL {kind: 'governs-delivery'}]->(b);
MATCH (a:ArchitectureNode {id: 'ssmr-infra-workflow'}), (b:ArchitectureNode {id: 'ssmr-smoke-harness'}) MERGE (a)-[r:ARCH_REL {kind: 'ci-stage-gate'}]->(b);
MATCH (a:ArchitectureNode {id: 'ssmr-smoke-harness'}), (b:ArchitectureNode {id: 'docker-compose-ssmr'}) MERGE (a)-[r:ARCH_REL {kind: 'smoke-orchestration'}]->(b);
MATCH (a:ArchitectureNode {id: 'ssmr-smoke-harness'}), (b:ArchitectureNode {id: 'ssmr-smokecheck'}) MERGE (a)-[r:ARCH_REL {kind: 'direct-proof'}]->(b);
MATCH (a:ArchitectureNode {id: 'docker-compose-ssmr'}), (b:ArchitectureNode {id: 'backend-setup'}) MERGE (a)-[r:ARCH_REL {kind: 'local-bootstrap'}]->(b);
MATCH (a:ArchitectureNode {id: 'docker-compose-ssmr'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'local-runtime'}]->(b);
MATCH (a:ArchitectureNode {id: 'docker-compose-ssmr'}), (b:ArchitectureNode {id: 'ai-worker'}) MERGE (a)-[r:ARCH_REL {kind: 'local-runtime'}]->(b);
MATCH (a:ArchitectureNode {id: 'docker-compose-ssmr'}), (b:ArchitectureNode {id: 'ai-worker-monitoring'}) MERGE (a)-[r:ARCH_REL {kind: 'monitoring-port'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker-k8s-configmap'}), (b:ArchitectureNode {id: 'ai-worker-k8s-deployment'}) MERGE (a)-[r:ARCH_REL {kind: 'env-source'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker-k8s-deployment'}), (b:ArchitectureNode {id: 'ai-worker-k8s-service'}) MERGE (a)-[r:ARCH_REL {kind: 'service-selector'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker-k8s-deployment'}), (b:ArchitectureNode {id: 'ai-worker'}) MERGE (a)-[r:ARCH_REL {kind: 'deploys'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker-k8s-gate'}), (b:ArchitectureNode {id: 'ai-worker-k8s-configmap'}) MERGE (a)-[r:ARCH_REL {kind: 'validates'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker-k8s-gate'}), (b:ArchitectureNode {id: 'ai-worker-k8s-deployment'}) MERGE (a)-[r:ARCH_REL {kind: 'validates'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker-k8s-gate'}), (b:ArchitectureNode {id: 'ai-worker-k8s-service'}) MERGE (a)-[r:ARCH_REL {kind: 'validates'}]->(b);
MATCH (a:ArchitectureNode {id: 'terraform'}), (b:ArchitectureNode {id: 'terraform-observability'}) MERGE (a)-[r:ARCH_REL {kind: 'module-file'}]->(b);
MATCH (a:ArchitectureNode {id: 'terraform-observability'}), (b:ArchitectureNode {id: 'ai-worker-monitoring'}) MERGE (a)-[r:ARCH_REL {kind: 'alert+uptime'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-setup'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'schema-bootstrap'}]->(b);
MATCH (a:ArchitectureNode {id: 'ssmr-smokecheck'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'read-assert'}]->(b);
MATCH (a:ArchitectureNode {id: 'ssmr-smokecheck'}), (b:ArchitectureNode {id: 'redis'}) MERGE (a)-[r:ARCH_REL {kind: 'spatial-read-assert'}]->(b);
MATCH (a:ArchitectureNode {id: 'ssmr-smokecheck'}), (b:ArchitectureNode {id: 'kafka'}) MERGE (a)-[r:ARCH_REL {kind: 'topic-roundtrip-assert'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'order-spanner-repo'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'order-spanner-repo'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'order-persistence'}]->(b);
MATCH (a:ArchitectureNode {id: 'order-spanner-repo'}), (b:ArchitectureNode {id: 'order-delivery-proof-store'}) MERGE (a)-[r:ARCH_REL {kind: 'delivery-proof-write'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-spanner-repo'}), (b:ArchitectureNode {id: 'order-delivery-proof-store'}) MERGE (a)-[r:ARCH_REL {kind: 'receipt-proof-read'}]->(b);
MATCH (a:ArchitectureNode {id: 'order-delivery-proof-store'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'spanner-table'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'payment-service'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'bootstrap-runtime'}) MERGE (a)-[r:ARCH_REL {kind: 'composition-root'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'kafka-consumer'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'ws-connection'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'payment-routes'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'payment-routes'}), (b:ArchitectureNode {id: 'payment-service'}) MERGE (a)-[r:ARCH_REL {kind: 'route-mount'}]->(b);
MATCH (a:ArchitectureNode {id: 'payment-service'}), (b:ArchitectureNode {id: 'payment-spanner-repo'}) MERGE (a)-[r:ARCH_REL {kind: 'repository-call'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'payment-spanner-repo'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'payment-spanner-repo'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'payment-persistence'}]->(b);
MATCH (a:ArchitectureNode {id: 'bootstrap-runtime'}), (b:ArchitectureNode {id: 'ws-connection'}) MERGE (a)-[r:ARCH_REL {kind: 'websocket-origin-policy-config'}]->(b);
MATCH (a:ArchitectureNode {id: 'bootstrap-runtime'}), (b:ArchitectureNode {id: 'kafka-dlq-writer'}) MERGE (a)-[r:ARCH_REL {kind: 'notification-dlq-wiring'}]->(b);
MATCH (a:ArchitectureNode {id: 'kafka-consumer'}), (b:ArchitectureNode {id: 'kafka-dlq-writer'}) MERGE (a)-[r:ARCH_REL {kind: 'dlq-routing'}]->(b);
MATCH (a:ArchitectureNode {id: 'kafka-dlq-writer'}), (b:ArchitectureNode {id: 'kafka'}) MERGE (a)-[r:ARCH_REL {kind: 'dead-letter-topic-write'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'supplier-spanner-repo'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'supplier-onboarding-handlers'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-spanner-repo'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'supplier-persistence'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-onboarding-handlers'}), (b:ArchitectureNode {id: 'supplier-spanner-repo'}) MERGE (a)-[r:ARCH_REL {kind: 'repository-call'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'retailer-spanner-repo'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-spanner-repo'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'retailer-and-pricing-read'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'retailer-core-handlers'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-core-handlers'}), (b:ArchitectureNode {id: 'retailer-spanner-repo'}) MERGE (a)-[r:ARCH_REL {kind: 'repository-call'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'order-service'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'order-routes'}) MERGE (a)-[r:ARCH_REL {kind: 'route-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'order-routes'}), (b:ArchitectureNode {id: 'order-service'}) MERGE (a)-[r:ARCH_REL {kind: 'route-mount'}]->(b);
MATCH (a:ArchitectureNode {id: 'order-service'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'assignment-event-contract'}]->(b);
MATCH (a:ArchitectureNode {id: 'order-service'}), (b:ArchitectureNode {id: 'ws-handler'}) MERGE (a)-[r:ARCH_REL {kind: 'assignment-ws-fanout'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'telemetry-routes'}) MERGE (a)-[r:ARCH_REL {kind: 'route-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'telemetry-location-store'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'ws-handler'}), (b:ArchitectureNode {id: 'ws-connection'}) MERGE (a)-[r:ARCH_REL {kind: 'upgrade-origin-check'}]->(b);
MATCH (a:ArchitectureNode {id: 'telemetry-routes'}), (b:ArchitectureNode {id: 'ws-handler'}) MERGE (a)-[r:ARCH_REL {kind: 'scoped-telemetry-fanout'}]->(b);
MATCH (a:ArchitectureNode {id: 'telemetry-routes'}), (b:ArchitectureNode {id: 'telemetry-location-store'}) MERGE (a)-[r:ARCH_REL {kind: 'claims-derived-location-cache-write'}]->(b);
MATCH (a:ArchitectureNode {id: 'telemetry-location-store'}), (b:ArchitectureNode {id: 'redis'}) MERGE (a)-[r:ARCH_REL {kind: 'bounded-ttl-live-location-cache'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-core-handlers'}), (b:ArchitectureNode {id: 'telemetry-location-store'}) MERGE (a)-[r:ARCH_REL {kind: 'scoped-live-location-read'}]->(b);
MATCH (a:ArchitectureNode {id: 'telemetry-routes'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'driver-location-event-contract'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'factory-service'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'payload-service'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'warehouse-service'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'order-service'}), (b:ArchitectureNode {id: 'order-warehouse-resolver-spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'serviceability-resolution'}]->(b);
MATCH (a:ArchitectureNode {id: 'order-warehouse-resolver-spanner'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'serviceability-coverage-read'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'supplier-pricing-handlers'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-pricing-handlers'}), (b:ArchitectureNode {id: 'supplier-spanner-repo'}) MERGE (a)-[r:ARCH_REL {kind: 'repository-call'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-pricing-handlers'}), (b:ArchitectureNode {id: 'telemetry-location-store'}) MERGE (a)-[r:ARCH_REL {kind: 'scoped-live-location-read'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'retailer-proximity'}) MERGE (a)-[r:ARCH_REL {kind: 'domain-component'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-proximity'}), (b:ArchitectureNode {id: 'redis'}) MERGE (a)-[r:ARCH_REL {kind: 'spatial-membership'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-portal'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-portal'}), (b:ArchitectureNode {id: 'supplier-portal-api-proxy'}) MERGE (a)-[r:ARCH_REL {kind: 'same-origin-api'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-portal'}), (b:ArchitectureNode {id: 'supplier-orders-page'}) MERGE (a)-[r:ARCH_REL {kind: 'route-surface'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-portal'}), (b:ArchitectureNode {id: 'supplier-org-fleet-page'}) MERGE (a)-[r:ARCH_REL {kind: 'route-surface'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-portal'}), (b:ArchitectureNode {id: 'supplier-payments-page'}) MERGE (a)-[r:ARCH_REL {kind: 'route-surface'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-orders-page'}), (b:ArchitectureNode {id: 'supplier-portal-api-proxy'}) MERGE (a)-[r:ARCH_REL {kind: 'same-origin-api'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-orders-page'}), (b:ArchitectureNode {id: 'pkg-api-client'}) MERGE (a)-[r:ARCH_REL {kind: 'package-consumer'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-orders-page'}), (b:ArchitectureNode {id: 'pkg-types'}) MERGE (a)-[r:ARCH_REL {kind: 'package-consumer'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-org-fleet-page'}), (b:ArchitectureNode {id: 'supplier-portal-api-proxy'}) MERGE (a)-[r:ARCH_REL {kind: 'same-origin-api'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-org-fleet-page'}), (b:ArchitectureNode {id: 'pkg-api-client'}) MERGE (a)-[r:ARCH_REL {kind: 'package-consumer'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-org-fleet-page'}), (b:ArchitectureNode {id: 'pkg-types'}) MERGE (a)-[r:ARCH_REL {kind: 'package-consumer'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-payments-page'}), (b:ArchitectureNode {id: 'supplier-portal-api-proxy'}) MERGE (a)-[r:ARCH_REL {kind: 'same-origin-api'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-payments-page'}), (b:ArchitectureNode {id: 'pkg-api-client'}) MERGE (a)-[r:ARCH_REL {kind: 'package-consumer'}]->(b);
MATCH (a:ArchitectureNode {id: 'supplier-portal-api-proxy'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http-proxy'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-app-android'}), (b:ArchitectureNode {id: 'retailer-android-build-files'}) MERGE (a)-[r:ARCH_REL {kind: 'project-spec'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-app-android'}), (b:ArchitectureNode {id: 'retailer-android-tracking-screen'}) MERGE (a)-[r:ARCH_REL {kind: 'route-surface'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-android-tracking-screen'}), (b:ArchitectureNode {id: 'retailer-android-api-client'}) MERGE (a)-[r:ARCH_REL {kind: 'app-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-android-api-client'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-app-ios'}), (b:ArchitectureNode {id: 'retailer-ios-project-spec'}) MERGE (a)-[r:ARCH_REL {kind: 'project-spec'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-app-ios'}), (b:ArchitectureNode {id: 'retailer-ios-tracking-view'}) MERGE (a)-[r:ARCH_REL {kind: 'route-surface'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-ios-tracking-view'}), (b:ArchitectureNode {id: 'retailer-ios-api-client'}) MERGE (a)-[r:ARCH_REL {kind: 'app-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-ios-api-client'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-app-desktop'}), (b:ArchitectureNode {id: 'retailer-desktop-tracking-page'}) MERGE (a)-[r:ARCH_REL {kind: 'route-surface'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-desktop-tracking-page'}), (b:ArchitectureNode {id: 'retailer-desktop-api-proxy'}) MERGE (a)-[r:ARCH_REL {kind: 'same-origin-api'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-desktop-tracking-page'}), (b:ArchitectureNode {id: 'pkg-api-client'}) MERGE (a)-[r:ARCH_REL {kind: 'package-consumer'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-desktop-tracking-page'}), (b:ArchitectureNode {id: 'pkg-types'}) MERGE (a)-[r:ARCH_REL {kind: 'package-consumer'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-desktop-api-proxy'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http-proxy'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-app-android'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-app-ios'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-app-desktop'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'driver-app-android'}), (b:ArchitectureNode {id: 'driver-android-build-files'}) MERGE (a)-[r:ARCH_REL {kind: 'project-spec'}]->(b);
MATCH (a:ArchitectureNode {id: 'driver-app-android'}), (b:ArchitectureNode {id: 'driver-android-live-ops-screen'}) MERGE (a)-[r:ARCH_REL {kind: 'route-surface'}]->(b);
MATCH (a:ArchitectureNode {id: 'driver-android-live-ops-screen'}), (b:ArchitectureNode {id: 'driver-android-api-client'}) MERGE (a)-[r:ARCH_REL {kind: 'app-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'driver-android-api-client'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'driver-app-android'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'driverappios'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'driver-app-android'}), (b:ArchitectureNode {id: 'order-routes'}) MERGE (a)-[r:ARCH_REL {kind: 'driver-delivery-http'}]->(b);
MATCH (a:ArchitectureNode {id: 'driverappios'}), (b:ArchitectureNode {id: 'order-routes'}) MERGE (a)-[r:ARCH_REL {kind: 'driver-delivery-http'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-portal'}), (b:ArchitectureNode {id: 'warehouse-desktop-dashboard-page'}) MERGE (a)-[r:ARCH_REL {kind: 'route-surface'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-portal'}), (b:ArchitectureNode {id: 'warehouse-desktop-tauri-config'}) MERGE (a)-[r:ARCH_REL {kind: 'project-spec'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-desktop-tauri-config'}), (b:ArchitectureNode {id: 'warehouse-desktop-dashboard-page'}) MERGE (a)-[r:ARCH_REL {kind: 'bundles-static-export'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-desktop-dashboard-page'}), (b:ArchitectureNode {id: 'pkg-api-client'}) MERGE (a)-[r:ARCH_REL {kind: 'package-consumer'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-desktop-dashboard-page'}), (b:ArchitectureNode {id: 'pkg-types'}) MERGE (a)-[r:ARCH_REL {kind: 'package-consumer'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-desktop-dashboard-page'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-portal'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-app-android'}), (b:ArchitectureNode {id: 'warehouse-android-build-files'}) MERGE (a)-[r:ARCH_REL {kind: 'project-spec'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-app-android'}), (b:ArchitectureNode {id: 'warehouse-android-dashboard-screen'}) MERGE (a)-[r:ARCH_REL {kind: 'route-surface'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-android-dashboard-screen'}), (b:ArchitectureNode {id: 'warehouse-android-api-client'}) MERGE (a)-[r:ARCH_REL {kind: 'app-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-android-api-client'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-app-android'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-app-ios'}), (b:ArchitectureNode {id: 'warehouse-ios-project-spec'}) MERGE (a)-[r:ARCH_REL {kind: 'project-spec'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-app-ios'}), (b:ArchitectureNode {id: 'warehouse-ios-dashboard-view'}) MERGE (a)-[r:ARCH_REL {kind: 'route-surface'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-ios-dashboard-view'}), (b:ArchitectureNode {id: 'warehouse-ios-api-client'}) MERGE (a)-[r:ARCH_REL {kind: 'app-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-ios-api-client'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http-client'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-app-ios'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http'}]->(b);
MATCH (a:ArchitectureNode {id: 'factory-portal'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'factory-app-android'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'factory-app-ios'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'payload-terminal'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'payload-app-ios'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'payload-app-android'}), (b:ArchitectureNode {id: 'backend-go'}) MERGE (a)-[r:ARCH_REL {kind: 'http+ws'}]->(b);
MATCH (a:ArchitectureNode {id: 'pkg-api-client'}), (b:ArchitectureNode {id: 'pkg-types'}) MERGE (a)-[r:ARCH_REL {kind: 'package-dependency'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'rw-txn'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'redis'}) MERGE (a)-[r:ARCH_REL {kind: 'cache+pubsub'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'kafka'}) MERGE (a)-[r:ARCH_REL {kind: 'outbox-relay'}]->(b);
MATCH (a:ArchitectureNode {id: 'docker-compose-ssmr'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'local-emulator'}]->(b);
MATCH (a:ArchitectureNode {id: 'docker-compose-ssmr'}), (b:ArchitectureNode {id: 'redis'}) MERGE (a)-[r:ARCH_REL {kind: 'local-emulator'}]->(b);
MATCH (a:ArchitectureNode {id: 'docker-compose-ssmr'}), (b:ArchitectureNode {id: 'kafka'}) MERGE (a)-[r:ARCH_REL {kind: 'local-emulator'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'firebase-auth'}) MERGE (a)-[r:ARCH_REL {kind: 'id-token-verify'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker'}), (b:ArchitectureNode {id: 'ai-worker-monitoring'}) MERGE (a)-[r:ARCH_REL {kind: 'health+metrics'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker-k8s-deployment'}), (b:ArchitectureNode {id: 'ai-worker-monitoring'}) MERGE (a)-[r:ARCH_REL {kind: 'probe-target'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker'}), (b:ArchitectureNode {id: 'kafka'}) MERGE (a)-[r:ARCH_REL {kind: 'consume'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker-monitoring'}), (b:ArchitectureNode {id: 'kafka'}) MERGE (a)-[r:ARCH_REL {kind: 'lag-metrics'}]->(b);
MATCH (a:ArchitectureNode {id: 'ai-worker'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'rw-txn'}]->(b);
MATCH (a:ArchitectureNode {id: 'terraform'}), (b:ArchitectureNode {id: 'spanner'}) MERGE (a)-[r:ARCH_REL {kind: 'provision'}]->(b);
MATCH (a:ArchitectureNode {id: 'terraform'}), (b:ArchitectureNode {id: 'redis'}) MERGE (a)-[r:ARCH_REL {kind: 'provision'}]->(b);
MATCH (a:ArchitectureNode {id: 'terraform'}), (b:ArchitectureNode {id: 'kafka'}) MERGE (a)-[r:ARCH_REL {kind: 'runtime-secret-wiring'}]->(b);
MATCH (a:ArchitectureNode {id: 'backend-go'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'generates'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-app-android'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'codegen'}]->(b);
MATCH (a:ArchitectureNode {id: 'retailer-app-ios'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'codegen'}]->(b);
MATCH (a:ArchitectureNode {id: 'driver-app-android'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'codegen'}]->(b);
MATCH (a:ArchitectureNode {id: 'driverappios'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'codegen'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-app-android'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'codegen'}]->(b);
MATCH (a:ArchitectureNode {id: 'warehouse-app-ios'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'codegen'}]->(b);
MATCH (a:ArchitectureNode {id: 'factory-app-android'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'codegen'}]->(b);
MATCH (a:ArchitectureNode {id: 'factory-app-ios'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'codegen'}]->(b);
MATCH (a:ArchitectureNode {id: 'payload-app-android'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'codegen'}]->(b);
MATCH (a:ArchitectureNode {id: 'payload-app-ios'}), (b:ArchitectureNode {id: 'contracts-events'}) MERGE (a)-[r:ARCH_REL {kind: 'codegen'}]->(b);
