/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
)

// checks if the PartnerCreateOrder401Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerCreateOrder401Response{}

// PartnerCreateOrder401Response struct for PartnerCreateOrder401Response
type PartnerCreateOrder401Response struct {
	Error *string `json:"error,omitempty"`
	Code *string `json:"code,omitempty"`
}

// NewPartnerCreateOrder401Response instantiates a new PartnerCreateOrder401Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerCreateOrder401Response() *PartnerCreateOrder401Response {
	this := PartnerCreateOrder401Response{}
	return &this
}

// NewPartnerCreateOrder401ResponseWithDefaults instantiates a new PartnerCreateOrder401Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerCreateOrder401ResponseWithDefaults() *PartnerCreateOrder401Response {
	this := PartnerCreateOrder401Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PartnerCreateOrder401Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrder401Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PartnerCreateOrder401Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *PartnerCreateOrder401Response) SetError(v string) {
	o.Error = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PartnerCreateOrder401Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrder401Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PartnerCreateOrder401Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *PartnerCreateOrder401Response) SetCode(v string) {
	o.Code = &v
}

func (o PartnerCreateOrder401Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerCreateOrder401Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullablePartnerCreateOrder401Response struct {
	value *PartnerCreateOrder401Response
	isSet bool
}

func (v NullablePartnerCreateOrder401Response) Get() *PartnerCreateOrder401Response {
	return v.value
}

func (v *NullablePartnerCreateOrder401Response) Set(val *PartnerCreateOrder401Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerCreateOrder401Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerCreateOrder401Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerCreateOrder401Response(val *PartnerCreateOrder401Response) *NullablePartnerCreateOrder401Response {
	return &NullablePartnerCreateOrder401Response{value: val, isSet: true}
}

func (v NullablePartnerCreateOrder401Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerCreateOrder401Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


