/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerPOSDemandFeedRequestLinesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerPOSDemandFeedRequestLinesInner{}

// PartnerPOSDemandFeedRequestLinesInner struct for PartnerPOSDemandFeedRequestLinesInner
type PartnerPOSDemandFeedRequestLinesInner struct {
	ExternalId string `json:"external_id"`
	Quantity float32 `json:"quantity"`
	Unit *string `json:"unit,omitempty"`
}

type _PartnerPOSDemandFeedRequestLinesInner PartnerPOSDemandFeedRequestLinesInner

// NewPartnerPOSDemandFeedRequestLinesInner instantiates a new PartnerPOSDemandFeedRequestLinesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerPOSDemandFeedRequestLinesInner(externalId string, quantity float32) *PartnerPOSDemandFeedRequestLinesInner {
	this := PartnerPOSDemandFeedRequestLinesInner{}
	this.ExternalId = externalId
	this.Quantity = quantity
	return &this
}

// NewPartnerPOSDemandFeedRequestLinesInnerWithDefaults instantiates a new PartnerPOSDemandFeedRequestLinesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerPOSDemandFeedRequestLinesInnerWithDefaults() *PartnerPOSDemandFeedRequestLinesInner {
	this := PartnerPOSDemandFeedRequestLinesInner{}
	return &this
}

// GetExternalId returns the ExternalId field value
func (o *PartnerPOSDemandFeedRequestLinesInner) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *PartnerPOSDemandFeedRequestLinesInner) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *PartnerPOSDemandFeedRequestLinesInner) SetExternalId(v string) {
	o.ExternalId = v
}

// GetQuantity returns the Quantity field value
func (o *PartnerPOSDemandFeedRequestLinesInner) GetQuantity() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *PartnerPOSDemandFeedRequestLinesInner) GetQuantityOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *PartnerPOSDemandFeedRequestLinesInner) SetQuantity(v float32) {
	o.Quantity = v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *PartnerPOSDemandFeedRequestLinesInner) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerPOSDemandFeedRequestLinesInner) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *PartnerPOSDemandFeedRequestLinesInner) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *PartnerPOSDemandFeedRequestLinesInner) SetUnit(v string) {
	o.Unit = &v
}

func (o PartnerPOSDemandFeedRequestLinesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerPOSDemandFeedRequestLinesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["external_id"] = o.ExternalId
	toSerialize["quantity"] = o.Quantity
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	return toSerialize, nil
}

func (o *PartnerPOSDemandFeedRequestLinesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"external_id",
		"quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerPOSDemandFeedRequestLinesInner := _PartnerPOSDemandFeedRequestLinesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerPOSDemandFeedRequestLinesInner)

	if err != nil {
		return err
	}

	*o = PartnerPOSDemandFeedRequestLinesInner(varPartnerPOSDemandFeedRequestLinesInner)

	return err
}

type NullablePartnerPOSDemandFeedRequestLinesInner struct {
	value *PartnerPOSDemandFeedRequestLinesInner
	isSet bool
}

func (v NullablePartnerPOSDemandFeedRequestLinesInner) Get() *PartnerPOSDemandFeedRequestLinesInner {
	return v.value
}

func (v *NullablePartnerPOSDemandFeedRequestLinesInner) Set(val *PartnerPOSDemandFeedRequestLinesInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerPOSDemandFeedRequestLinesInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerPOSDemandFeedRequestLinesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerPOSDemandFeedRequestLinesInner(val *PartnerPOSDemandFeedRequestLinesInner) *NullablePartnerPOSDemandFeedRequestLinesInner {
	return &NullablePartnerPOSDemandFeedRequestLinesInner{value: val, isSet: true}
}

func (v NullablePartnerPOSDemandFeedRequestLinesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerPOSDemandFeedRequestLinesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


