/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerOAuthTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerOAuthTokenRequest{}

// PartnerOAuthTokenRequest struct for PartnerOAuthTokenRequest
type PartnerOAuthTokenRequest struct {
	GrantType string `json:"grant_type"`
	// PartnerApiKeys.KeyId or KeyPrefix
	ClientId *string `json:"client_id,omitempty"`
	// Full pxk_… plaintext
	ClientSecret string `json:"client_secret"`
	// Space-separated subset of key scopes
	Scope *string `json:"scope,omitempty"`
}

type _PartnerOAuthTokenRequest PartnerOAuthTokenRequest

// NewPartnerOAuthTokenRequest instantiates a new PartnerOAuthTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerOAuthTokenRequest(grantType string, clientSecret string) *PartnerOAuthTokenRequest {
	this := PartnerOAuthTokenRequest{}
	this.GrantType = grantType
	this.ClientSecret = clientSecret
	return &this
}

// NewPartnerOAuthTokenRequestWithDefaults instantiates a new PartnerOAuthTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerOAuthTokenRequestWithDefaults() *PartnerOAuthTokenRequest {
	this := PartnerOAuthTokenRequest{}
	return &this
}

// GetGrantType returns the GrantType field value
func (o *PartnerOAuthTokenRequest) GetGrantType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantType
}

// GetGrantTypeOk returns a tuple with the GrantType field value
// and a boolean to check if the value has been set.
func (o *PartnerOAuthTokenRequest) GetGrantTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantType, true
}

// SetGrantType sets field value
func (o *PartnerOAuthTokenRequest) SetGrantType(v string) {
	o.GrantType = v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *PartnerOAuthTokenRequest) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerOAuthTokenRequest) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *PartnerOAuthTokenRequest) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *PartnerOAuthTokenRequest) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value
func (o *PartnerOAuthTokenRequest) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *PartnerOAuthTokenRequest) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *PartnerOAuthTokenRequest) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *PartnerOAuthTokenRequest) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerOAuthTokenRequest) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *PartnerOAuthTokenRequest) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *PartnerOAuthTokenRequest) SetScope(v string) {
	o.Scope = &v
}

func (o PartnerOAuthTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerOAuthTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["grant_type"] = o.GrantType
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	toSerialize["client_secret"] = o.ClientSecret
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	return toSerialize, nil
}

func (o *PartnerOAuthTokenRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"grant_type",
		"client_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerOAuthTokenRequest := _PartnerOAuthTokenRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerOAuthTokenRequest)

	if err != nil {
		return err
	}

	*o = PartnerOAuthTokenRequest(varPartnerOAuthTokenRequest)

	return err
}

type NullablePartnerOAuthTokenRequest struct {
	value *PartnerOAuthTokenRequest
	isSet bool
}

func (v NullablePartnerOAuthTokenRequest) Get() *PartnerOAuthTokenRequest {
	return v.value
}

func (v *NullablePartnerOAuthTokenRequest) Set(val *PartnerOAuthTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerOAuthTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerOAuthTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerOAuthTokenRequest(val *PartnerOAuthTokenRequest) *NullablePartnerOAuthTokenRequest {
	return &NullablePartnerOAuthTokenRequest{value: val, isSet: true}
}

func (v NullablePartnerOAuthTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerOAuthTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


