/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
)

// checks if the PartnerCreateOrderRequestLineItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerCreateOrderRequestLineItemsInner{}

// PartnerCreateOrderRequestLineItemsInner struct for PartnerCreateOrderRequestLineItemsInner
type PartnerCreateOrderRequestLineItemsInner struct {
	Sku *string `json:"sku,omitempty"`
	Quantity *int32 `json:"quantity,omitempty"`
}

// NewPartnerCreateOrderRequestLineItemsInner instantiates a new PartnerCreateOrderRequestLineItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerCreateOrderRequestLineItemsInner() *PartnerCreateOrderRequestLineItemsInner {
	this := PartnerCreateOrderRequestLineItemsInner{}
	return &this
}

// NewPartnerCreateOrderRequestLineItemsInnerWithDefaults instantiates a new PartnerCreateOrderRequestLineItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerCreateOrderRequestLineItemsInnerWithDefaults() *PartnerCreateOrderRequestLineItemsInner {
	this := PartnerCreateOrderRequestLineItemsInner{}
	return &this
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *PartnerCreateOrderRequestLineItemsInner) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderRequestLineItemsInner) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *PartnerCreateOrderRequestLineItemsInner) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *PartnerCreateOrderRequestLineItemsInner) SetSku(v string) {
	o.Sku = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *PartnerCreateOrderRequestLineItemsInner) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderRequestLineItemsInner) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *PartnerCreateOrderRequestLineItemsInner) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *PartnerCreateOrderRequestLineItemsInner) SetQuantity(v int32) {
	o.Quantity = &v
}

func (o PartnerCreateOrderRequestLineItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerCreateOrderRequestLineItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	return toSerialize, nil
}

type NullablePartnerCreateOrderRequestLineItemsInner struct {
	value *PartnerCreateOrderRequestLineItemsInner
	isSet bool
}

func (v NullablePartnerCreateOrderRequestLineItemsInner) Get() *PartnerCreateOrderRequestLineItemsInner {
	return v.value
}

func (v *NullablePartnerCreateOrderRequestLineItemsInner) Set(val *PartnerCreateOrderRequestLineItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerCreateOrderRequestLineItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerCreateOrderRequestLineItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerCreateOrderRequestLineItemsInner(val *PartnerCreateOrderRequestLineItemsInner) *NullablePartnerCreateOrderRequestLineItemsInner {
	return &NullablePartnerCreateOrderRequestLineItemsInner{value: val, isSet: true}
}

func (v NullablePartnerCreateOrderRequestLineItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerCreateOrderRequestLineItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


