/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"time"
)

// checks if the PartnerEdiDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerEdiDocument{}

// PartnerEdiDocument struct for PartnerEdiDocument
type PartnerEdiDocument struct {
	DocumentId *string `json:"document_id,omitempty"`
	Direction *string `json:"direction,omitempty"`
	DocType *string `json:"doc_type,omitempty"`
	ExternalDocId *string `json:"external_doc_id,omitempty"`
	OrderId *string `json:"order_id,omitempty"`
	Status *string `json:"status,omitempty"`
	RemoteName *string `json:"remote_name,omitempty"`
	ObjectPath *string `json:"object_path,omitempty"`
	Error *string `json:"error,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
}

// NewPartnerEdiDocument instantiates a new PartnerEdiDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerEdiDocument() *PartnerEdiDocument {
	this := PartnerEdiDocument{}
	return &this
}

// NewPartnerEdiDocumentWithDefaults instantiates a new PartnerEdiDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerEdiDocumentWithDefaults() *PartnerEdiDocument {
	this := PartnerEdiDocument{}
	return &this
}

// GetDocumentId returns the DocumentId field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetDocumentId() string {
	if o == nil || IsNil(o.DocumentId) {
		var ret string
		return ret
	}
	return *o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetDocumentIdOk() (*string, bool) {
	if o == nil || IsNil(o.DocumentId) {
		return nil, false
	}
	return o.DocumentId, true
}

// HasDocumentId returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasDocumentId() bool {
	if o != nil && !IsNil(o.DocumentId) {
		return true
	}

	return false
}

// SetDocumentId gets a reference to the given string and assigns it to the DocumentId field.
func (o *PartnerEdiDocument) SetDocumentId(v string) {
	o.DocumentId = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetDirection() string {
	if o == nil || IsNil(o.Direction) {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *PartnerEdiDocument) SetDirection(v string) {
	o.Direction = &v
}

// GetDocType returns the DocType field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetDocType() string {
	if o == nil || IsNil(o.DocType) {
		var ret string
		return ret
	}
	return *o.DocType
}

// GetDocTypeOk returns a tuple with the DocType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetDocTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DocType) {
		return nil, false
	}
	return o.DocType, true
}

// HasDocType returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasDocType() bool {
	if o != nil && !IsNil(o.DocType) {
		return true
	}

	return false
}

// SetDocType gets a reference to the given string and assigns it to the DocType field.
func (o *PartnerEdiDocument) SetDocType(v string) {
	o.DocType = &v
}

// GetExternalDocId returns the ExternalDocId field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetExternalDocId() string {
	if o == nil || IsNil(o.ExternalDocId) {
		var ret string
		return ret
	}
	return *o.ExternalDocId
}

// GetExternalDocIdOk returns a tuple with the ExternalDocId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetExternalDocIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalDocId) {
		return nil, false
	}
	return o.ExternalDocId, true
}

// HasExternalDocId returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasExternalDocId() bool {
	if o != nil && !IsNil(o.ExternalDocId) {
		return true
	}

	return false
}

// SetExternalDocId gets a reference to the given string and assigns it to the ExternalDocId field.
func (o *PartnerEdiDocument) SetExternalDocId(v string) {
	o.ExternalDocId = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *PartnerEdiDocument) SetOrderId(v string) {
	o.OrderId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PartnerEdiDocument) SetStatus(v string) {
	o.Status = &v
}

// GetRemoteName returns the RemoteName field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetRemoteName() string {
	if o == nil || IsNil(o.RemoteName) {
		var ret string
		return ret
	}
	return *o.RemoteName
}

// GetRemoteNameOk returns a tuple with the RemoteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetRemoteNameOk() (*string, bool) {
	if o == nil || IsNil(o.RemoteName) {
		return nil, false
	}
	return o.RemoteName, true
}

// HasRemoteName returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasRemoteName() bool {
	if o != nil && !IsNil(o.RemoteName) {
		return true
	}

	return false
}

// SetRemoteName gets a reference to the given string and assigns it to the RemoteName field.
func (o *PartnerEdiDocument) SetRemoteName(v string) {
	o.RemoteName = &v
}

// GetObjectPath returns the ObjectPath field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetObjectPath() string {
	if o == nil || IsNil(o.ObjectPath) {
		var ret string
		return ret
	}
	return *o.ObjectPath
}

// GetObjectPathOk returns a tuple with the ObjectPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetObjectPathOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectPath) {
		return nil, false
	}
	return o.ObjectPath, true
}

// HasObjectPath returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasObjectPath() bool {
	if o != nil && !IsNil(o.ObjectPath) {
		return true
	}

	return false
}

// SetObjectPath gets a reference to the given string and assigns it to the ObjectPath field.
func (o *PartnerEdiDocument) SetObjectPath(v string) {
	o.ObjectPath = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *PartnerEdiDocument) SetError(v string) {
	o.Error = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *PartnerEdiDocument) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise.
func (o *PartnerEdiDocument) GetFinishedAt() time.Time {
	if o == nil || IsNil(o.FinishedAt) {
		var ret time.Time
		return ret
	}
	return *o.FinishedAt
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerEdiDocument) GetFinishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FinishedAt) {
		return nil, false
	}
	return o.FinishedAt, true
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *PartnerEdiDocument) HasFinishedAt() bool {
	if o != nil && !IsNil(o.FinishedAt) {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given time.Time and assigns it to the FinishedAt field.
func (o *PartnerEdiDocument) SetFinishedAt(v time.Time) {
	o.FinishedAt = &v
}

func (o PartnerEdiDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerEdiDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DocumentId) {
		toSerialize["document_id"] = o.DocumentId
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.DocType) {
		toSerialize["doc_type"] = o.DocType
	}
	if !IsNil(o.ExternalDocId) {
		toSerialize["external_doc_id"] = o.ExternalDocId
	}
	if !IsNil(o.OrderId) {
		toSerialize["order_id"] = o.OrderId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.RemoteName) {
		toSerialize["remote_name"] = o.RemoteName
	}
	if !IsNil(o.ObjectPath) {
		toSerialize["object_path"] = o.ObjectPath
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.FinishedAt) {
		toSerialize["finished_at"] = o.FinishedAt
	}
	return toSerialize, nil
}

type NullablePartnerEdiDocument struct {
	value *PartnerEdiDocument
	isSet bool
}

func (v NullablePartnerEdiDocument) Get() *PartnerEdiDocument {
	return v.value
}

func (v *NullablePartnerEdiDocument) Set(val *PartnerEdiDocument) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerEdiDocument) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerEdiDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerEdiDocument(val *PartnerEdiDocument) *NullablePartnerEdiDocument {
	return &NullablePartnerEdiDocument{value: val, isSet: true}
}

func (v NullablePartnerEdiDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerEdiDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


