/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerOAuthTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerOAuthTokenResponse{}

// PartnerOAuthTokenResponse struct for PartnerOAuthTokenResponse
type PartnerOAuthTokenResponse struct {
	AccessToken string `json:"access_token"`
	TokenType string `json:"token_type"`
	ExpiresIn int32 `json:"expires_in"`
	Scope *string `json:"scope,omitempty"`
}

type _PartnerOAuthTokenResponse PartnerOAuthTokenResponse

// NewPartnerOAuthTokenResponse instantiates a new PartnerOAuthTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerOAuthTokenResponse(accessToken string, tokenType string, expiresIn int32) *PartnerOAuthTokenResponse {
	this := PartnerOAuthTokenResponse{}
	this.AccessToken = accessToken
	this.TokenType = tokenType
	this.ExpiresIn = expiresIn
	return &this
}

// NewPartnerOAuthTokenResponseWithDefaults instantiates a new PartnerOAuthTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerOAuthTokenResponseWithDefaults() *PartnerOAuthTokenResponse {
	this := PartnerOAuthTokenResponse{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *PartnerOAuthTokenResponse) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *PartnerOAuthTokenResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *PartnerOAuthTokenResponse) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetTokenType returns the TokenType field value
func (o *PartnerOAuthTokenResponse) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *PartnerOAuthTokenResponse) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *PartnerOAuthTokenResponse) SetTokenType(v string) {
	o.TokenType = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *PartnerOAuthTokenResponse) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *PartnerOAuthTokenResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *PartnerOAuthTokenResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *PartnerOAuthTokenResponse) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerOAuthTokenResponse) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *PartnerOAuthTokenResponse) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *PartnerOAuthTokenResponse) SetScope(v string) {
	o.Scope = &v
}

func (o PartnerOAuthTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerOAuthTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["token_type"] = o.TokenType
	toSerialize["expires_in"] = o.ExpiresIn
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	return toSerialize, nil
}

func (o *PartnerOAuthTokenResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"token_type",
		"expires_in",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerOAuthTokenResponse := _PartnerOAuthTokenResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerOAuthTokenResponse)

	if err != nil {
		return err
	}

	*o = PartnerOAuthTokenResponse(varPartnerOAuthTokenResponse)

	return err
}

type NullablePartnerOAuthTokenResponse struct {
	value *PartnerOAuthTokenResponse
	isSet bool
}

func (v NullablePartnerOAuthTokenResponse) Get() *PartnerOAuthTokenResponse {
	return v.value
}

func (v *NullablePartnerOAuthTokenResponse) Set(val *PartnerOAuthTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerOAuthTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerOAuthTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerOAuthTokenResponse(val *PartnerOAuthTokenResponse) *NullablePartnerOAuthTokenResponse {
	return &NullablePartnerOAuthTokenResponse{value: val, isSet: true}
}

func (v NullablePartnerOAuthTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerOAuthTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


