/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
)

// checks if the PartnerAs2ConfigUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerAs2ConfigUpdate{}

// PartnerAs2ConfigUpdate struct for PartnerAs2ConfigUpdate
type PartnerAs2ConfigUpdate struct {
	As2Enabled *bool `json:"as2_enabled,omitempty"`
	OurAs2Id *string `json:"our_as2_id,omitempty"`
	PartnerAs2Id *string `json:"partner_as2_id,omitempty"`
	PartnerUrl *string `json:"partner_url,omitempty"`
	OurCertSecretRef *string `json:"our_cert_secret_ref,omitempty"`
	OurKeySecretRef *string `json:"our_key_secret_ref,omitempty"`
	PartnerCertSecretRef *string `json:"partner_cert_secret_ref,omitempty"`
	SignRequired *bool `json:"sign_required,omitempty"`
	EncryptRequired *bool `json:"encrypt_required,omitempty"`
}

// NewPartnerAs2ConfigUpdate instantiates a new PartnerAs2ConfigUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerAs2ConfigUpdate() *PartnerAs2ConfigUpdate {
	this := PartnerAs2ConfigUpdate{}
	return &this
}

// NewPartnerAs2ConfigUpdateWithDefaults instantiates a new PartnerAs2ConfigUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerAs2ConfigUpdateWithDefaults() *PartnerAs2ConfigUpdate {
	this := PartnerAs2ConfigUpdate{}
	return &this
}

// GetAs2Enabled returns the As2Enabled field value if set, zero value otherwise.
func (o *PartnerAs2ConfigUpdate) GetAs2Enabled() bool {
	if o == nil || IsNil(o.As2Enabled) {
		var ret bool
		return ret
	}
	return *o.As2Enabled
}

// GetAs2EnabledOk returns a tuple with the As2Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerAs2ConfigUpdate) GetAs2EnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.As2Enabled) {
		return nil, false
	}
	return o.As2Enabled, true
}

// HasAs2Enabled returns a boolean if a field has been set.
func (o *PartnerAs2ConfigUpdate) HasAs2Enabled() bool {
	if o != nil && !IsNil(o.As2Enabled) {
		return true
	}

	return false
}

// SetAs2Enabled gets a reference to the given bool and assigns it to the As2Enabled field.
func (o *PartnerAs2ConfigUpdate) SetAs2Enabled(v bool) {
	o.As2Enabled = &v
}

// GetOurAs2Id returns the OurAs2Id field value if set, zero value otherwise.
func (o *PartnerAs2ConfigUpdate) GetOurAs2Id() string {
	if o == nil || IsNil(o.OurAs2Id) {
		var ret string
		return ret
	}
	return *o.OurAs2Id
}

// GetOurAs2IdOk returns a tuple with the OurAs2Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerAs2ConfigUpdate) GetOurAs2IdOk() (*string, bool) {
	if o == nil || IsNil(o.OurAs2Id) {
		return nil, false
	}
	return o.OurAs2Id, true
}

// HasOurAs2Id returns a boolean if a field has been set.
func (o *PartnerAs2ConfigUpdate) HasOurAs2Id() bool {
	if o != nil && !IsNil(o.OurAs2Id) {
		return true
	}

	return false
}

// SetOurAs2Id gets a reference to the given string and assigns it to the OurAs2Id field.
func (o *PartnerAs2ConfigUpdate) SetOurAs2Id(v string) {
	o.OurAs2Id = &v
}

// GetPartnerAs2Id returns the PartnerAs2Id field value if set, zero value otherwise.
func (o *PartnerAs2ConfigUpdate) GetPartnerAs2Id() string {
	if o == nil || IsNil(o.PartnerAs2Id) {
		var ret string
		return ret
	}
	return *o.PartnerAs2Id
}

// GetPartnerAs2IdOk returns a tuple with the PartnerAs2Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerAs2ConfigUpdate) GetPartnerAs2IdOk() (*string, bool) {
	if o == nil || IsNil(o.PartnerAs2Id) {
		return nil, false
	}
	return o.PartnerAs2Id, true
}

// HasPartnerAs2Id returns a boolean if a field has been set.
func (o *PartnerAs2ConfigUpdate) HasPartnerAs2Id() bool {
	if o != nil && !IsNil(o.PartnerAs2Id) {
		return true
	}

	return false
}

// SetPartnerAs2Id gets a reference to the given string and assigns it to the PartnerAs2Id field.
func (o *PartnerAs2ConfigUpdate) SetPartnerAs2Id(v string) {
	o.PartnerAs2Id = &v
}

// GetPartnerUrl returns the PartnerUrl field value if set, zero value otherwise.
func (o *PartnerAs2ConfigUpdate) GetPartnerUrl() string {
	if o == nil || IsNil(o.PartnerUrl) {
		var ret string
		return ret
	}
	return *o.PartnerUrl
}

// GetPartnerUrlOk returns a tuple with the PartnerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerAs2ConfigUpdate) GetPartnerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PartnerUrl) {
		return nil, false
	}
	return o.PartnerUrl, true
}

// HasPartnerUrl returns a boolean if a field has been set.
func (o *PartnerAs2ConfigUpdate) HasPartnerUrl() bool {
	if o != nil && !IsNil(o.PartnerUrl) {
		return true
	}

	return false
}

// SetPartnerUrl gets a reference to the given string and assigns it to the PartnerUrl field.
func (o *PartnerAs2ConfigUpdate) SetPartnerUrl(v string) {
	o.PartnerUrl = &v
}

// GetOurCertSecretRef returns the OurCertSecretRef field value if set, zero value otherwise.
func (o *PartnerAs2ConfigUpdate) GetOurCertSecretRef() string {
	if o == nil || IsNil(o.OurCertSecretRef) {
		var ret string
		return ret
	}
	return *o.OurCertSecretRef
}

// GetOurCertSecretRefOk returns a tuple with the OurCertSecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerAs2ConfigUpdate) GetOurCertSecretRefOk() (*string, bool) {
	if o == nil || IsNil(o.OurCertSecretRef) {
		return nil, false
	}
	return o.OurCertSecretRef, true
}

// HasOurCertSecretRef returns a boolean if a field has been set.
func (o *PartnerAs2ConfigUpdate) HasOurCertSecretRef() bool {
	if o != nil && !IsNil(o.OurCertSecretRef) {
		return true
	}

	return false
}

// SetOurCertSecretRef gets a reference to the given string and assigns it to the OurCertSecretRef field.
func (o *PartnerAs2ConfigUpdate) SetOurCertSecretRef(v string) {
	o.OurCertSecretRef = &v
}

// GetOurKeySecretRef returns the OurKeySecretRef field value if set, zero value otherwise.
func (o *PartnerAs2ConfigUpdate) GetOurKeySecretRef() string {
	if o == nil || IsNil(o.OurKeySecretRef) {
		var ret string
		return ret
	}
	return *o.OurKeySecretRef
}

// GetOurKeySecretRefOk returns a tuple with the OurKeySecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerAs2ConfigUpdate) GetOurKeySecretRefOk() (*string, bool) {
	if o == nil || IsNil(o.OurKeySecretRef) {
		return nil, false
	}
	return o.OurKeySecretRef, true
}

// HasOurKeySecretRef returns a boolean if a field has been set.
func (o *PartnerAs2ConfigUpdate) HasOurKeySecretRef() bool {
	if o != nil && !IsNil(o.OurKeySecretRef) {
		return true
	}

	return false
}

// SetOurKeySecretRef gets a reference to the given string and assigns it to the OurKeySecretRef field.
func (o *PartnerAs2ConfigUpdate) SetOurKeySecretRef(v string) {
	o.OurKeySecretRef = &v
}

// GetPartnerCertSecretRef returns the PartnerCertSecretRef field value if set, zero value otherwise.
func (o *PartnerAs2ConfigUpdate) GetPartnerCertSecretRef() string {
	if o == nil || IsNil(o.PartnerCertSecretRef) {
		var ret string
		return ret
	}
	return *o.PartnerCertSecretRef
}

// GetPartnerCertSecretRefOk returns a tuple with the PartnerCertSecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerAs2ConfigUpdate) GetPartnerCertSecretRefOk() (*string, bool) {
	if o == nil || IsNil(o.PartnerCertSecretRef) {
		return nil, false
	}
	return o.PartnerCertSecretRef, true
}

// HasPartnerCertSecretRef returns a boolean if a field has been set.
func (o *PartnerAs2ConfigUpdate) HasPartnerCertSecretRef() bool {
	if o != nil && !IsNil(o.PartnerCertSecretRef) {
		return true
	}

	return false
}

// SetPartnerCertSecretRef gets a reference to the given string and assigns it to the PartnerCertSecretRef field.
func (o *PartnerAs2ConfigUpdate) SetPartnerCertSecretRef(v string) {
	o.PartnerCertSecretRef = &v
}

// GetSignRequired returns the SignRequired field value if set, zero value otherwise.
func (o *PartnerAs2ConfigUpdate) GetSignRequired() bool {
	if o == nil || IsNil(o.SignRequired) {
		var ret bool
		return ret
	}
	return *o.SignRequired
}

// GetSignRequiredOk returns a tuple with the SignRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerAs2ConfigUpdate) GetSignRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.SignRequired) {
		return nil, false
	}
	return o.SignRequired, true
}

// HasSignRequired returns a boolean if a field has been set.
func (o *PartnerAs2ConfigUpdate) HasSignRequired() bool {
	if o != nil && !IsNil(o.SignRequired) {
		return true
	}

	return false
}

// SetSignRequired gets a reference to the given bool and assigns it to the SignRequired field.
func (o *PartnerAs2ConfigUpdate) SetSignRequired(v bool) {
	o.SignRequired = &v
}

// GetEncryptRequired returns the EncryptRequired field value if set, zero value otherwise.
func (o *PartnerAs2ConfigUpdate) GetEncryptRequired() bool {
	if o == nil || IsNil(o.EncryptRequired) {
		var ret bool
		return ret
	}
	return *o.EncryptRequired
}

// GetEncryptRequiredOk returns a tuple with the EncryptRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerAs2ConfigUpdate) GetEncryptRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.EncryptRequired) {
		return nil, false
	}
	return o.EncryptRequired, true
}

// HasEncryptRequired returns a boolean if a field has been set.
func (o *PartnerAs2ConfigUpdate) HasEncryptRequired() bool {
	if o != nil && !IsNil(o.EncryptRequired) {
		return true
	}

	return false
}

// SetEncryptRequired gets a reference to the given bool and assigns it to the EncryptRequired field.
func (o *PartnerAs2ConfigUpdate) SetEncryptRequired(v bool) {
	o.EncryptRequired = &v
}

func (o PartnerAs2ConfigUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerAs2ConfigUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.As2Enabled) {
		toSerialize["as2_enabled"] = o.As2Enabled
	}
	if !IsNil(o.OurAs2Id) {
		toSerialize["our_as2_id"] = o.OurAs2Id
	}
	if !IsNil(o.PartnerAs2Id) {
		toSerialize["partner_as2_id"] = o.PartnerAs2Id
	}
	if !IsNil(o.PartnerUrl) {
		toSerialize["partner_url"] = o.PartnerUrl
	}
	if !IsNil(o.OurCertSecretRef) {
		toSerialize["our_cert_secret_ref"] = o.OurCertSecretRef
	}
	if !IsNil(o.OurKeySecretRef) {
		toSerialize["our_key_secret_ref"] = o.OurKeySecretRef
	}
	if !IsNil(o.PartnerCertSecretRef) {
		toSerialize["partner_cert_secret_ref"] = o.PartnerCertSecretRef
	}
	if !IsNil(o.SignRequired) {
		toSerialize["sign_required"] = o.SignRequired
	}
	if !IsNil(o.EncryptRequired) {
		toSerialize["encrypt_required"] = o.EncryptRequired
	}
	return toSerialize, nil
}

type NullablePartnerAs2ConfigUpdate struct {
	value *PartnerAs2ConfigUpdate
	isSet bool
}

func (v NullablePartnerAs2ConfigUpdate) Get() *PartnerAs2ConfigUpdate {
	return v.value
}

func (v *NullablePartnerAs2ConfigUpdate) Set(val *PartnerAs2ConfigUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerAs2ConfigUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerAs2ConfigUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerAs2ConfigUpdate(val *PartnerAs2ConfigUpdate) *NullablePartnerAs2ConfigUpdate {
	return &NullablePartnerAs2ConfigUpdate{value: val, isSet: true}
}

func (v NullablePartnerAs2ConfigUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerAs2ConfigUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


