/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
)

// checks if the PartnerSftpConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerSftpConfig{}

// PartnerSftpConfig SFTP destination metadata (secret material never returned)
type PartnerSftpConfig struct {
	Configured *bool `json:"configured,omitempty"`
	Host *string `json:"host,omitempty"`
	Port *int32 `json:"port,omitempty"`
	Username *string `json:"username,omitempty"`
	// GSM secret name (not plaintext)
	SecretRef *string `json:"secret_ref,omitempty"`
	RemoteDir *string `json:"remote_dir,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	InboundDir *string `json:"inbound_dir,omitempty"`
	OutboundDir *string `json:"outbound_dir,omitempty"`
	ArchiveDir *string `json:"archive_dir,omitempty"`
	EdiEnabled *bool `json:"edi_enabled,omitempty"`
	// Base64 SHA-256 of SSH host key (pin); required when PARTNER_SFTP_STRICT_HOSTKEY=true
	HostKeySha256 *string `json:"host_key_sha256,omitempty"`
}

// NewPartnerSftpConfig instantiates a new PartnerSftpConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerSftpConfig() *PartnerSftpConfig {
	this := PartnerSftpConfig{}
	return &this
}

// NewPartnerSftpConfigWithDefaults instantiates a new PartnerSftpConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerSftpConfigWithDefaults() *PartnerSftpConfig {
	this := PartnerSftpConfig{}
	return &this
}

// GetConfigured returns the Configured field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetConfigured() bool {
	if o == nil || IsNil(o.Configured) {
		var ret bool
		return ret
	}
	return *o.Configured
}

// GetConfiguredOk returns a tuple with the Configured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetConfiguredOk() (*bool, bool) {
	if o == nil || IsNil(o.Configured) {
		return nil, false
	}
	return o.Configured, true
}

// HasConfigured returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasConfigured() bool {
	if o != nil && !IsNil(o.Configured) {
		return true
	}

	return false
}

// SetConfigured gets a reference to the given bool and assigns it to the Configured field.
func (o *PartnerSftpConfig) SetConfigured(v bool) {
	o.Configured = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *PartnerSftpConfig) SetHost(v string) {
	o.Host = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *PartnerSftpConfig) SetPort(v int32) {
	o.Port = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *PartnerSftpConfig) SetUsername(v string) {
	o.Username = &v
}

// GetSecretRef returns the SecretRef field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetSecretRef() string {
	if o == nil || IsNil(o.SecretRef) {
		var ret string
		return ret
	}
	return *o.SecretRef
}

// GetSecretRefOk returns a tuple with the SecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetSecretRefOk() (*string, bool) {
	if o == nil || IsNil(o.SecretRef) {
		return nil, false
	}
	return o.SecretRef, true
}

// HasSecretRef returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasSecretRef() bool {
	if o != nil && !IsNil(o.SecretRef) {
		return true
	}

	return false
}

// SetSecretRef gets a reference to the given string and assigns it to the SecretRef field.
func (o *PartnerSftpConfig) SetSecretRef(v string) {
	o.SecretRef = &v
}

// GetRemoteDir returns the RemoteDir field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetRemoteDir() string {
	if o == nil || IsNil(o.RemoteDir) {
		var ret string
		return ret
	}
	return *o.RemoteDir
}

// GetRemoteDirOk returns a tuple with the RemoteDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetRemoteDirOk() (*string, bool) {
	if o == nil || IsNil(o.RemoteDir) {
		return nil, false
	}
	return o.RemoteDir, true
}

// HasRemoteDir returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasRemoteDir() bool {
	if o != nil && !IsNil(o.RemoteDir) {
		return true
	}

	return false
}

// SetRemoteDir gets a reference to the given string and assigns it to the RemoteDir field.
func (o *PartnerSftpConfig) SetRemoteDir(v string) {
	o.RemoteDir = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *PartnerSftpConfig) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetInboundDir returns the InboundDir field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetInboundDir() string {
	if o == nil || IsNil(o.InboundDir) {
		var ret string
		return ret
	}
	return *o.InboundDir
}

// GetInboundDirOk returns a tuple with the InboundDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetInboundDirOk() (*string, bool) {
	if o == nil || IsNil(o.InboundDir) {
		return nil, false
	}
	return o.InboundDir, true
}

// HasInboundDir returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasInboundDir() bool {
	if o != nil && !IsNil(o.InboundDir) {
		return true
	}

	return false
}

// SetInboundDir gets a reference to the given string and assigns it to the InboundDir field.
func (o *PartnerSftpConfig) SetInboundDir(v string) {
	o.InboundDir = &v
}

// GetOutboundDir returns the OutboundDir field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetOutboundDir() string {
	if o == nil || IsNil(o.OutboundDir) {
		var ret string
		return ret
	}
	return *o.OutboundDir
}

// GetOutboundDirOk returns a tuple with the OutboundDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetOutboundDirOk() (*string, bool) {
	if o == nil || IsNil(o.OutboundDir) {
		return nil, false
	}
	return o.OutboundDir, true
}

// HasOutboundDir returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasOutboundDir() bool {
	if o != nil && !IsNil(o.OutboundDir) {
		return true
	}

	return false
}

// SetOutboundDir gets a reference to the given string and assigns it to the OutboundDir field.
func (o *PartnerSftpConfig) SetOutboundDir(v string) {
	o.OutboundDir = &v
}

// GetArchiveDir returns the ArchiveDir field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetArchiveDir() string {
	if o == nil || IsNil(o.ArchiveDir) {
		var ret string
		return ret
	}
	return *o.ArchiveDir
}

// GetArchiveDirOk returns a tuple with the ArchiveDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetArchiveDirOk() (*string, bool) {
	if o == nil || IsNil(o.ArchiveDir) {
		return nil, false
	}
	return o.ArchiveDir, true
}

// HasArchiveDir returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasArchiveDir() bool {
	if o != nil && !IsNil(o.ArchiveDir) {
		return true
	}

	return false
}

// SetArchiveDir gets a reference to the given string and assigns it to the ArchiveDir field.
func (o *PartnerSftpConfig) SetArchiveDir(v string) {
	o.ArchiveDir = &v
}

// GetEdiEnabled returns the EdiEnabled field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetEdiEnabled() bool {
	if o == nil || IsNil(o.EdiEnabled) {
		var ret bool
		return ret
	}
	return *o.EdiEnabled
}

// GetEdiEnabledOk returns a tuple with the EdiEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetEdiEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.EdiEnabled) {
		return nil, false
	}
	return o.EdiEnabled, true
}

// HasEdiEnabled returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasEdiEnabled() bool {
	if o != nil && !IsNil(o.EdiEnabled) {
		return true
	}

	return false
}

// SetEdiEnabled gets a reference to the given bool and assigns it to the EdiEnabled field.
func (o *PartnerSftpConfig) SetEdiEnabled(v bool) {
	o.EdiEnabled = &v
}

// GetHostKeySha256 returns the HostKeySha256 field value if set, zero value otherwise.
func (o *PartnerSftpConfig) GetHostKeySha256() string {
	if o == nil || IsNil(o.HostKeySha256) {
		var ret string
		return ret
	}
	return *o.HostKeySha256
}

// GetHostKeySha256Ok returns a tuple with the HostKeySha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerSftpConfig) GetHostKeySha256Ok() (*string, bool) {
	if o == nil || IsNil(o.HostKeySha256) {
		return nil, false
	}
	return o.HostKeySha256, true
}

// HasHostKeySha256 returns a boolean if a field has been set.
func (o *PartnerSftpConfig) HasHostKeySha256() bool {
	if o != nil && !IsNil(o.HostKeySha256) {
		return true
	}

	return false
}

// SetHostKeySha256 gets a reference to the given string and assigns it to the HostKeySha256 field.
func (o *PartnerSftpConfig) SetHostKeySha256(v string) {
	o.HostKeySha256 = &v
}

func (o PartnerSftpConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerSftpConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Configured) {
		toSerialize["configured"] = o.Configured
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.SecretRef) {
		toSerialize["secret_ref"] = o.SecretRef
	}
	if !IsNil(o.RemoteDir) {
		toSerialize["remote_dir"] = o.RemoteDir
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.InboundDir) {
		toSerialize["inbound_dir"] = o.InboundDir
	}
	if !IsNil(o.OutboundDir) {
		toSerialize["outbound_dir"] = o.OutboundDir
	}
	if !IsNil(o.ArchiveDir) {
		toSerialize["archive_dir"] = o.ArchiveDir
	}
	if !IsNil(o.EdiEnabled) {
		toSerialize["edi_enabled"] = o.EdiEnabled
	}
	if !IsNil(o.HostKeySha256) {
		toSerialize["host_key_sha256"] = o.HostKeySha256
	}
	return toSerialize, nil
}

type NullablePartnerSftpConfig struct {
	value *PartnerSftpConfig
	isSet bool
}

func (v NullablePartnerSftpConfig) Get() *PartnerSftpConfig {
	return v.value
}

func (v *NullablePartnerSftpConfig) Set(val *PartnerSftpConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerSftpConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerSftpConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerSftpConfig(val *PartnerSftpConfig) *NullablePartnerSftpConfig {
	return &NullablePartnerSftpConfig{value: val, isSet: true}
}

func (v NullablePartnerSftpConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerSftpConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


