/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerStockUpsertRequestItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerStockUpsertRequestItemsInner{}

// PartnerStockUpsertRequestItemsInner struct for PartnerStockUpsertRequestItemsInner
type PartnerStockUpsertRequestItemsInner struct {
	ExternalId string `json:"external_id"`
	WarehouseId string `json:"warehouse_id"`
	QuantityOnHand int32 `json:"quantity_on_hand"`
	ReorderThreshold *int32 `json:"reorder_threshold,omitempty"`
}

type _PartnerStockUpsertRequestItemsInner PartnerStockUpsertRequestItemsInner

// NewPartnerStockUpsertRequestItemsInner instantiates a new PartnerStockUpsertRequestItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerStockUpsertRequestItemsInner(externalId string, warehouseId string, quantityOnHand int32) *PartnerStockUpsertRequestItemsInner {
	this := PartnerStockUpsertRequestItemsInner{}
	this.ExternalId = externalId
	this.WarehouseId = warehouseId
	this.QuantityOnHand = quantityOnHand
	return &this
}

// NewPartnerStockUpsertRequestItemsInnerWithDefaults instantiates a new PartnerStockUpsertRequestItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerStockUpsertRequestItemsInnerWithDefaults() *PartnerStockUpsertRequestItemsInner {
	this := PartnerStockUpsertRequestItemsInner{}
	return &this
}

// GetExternalId returns the ExternalId field value
func (o *PartnerStockUpsertRequestItemsInner) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *PartnerStockUpsertRequestItemsInner) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *PartnerStockUpsertRequestItemsInner) SetExternalId(v string) {
	o.ExternalId = v
}

// GetWarehouseId returns the WarehouseId field value
func (o *PartnerStockUpsertRequestItemsInner) GetWarehouseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WarehouseId
}

// GetWarehouseIdOk returns a tuple with the WarehouseId field value
// and a boolean to check if the value has been set.
func (o *PartnerStockUpsertRequestItemsInner) GetWarehouseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WarehouseId, true
}

// SetWarehouseId sets field value
func (o *PartnerStockUpsertRequestItemsInner) SetWarehouseId(v string) {
	o.WarehouseId = v
}

// GetQuantityOnHand returns the QuantityOnHand field value
func (o *PartnerStockUpsertRequestItemsInner) GetQuantityOnHand() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.QuantityOnHand
}

// GetQuantityOnHandOk returns a tuple with the QuantityOnHand field value
// and a boolean to check if the value has been set.
func (o *PartnerStockUpsertRequestItemsInner) GetQuantityOnHandOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuantityOnHand, true
}

// SetQuantityOnHand sets field value
func (o *PartnerStockUpsertRequestItemsInner) SetQuantityOnHand(v int32) {
	o.QuantityOnHand = v
}

// GetReorderThreshold returns the ReorderThreshold field value if set, zero value otherwise.
func (o *PartnerStockUpsertRequestItemsInner) GetReorderThreshold() int32 {
	if o == nil || IsNil(o.ReorderThreshold) {
		var ret int32
		return ret
	}
	return *o.ReorderThreshold
}

// GetReorderThresholdOk returns a tuple with the ReorderThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerStockUpsertRequestItemsInner) GetReorderThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.ReorderThreshold) {
		return nil, false
	}
	return o.ReorderThreshold, true
}

// HasReorderThreshold returns a boolean if a field has been set.
func (o *PartnerStockUpsertRequestItemsInner) HasReorderThreshold() bool {
	if o != nil && !IsNil(o.ReorderThreshold) {
		return true
	}

	return false
}

// SetReorderThreshold gets a reference to the given int32 and assigns it to the ReorderThreshold field.
func (o *PartnerStockUpsertRequestItemsInner) SetReorderThreshold(v int32) {
	o.ReorderThreshold = &v
}

func (o PartnerStockUpsertRequestItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerStockUpsertRequestItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["external_id"] = o.ExternalId
	toSerialize["warehouse_id"] = o.WarehouseId
	toSerialize["quantity_on_hand"] = o.QuantityOnHand
	if !IsNil(o.ReorderThreshold) {
		toSerialize["reorder_threshold"] = o.ReorderThreshold
	}
	return toSerialize, nil
}

func (o *PartnerStockUpsertRequestItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"external_id",
		"warehouse_id",
		"quantity_on_hand",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerStockUpsertRequestItemsInner := _PartnerStockUpsertRequestItemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerStockUpsertRequestItemsInner)

	if err != nil {
		return err
	}

	*o = PartnerStockUpsertRequestItemsInner(varPartnerStockUpsertRequestItemsInner)

	return err
}

type NullablePartnerStockUpsertRequestItemsInner struct {
	value *PartnerStockUpsertRequestItemsInner
	isSet bool
}

func (v NullablePartnerStockUpsertRequestItemsInner) Get() *PartnerStockUpsertRequestItemsInner {
	return v.value
}

func (v *NullablePartnerStockUpsertRequestItemsInner) Set(val *PartnerStockUpsertRequestItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerStockUpsertRequestItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerStockUpsertRequestItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerStockUpsertRequestItemsInner(val *PartnerStockUpsertRequestItemsInner) *NullablePartnerStockUpsertRequestItemsInner {
	return &NullablePartnerStockUpsertRequestItemsInner{value: val, isSet: true}
}

func (v NullablePartnerStockUpsertRequestItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerStockUpsertRequestItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


