/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerProductUpsertRequestItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerProductUpsertRequestItemsInner{}

// PartnerProductUpsertRequestItemsInner struct for PartnerProductUpsertRequestItemsInner
type PartnerProductUpsertRequestItemsInner struct {
	ExternalId string `json:"external_id"`
	Name string `json:"name"`
	CategoryId *string `json:"category_id,omitempty"`
	PriceMinor *int32 `json:"price_minor,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Unit *string `json:"unit,omitempty"`
	Barcode *string `json:"barcode,omitempty"`
	Description *string `json:"description,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	HandlingClass *string `json:"handling_class,omitempty"`
}

type _PartnerProductUpsertRequestItemsInner PartnerProductUpsertRequestItemsInner

// NewPartnerProductUpsertRequestItemsInner instantiates a new PartnerProductUpsertRequestItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerProductUpsertRequestItemsInner(externalId string, name string) *PartnerProductUpsertRequestItemsInner {
	this := PartnerProductUpsertRequestItemsInner{}
	this.ExternalId = externalId
	this.Name = name
	return &this
}

// NewPartnerProductUpsertRequestItemsInnerWithDefaults instantiates a new PartnerProductUpsertRequestItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerProductUpsertRequestItemsInnerWithDefaults() *PartnerProductUpsertRequestItemsInner {
	this := PartnerProductUpsertRequestItemsInner{}
	return &this
}

// GetExternalId returns the ExternalId field value
func (o *PartnerProductUpsertRequestItemsInner) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *PartnerProductUpsertRequestItemsInner) SetExternalId(v string) {
	o.ExternalId = v
}

// GetName returns the Name field value
func (o *PartnerProductUpsertRequestItemsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PartnerProductUpsertRequestItemsInner) SetName(v string) {
	o.Name = v
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *PartnerProductUpsertRequestItemsInner) GetCategoryId() string {
	if o == nil || IsNil(o.CategoryId) {
		var ret string
		return ret
	}
	return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetCategoryIdOk() (*string, bool) {
	if o == nil || IsNil(o.CategoryId) {
		return nil, false
	}
	return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *PartnerProductUpsertRequestItemsInner) HasCategoryId() bool {
	if o != nil && !IsNil(o.CategoryId) {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given string and assigns it to the CategoryId field.
func (o *PartnerProductUpsertRequestItemsInner) SetCategoryId(v string) {
	o.CategoryId = &v
}

// GetPriceMinor returns the PriceMinor field value if set, zero value otherwise.
func (o *PartnerProductUpsertRequestItemsInner) GetPriceMinor() int32 {
	if o == nil || IsNil(o.PriceMinor) {
		var ret int32
		return ret
	}
	return *o.PriceMinor
}

// GetPriceMinorOk returns a tuple with the PriceMinor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetPriceMinorOk() (*int32, bool) {
	if o == nil || IsNil(o.PriceMinor) {
		return nil, false
	}
	return o.PriceMinor, true
}

// HasPriceMinor returns a boolean if a field has been set.
func (o *PartnerProductUpsertRequestItemsInner) HasPriceMinor() bool {
	if o != nil && !IsNil(o.PriceMinor) {
		return true
	}

	return false
}

// SetPriceMinor gets a reference to the given int32 and assigns it to the PriceMinor field.
func (o *PartnerProductUpsertRequestItemsInner) SetPriceMinor(v int32) {
	o.PriceMinor = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *PartnerProductUpsertRequestItemsInner) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *PartnerProductUpsertRequestItemsInner) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *PartnerProductUpsertRequestItemsInner) SetCurrency(v string) {
	o.Currency = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *PartnerProductUpsertRequestItemsInner) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *PartnerProductUpsertRequestItemsInner) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *PartnerProductUpsertRequestItemsInner) SetUnit(v string) {
	o.Unit = &v
}

// GetBarcode returns the Barcode field value if set, zero value otherwise.
func (o *PartnerProductUpsertRequestItemsInner) GetBarcode() string {
	if o == nil || IsNil(o.Barcode) {
		var ret string
		return ret
	}
	return *o.Barcode
}

// GetBarcodeOk returns a tuple with the Barcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetBarcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Barcode) {
		return nil, false
	}
	return o.Barcode, true
}

// HasBarcode returns a boolean if a field has been set.
func (o *PartnerProductUpsertRequestItemsInner) HasBarcode() bool {
	if o != nil && !IsNil(o.Barcode) {
		return true
	}

	return false
}

// SetBarcode gets a reference to the given string and assigns it to the Barcode field.
func (o *PartnerProductUpsertRequestItemsInner) SetBarcode(v string) {
	o.Barcode = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PartnerProductUpsertRequestItemsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PartnerProductUpsertRequestItemsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PartnerProductUpsertRequestItemsInner) SetDescription(v string) {
	o.Description = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *PartnerProductUpsertRequestItemsInner) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *PartnerProductUpsertRequestItemsInner) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *PartnerProductUpsertRequestItemsInner) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *PartnerProductUpsertRequestItemsInner) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *PartnerProductUpsertRequestItemsInner) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *PartnerProductUpsertRequestItemsInner) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetHandlingClass returns the HandlingClass field value if set, zero value otherwise.
func (o *PartnerProductUpsertRequestItemsInner) GetHandlingClass() string {
	if o == nil || IsNil(o.HandlingClass) {
		var ret string
		return ret
	}
	return *o.HandlingClass
}

// GetHandlingClassOk returns a tuple with the HandlingClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequestItemsInner) GetHandlingClassOk() (*string, bool) {
	if o == nil || IsNil(o.HandlingClass) {
		return nil, false
	}
	return o.HandlingClass, true
}

// HasHandlingClass returns a boolean if a field has been set.
func (o *PartnerProductUpsertRequestItemsInner) HasHandlingClass() bool {
	if o != nil && !IsNil(o.HandlingClass) {
		return true
	}

	return false
}

// SetHandlingClass gets a reference to the given string and assigns it to the HandlingClass field.
func (o *PartnerProductUpsertRequestItemsInner) SetHandlingClass(v string) {
	o.HandlingClass = &v
}

func (o PartnerProductUpsertRequestItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerProductUpsertRequestItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["external_id"] = o.ExternalId
	toSerialize["name"] = o.Name
	if !IsNil(o.CategoryId) {
		toSerialize["category_id"] = o.CategoryId
	}
	if !IsNil(o.PriceMinor) {
		toSerialize["price_minor"] = o.PriceMinor
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	if !IsNil(o.Barcode) {
		toSerialize["barcode"] = o.Barcode
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["image_url"] = o.ImageUrl
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.HandlingClass) {
		toSerialize["handling_class"] = o.HandlingClass
	}
	return toSerialize, nil
}

func (o *PartnerProductUpsertRequestItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"external_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerProductUpsertRequestItemsInner := _PartnerProductUpsertRequestItemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerProductUpsertRequestItemsInner)

	if err != nil {
		return err
	}

	*o = PartnerProductUpsertRequestItemsInner(varPartnerProductUpsertRequestItemsInner)

	return err
}

type NullablePartnerProductUpsertRequestItemsInner struct {
	value *PartnerProductUpsertRequestItemsInner
	isSet bool
}

func (v NullablePartnerProductUpsertRequestItemsInner) Get() *PartnerProductUpsertRequestItemsInner {
	return v.value
}

func (v *NullablePartnerProductUpsertRequestItemsInner) Set(val *PartnerProductUpsertRequestItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerProductUpsertRequestItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerProductUpsertRequestItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerProductUpsertRequestItemsInner(val *PartnerProductUpsertRequestItemsInner) *NullablePartnerProductUpsertRequestItemsInner {
	return &NullablePartnerProductUpsertRequestItemsInner{value: val, isSet: true}
}

func (v NullablePartnerProductUpsertRequestItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerProductUpsertRequestItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


