/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerCreateWebhookRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerCreateWebhookRequest{}

// PartnerCreateWebhookRequest struct for PartnerCreateWebhookRequest
type PartnerCreateWebhookRequest struct {
	Url string `json:"url"`
	EventTypes []string `json:"event_types,omitempty"`
}

type _PartnerCreateWebhookRequest PartnerCreateWebhookRequest

// NewPartnerCreateWebhookRequest instantiates a new PartnerCreateWebhookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerCreateWebhookRequest(url string) *PartnerCreateWebhookRequest {
	this := PartnerCreateWebhookRequest{}
	this.Url = url
	return &this
}

// NewPartnerCreateWebhookRequestWithDefaults instantiates a new PartnerCreateWebhookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerCreateWebhookRequestWithDefaults() *PartnerCreateWebhookRequest {
	this := PartnerCreateWebhookRequest{}
	return &this
}

// GetUrl returns the Url field value
func (o *PartnerCreateWebhookRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *PartnerCreateWebhookRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *PartnerCreateWebhookRequest) SetUrl(v string) {
	o.Url = v
}

// GetEventTypes returns the EventTypes field value if set, zero value otherwise.
func (o *PartnerCreateWebhookRequest) GetEventTypes() []string {
	if o == nil || IsNil(o.EventTypes) {
		var ret []string
		return ret
	}
	return o.EventTypes
}

// GetEventTypesOk returns a tuple with the EventTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateWebhookRequest) GetEventTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.EventTypes) {
		return nil, false
	}
	return o.EventTypes, true
}

// HasEventTypes returns a boolean if a field has been set.
func (o *PartnerCreateWebhookRequest) HasEventTypes() bool {
	if o != nil && !IsNil(o.EventTypes) {
		return true
	}

	return false
}

// SetEventTypes gets a reference to the given []string and assigns it to the EventTypes field.
func (o *PartnerCreateWebhookRequest) SetEventTypes(v []string) {
	o.EventTypes = v
}

func (o PartnerCreateWebhookRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerCreateWebhookRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if !IsNil(o.EventTypes) {
		toSerialize["event_types"] = o.EventTypes
	}
	return toSerialize, nil
}

func (o *PartnerCreateWebhookRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerCreateWebhookRequest := _PartnerCreateWebhookRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerCreateWebhookRequest)

	if err != nil {
		return err
	}

	*o = PartnerCreateWebhookRequest(varPartnerCreateWebhookRequest)

	return err
}

type NullablePartnerCreateWebhookRequest struct {
	value *PartnerCreateWebhookRequest
	isSet bool
}

func (v NullablePartnerCreateWebhookRequest) Get() *PartnerCreateWebhookRequest {
	return v.value
}

func (v *NullablePartnerCreateWebhookRequest) Set(val *PartnerCreateWebhookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerCreateWebhookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerCreateWebhookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerCreateWebhookRequest(val *PartnerCreateWebhookRequest) *NullablePartnerCreateWebhookRequest {
	return &NullablePartnerCreateWebhookRequest{value: val, isSet: true}
}

func (v NullablePartnerCreateWebhookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerCreateWebhookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


