/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PartnerPOSDemandFeedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerPOSDemandFeedRequest{}

// PartnerPOSDemandFeedRequest struct for PartnerPOSDemandFeedRequest
type PartnerPOSDemandFeedRequest struct {
	StoreId *string `json:"store_id,omitempty"`
	ObservedAt *time.Time `json:"observed_at,omitempty"`
	Lines []PartnerPOSDemandFeedRequestLinesInner `json:"lines"`
}

type _PartnerPOSDemandFeedRequest PartnerPOSDemandFeedRequest

// NewPartnerPOSDemandFeedRequest instantiates a new PartnerPOSDemandFeedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerPOSDemandFeedRequest(lines []PartnerPOSDemandFeedRequestLinesInner) *PartnerPOSDemandFeedRequest {
	this := PartnerPOSDemandFeedRequest{}
	this.Lines = lines
	return &this
}

// NewPartnerPOSDemandFeedRequestWithDefaults instantiates a new PartnerPOSDemandFeedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerPOSDemandFeedRequestWithDefaults() *PartnerPOSDemandFeedRequest {
	this := PartnerPOSDemandFeedRequest{}
	return &this
}

// GetStoreId returns the StoreId field value if set, zero value otherwise.
func (o *PartnerPOSDemandFeedRequest) GetStoreId() string {
	if o == nil || IsNil(o.StoreId) {
		var ret string
		return ret
	}
	return *o.StoreId
}

// GetStoreIdOk returns a tuple with the StoreId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerPOSDemandFeedRequest) GetStoreIdOk() (*string, bool) {
	if o == nil || IsNil(o.StoreId) {
		return nil, false
	}
	return o.StoreId, true
}

// HasStoreId returns a boolean if a field has been set.
func (o *PartnerPOSDemandFeedRequest) HasStoreId() bool {
	if o != nil && !IsNil(o.StoreId) {
		return true
	}

	return false
}

// SetStoreId gets a reference to the given string and assigns it to the StoreId field.
func (o *PartnerPOSDemandFeedRequest) SetStoreId(v string) {
	o.StoreId = &v
}

// GetObservedAt returns the ObservedAt field value if set, zero value otherwise.
func (o *PartnerPOSDemandFeedRequest) GetObservedAt() time.Time {
	if o == nil || IsNil(o.ObservedAt) {
		var ret time.Time
		return ret
	}
	return *o.ObservedAt
}

// GetObservedAtOk returns a tuple with the ObservedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerPOSDemandFeedRequest) GetObservedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ObservedAt) {
		return nil, false
	}
	return o.ObservedAt, true
}

// HasObservedAt returns a boolean if a field has been set.
func (o *PartnerPOSDemandFeedRequest) HasObservedAt() bool {
	if o != nil && !IsNil(o.ObservedAt) {
		return true
	}

	return false
}

// SetObservedAt gets a reference to the given time.Time and assigns it to the ObservedAt field.
func (o *PartnerPOSDemandFeedRequest) SetObservedAt(v time.Time) {
	o.ObservedAt = &v
}

// GetLines returns the Lines field value
func (o *PartnerPOSDemandFeedRequest) GetLines() []PartnerPOSDemandFeedRequestLinesInner {
	if o == nil {
		var ret []PartnerPOSDemandFeedRequestLinesInner
		return ret
	}

	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value
// and a boolean to check if the value has been set.
func (o *PartnerPOSDemandFeedRequest) GetLinesOk() ([]PartnerPOSDemandFeedRequestLinesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lines, true
}

// SetLines sets field value
func (o *PartnerPOSDemandFeedRequest) SetLines(v []PartnerPOSDemandFeedRequestLinesInner) {
	o.Lines = v
}

func (o PartnerPOSDemandFeedRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerPOSDemandFeedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StoreId) {
		toSerialize["store_id"] = o.StoreId
	}
	if !IsNil(o.ObservedAt) {
		toSerialize["observed_at"] = o.ObservedAt
	}
	toSerialize["lines"] = o.Lines
	return toSerialize, nil
}

func (o *PartnerPOSDemandFeedRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lines",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerPOSDemandFeedRequest := _PartnerPOSDemandFeedRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerPOSDemandFeedRequest)

	if err != nil {
		return err
	}

	*o = PartnerPOSDemandFeedRequest(varPartnerPOSDemandFeedRequest)

	return err
}

type NullablePartnerPOSDemandFeedRequest struct {
	value *PartnerPOSDemandFeedRequest
	isSet bool
}

func (v NullablePartnerPOSDemandFeedRequest) Get() *PartnerPOSDemandFeedRequest {
	return v.value
}

func (v *NullablePartnerPOSDemandFeedRequest) Set(val *PartnerPOSDemandFeedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerPOSDemandFeedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerPOSDemandFeedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerPOSDemandFeedRequest(val *PartnerPOSDemandFeedRequest) *NullablePartnerPOSDemandFeedRequest {
	return &NullablePartnerPOSDemandFeedRequest{value: val, isSet: true}
}

func (v NullablePartnerPOSDemandFeedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerPOSDemandFeedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


