/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerCreateOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerCreateOrderRequest{}

// PartnerCreateOrderRequest struct for PartnerCreateOrderRequest
type PartnerCreateOrderRequest struct {
	// Required for RETAILER keys
	SupplierId *string `json:"supplier_id,omitempty"`
	// Required for SUPPLIER keys
	RetailerId *string `json:"retailer_id,omitempty"`
	LineItems []PartnerCreateOrderRequestLineItemsInner `json:"line_items"`
	H3Cell *string `json:"h3_cell,omitempty"`
	Lat float32 `json:"lat"`
	Lng float32 `json:"lng"`
}

type _PartnerCreateOrderRequest PartnerCreateOrderRequest

// NewPartnerCreateOrderRequest instantiates a new PartnerCreateOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerCreateOrderRequest(lineItems []PartnerCreateOrderRequestLineItemsInner, lat float32, lng float32) *PartnerCreateOrderRequest {
	this := PartnerCreateOrderRequest{}
	this.LineItems = lineItems
	this.Lat = lat
	this.Lng = lng
	return &this
}

// NewPartnerCreateOrderRequestWithDefaults instantiates a new PartnerCreateOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerCreateOrderRequestWithDefaults() *PartnerCreateOrderRequest {
	this := PartnerCreateOrderRequest{}
	return &this
}

// GetSupplierId returns the SupplierId field value if set, zero value otherwise.
func (o *PartnerCreateOrderRequest) GetSupplierId() string {
	if o == nil || IsNil(o.SupplierId) {
		var ret string
		return ret
	}
	return *o.SupplierId
}

// GetSupplierIdOk returns a tuple with the SupplierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderRequest) GetSupplierIdOk() (*string, bool) {
	if o == nil || IsNil(o.SupplierId) {
		return nil, false
	}
	return o.SupplierId, true
}

// HasSupplierId returns a boolean if a field has been set.
func (o *PartnerCreateOrderRequest) HasSupplierId() bool {
	if o != nil && !IsNil(o.SupplierId) {
		return true
	}

	return false
}

// SetSupplierId gets a reference to the given string and assigns it to the SupplierId field.
func (o *PartnerCreateOrderRequest) SetSupplierId(v string) {
	o.SupplierId = &v
}

// GetRetailerId returns the RetailerId field value if set, zero value otherwise.
func (o *PartnerCreateOrderRequest) GetRetailerId() string {
	if o == nil || IsNil(o.RetailerId) {
		var ret string
		return ret
	}
	return *o.RetailerId
}

// GetRetailerIdOk returns a tuple with the RetailerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderRequest) GetRetailerIdOk() (*string, bool) {
	if o == nil || IsNil(o.RetailerId) {
		return nil, false
	}
	return o.RetailerId, true
}

// HasRetailerId returns a boolean if a field has been set.
func (o *PartnerCreateOrderRequest) HasRetailerId() bool {
	if o != nil && !IsNil(o.RetailerId) {
		return true
	}

	return false
}

// SetRetailerId gets a reference to the given string and assigns it to the RetailerId field.
func (o *PartnerCreateOrderRequest) SetRetailerId(v string) {
	o.RetailerId = &v
}

// GetLineItems returns the LineItems field value
func (o *PartnerCreateOrderRequest) GetLineItems() []PartnerCreateOrderRequestLineItemsInner {
	if o == nil {
		var ret []PartnerCreateOrderRequestLineItemsInner
		return ret
	}

	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderRequest) GetLineItemsOk() ([]PartnerCreateOrderRequestLineItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.LineItems, true
}

// SetLineItems sets field value
func (o *PartnerCreateOrderRequest) SetLineItems(v []PartnerCreateOrderRequestLineItemsInner) {
	o.LineItems = v
}

// GetH3Cell returns the H3Cell field value if set, zero value otherwise.
func (o *PartnerCreateOrderRequest) GetH3Cell() string {
	if o == nil || IsNil(o.H3Cell) {
		var ret string
		return ret
	}
	return *o.H3Cell
}

// GetH3CellOk returns a tuple with the H3Cell field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderRequest) GetH3CellOk() (*string, bool) {
	if o == nil || IsNil(o.H3Cell) {
		return nil, false
	}
	return o.H3Cell, true
}

// HasH3Cell returns a boolean if a field has been set.
func (o *PartnerCreateOrderRequest) HasH3Cell() bool {
	if o != nil && !IsNil(o.H3Cell) {
		return true
	}

	return false
}

// SetH3Cell gets a reference to the given string and assigns it to the H3Cell field.
func (o *PartnerCreateOrderRequest) SetH3Cell(v string) {
	o.H3Cell = &v
}

// GetLat returns the Lat field value
func (o *PartnerCreateOrderRequest) GetLat() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Lat
}

// GetLatOk returns a tuple with the Lat field value
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderRequest) GetLatOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lat, true
}

// SetLat sets field value
func (o *PartnerCreateOrderRequest) SetLat(v float32) {
	o.Lat = v
}

// GetLng returns the Lng field value
func (o *PartnerCreateOrderRequest) GetLng() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Lng
}

// GetLngOk returns a tuple with the Lng field value
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderRequest) GetLngOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lng, true
}

// SetLng sets field value
func (o *PartnerCreateOrderRequest) SetLng(v float32) {
	o.Lng = v
}

func (o PartnerCreateOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerCreateOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SupplierId) {
		toSerialize["supplier_id"] = o.SupplierId
	}
	if !IsNil(o.RetailerId) {
		toSerialize["retailer_id"] = o.RetailerId
	}
	toSerialize["line_items"] = o.LineItems
	if !IsNil(o.H3Cell) {
		toSerialize["h3_cell"] = o.H3Cell
	}
	toSerialize["lat"] = o.Lat
	toSerialize["lng"] = o.Lng
	return toSerialize, nil
}

func (o *PartnerCreateOrderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"line_items",
		"lat",
		"lng",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerCreateOrderRequest := _PartnerCreateOrderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerCreateOrderRequest)

	if err != nil {
		return err
	}

	*o = PartnerCreateOrderRequest(varPartnerCreateOrderRequest)

	return err
}

type NullablePartnerCreateOrderRequest struct {
	value *PartnerCreateOrderRequest
	isSet bool
}

func (v NullablePartnerCreateOrderRequest) Get() *PartnerCreateOrderRequest {
	return v.value
}

func (v *NullablePartnerCreateOrderRequest) Set(val *PartnerCreateOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerCreateOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerCreateOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerCreateOrderRequest(val *PartnerCreateOrderRequest) *NullablePartnerCreateOrderRequest {
	return &NullablePartnerCreateOrderRequest{value: val, isSet: true}
}

func (v NullablePartnerCreateOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerCreateOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


