/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
)

// checks if the PartnerCreateOrderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerCreateOrderResponse{}

// PartnerCreateOrderResponse struct for PartnerCreateOrderResponse
type PartnerCreateOrderResponse struct {
	OrderId *string `json:"order_id,omitempty"`
	Status *string `json:"status,omitempty"`
	TotalMinor *int32 `json:"total_minor,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

// NewPartnerCreateOrderResponse instantiates a new PartnerCreateOrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerCreateOrderResponse() *PartnerCreateOrderResponse {
	this := PartnerCreateOrderResponse{}
	return &this
}

// NewPartnerCreateOrderResponseWithDefaults instantiates a new PartnerCreateOrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerCreateOrderResponseWithDefaults() *PartnerCreateOrderResponse {
	this := PartnerCreateOrderResponse{}
	return &this
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *PartnerCreateOrderResponse) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderResponse) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *PartnerCreateOrderResponse) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *PartnerCreateOrderResponse) SetOrderId(v string) {
	o.OrderId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PartnerCreateOrderResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PartnerCreateOrderResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PartnerCreateOrderResponse) SetStatus(v string) {
	o.Status = &v
}

// GetTotalMinor returns the TotalMinor field value if set, zero value otherwise.
func (o *PartnerCreateOrderResponse) GetTotalMinor() int32 {
	if o == nil || IsNil(o.TotalMinor) {
		var ret int32
		return ret
	}
	return *o.TotalMinor
}

// GetTotalMinorOk returns a tuple with the TotalMinor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderResponse) GetTotalMinorOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalMinor) {
		return nil, false
	}
	return o.TotalMinor, true
}

// HasTotalMinor returns a boolean if a field has been set.
func (o *PartnerCreateOrderResponse) HasTotalMinor() bool {
	if o != nil && !IsNil(o.TotalMinor) {
		return true
	}

	return false
}

// SetTotalMinor gets a reference to the given int32 and assigns it to the TotalMinor field.
func (o *PartnerCreateOrderResponse) SetTotalMinor(v int32) {
	o.TotalMinor = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *PartnerCreateOrderResponse) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateOrderResponse) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *PartnerCreateOrderResponse) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *PartnerCreateOrderResponse) SetCurrency(v string) {
	o.Currency = &v
}

func (o PartnerCreateOrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerCreateOrderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrderId) {
		toSerialize["order_id"] = o.OrderId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TotalMinor) {
		toSerialize["total_minor"] = o.TotalMinor
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullablePartnerCreateOrderResponse struct {
	value *PartnerCreateOrderResponse
	isSet bool
}

func (v NullablePartnerCreateOrderResponse) Get() *PartnerCreateOrderResponse {
	return v.value
}

func (v *NullablePartnerCreateOrderResponse) Set(val *PartnerCreateOrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerCreateOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerCreateOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerCreateOrderResponse(val *PartnerCreateOrderResponse) *NullablePartnerCreateOrderResponse {
	return &NullablePartnerCreateOrderResponse{value: val, isSet: true}
}

func (v NullablePartnerCreateOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerCreateOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


