/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
)

// checks if the PartnerListWebhooks200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerListWebhooks200Response{}

// PartnerListWebhooks200Response struct for PartnerListWebhooks200Response
type PartnerListWebhooks200Response struct {
	Subscriptions []PartnerWebhookSubscription `json:"subscriptions,omitempty"`
}

// NewPartnerListWebhooks200Response instantiates a new PartnerListWebhooks200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerListWebhooks200Response() *PartnerListWebhooks200Response {
	this := PartnerListWebhooks200Response{}
	return &this
}

// NewPartnerListWebhooks200ResponseWithDefaults instantiates a new PartnerListWebhooks200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerListWebhooks200ResponseWithDefaults() *PartnerListWebhooks200Response {
	this := PartnerListWebhooks200Response{}
	return &this
}

// GetSubscriptions returns the Subscriptions field value if set, zero value otherwise.
func (o *PartnerListWebhooks200Response) GetSubscriptions() []PartnerWebhookSubscription {
	if o == nil || IsNil(o.Subscriptions) {
		var ret []PartnerWebhookSubscription
		return ret
	}
	return o.Subscriptions
}

// GetSubscriptionsOk returns a tuple with the Subscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerListWebhooks200Response) GetSubscriptionsOk() ([]PartnerWebhookSubscription, bool) {
	if o == nil || IsNil(o.Subscriptions) {
		return nil, false
	}
	return o.Subscriptions, true
}

// HasSubscriptions returns a boolean if a field has been set.
func (o *PartnerListWebhooks200Response) HasSubscriptions() bool {
	if o != nil && !IsNil(o.Subscriptions) {
		return true
	}

	return false
}

// SetSubscriptions gets a reference to the given []PartnerWebhookSubscription and assigns it to the Subscriptions field.
func (o *PartnerListWebhooks200Response) SetSubscriptions(v []PartnerWebhookSubscription) {
	o.Subscriptions = v
}

func (o PartnerListWebhooks200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerListWebhooks200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subscriptions) {
		toSerialize["subscriptions"] = o.Subscriptions
	}
	return toSerialize, nil
}

type NullablePartnerListWebhooks200Response struct {
	value *PartnerListWebhooks200Response
	isSet bool
}

func (v NullablePartnerListWebhooks200Response) Get() *PartnerListWebhooks200Response {
	return v.value
}

func (v *NullablePartnerListWebhooks200Response) Set(val *PartnerListWebhooks200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerListWebhooks200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerListWebhooks200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerListWebhooks200Response(val *PartnerListWebhooks200Response) *NullablePartnerListWebhooks200Response {
	return &NullablePartnerListWebhooks200Response{value: val, isSet: true}
}

func (v NullablePartnerListWebhooks200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerListWebhooks200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


