/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerProductUpsertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerProductUpsertRequest{}

// PartnerProductUpsertRequest struct for PartnerProductUpsertRequest
type PartnerProductUpsertRequest struct {
	Items []PartnerProductUpsertRequestItemsInner `json:"items"`
}

type _PartnerProductUpsertRequest PartnerProductUpsertRequest

// NewPartnerProductUpsertRequest instantiates a new PartnerProductUpsertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerProductUpsertRequest(items []PartnerProductUpsertRequestItemsInner) *PartnerProductUpsertRequest {
	this := PartnerProductUpsertRequest{}
	this.Items = items
	return &this
}

// NewPartnerProductUpsertRequestWithDefaults instantiates a new PartnerProductUpsertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerProductUpsertRequestWithDefaults() *PartnerProductUpsertRequest {
	this := PartnerProductUpsertRequest{}
	return &this
}

// GetItems returns the Items field value
func (o *PartnerProductUpsertRequest) GetItems() []PartnerProductUpsertRequestItemsInner {
	if o == nil {
		var ret []PartnerProductUpsertRequestItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PartnerProductUpsertRequest) GetItemsOk() ([]PartnerProductUpsertRequestItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PartnerProductUpsertRequest) SetItems(v []PartnerProductUpsertRequestItemsInner) {
	o.Items = v
}

func (o PartnerProductUpsertRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerProductUpsertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *PartnerProductUpsertRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerProductUpsertRequest := _PartnerProductUpsertRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerProductUpsertRequest)

	if err != nil {
		return err
	}

	*o = PartnerProductUpsertRequest(varPartnerProductUpsertRequest)

	return err
}

type NullablePartnerProductUpsertRequest struct {
	value *PartnerProductUpsertRequest
	isSet bool
}

func (v NullablePartnerProductUpsertRequest) Get() *PartnerProductUpsertRequest {
	return v.value
}

func (v *NullablePartnerProductUpsertRequest) Set(val *PartnerProductUpsertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerProductUpsertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerProductUpsertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerProductUpsertRequest(val *PartnerProductUpsertRequest) *NullablePartnerProductUpsertRequest {
	return &NullablePartnerProductUpsertRequest{value: val, isSet: true}
}

func (v NullablePartnerProductUpsertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerProductUpsertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


