/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
)

// checks if the PartnerListEdiDocuments200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerListEdiDocuments200Response{}

// PartnerListEdiDocuments200Response struct for PartnerListEdiDocuments200Response
type PartnerListEdiDocuments200Response struct {
	Documents []PartnerEdiDocument `json:"documents,omitempty"`
}

// NewPartnerListEdiDocuments200Response instantiates a new PartnerListEdiDocuments200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerListEdiDocuments200Response() *PartnerListEdiDocuments200Response {
	this := PartnerListEdiDocuments200Response{}
	return &this
}

// NewPartnerListEdiDocuments200ResponseWithDefaults instantiates a new PartnerListEdiDocuments200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerListEdiDocuments200ResponseWithDefaults() *PartnerListEdiDocuments200Response {
	this := PartnerListEdiDocuments200Response{}
	return &this
}

// GetDocuments returns the Documents field value if set, zero value otherwise.
func (o *PartnerListEdiDocuments200Response) GetDocuments() []PartnerEdiDocument {
	if o == nil || IsNil(o.Documents) {
		var ret []PartnerEdiDocument
		return ret
	}
	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerListEdiDocuments200Response) GetDocumentsOk() ([]PartnerEdiDocument, bool) {
	if o == nil || IsNil(o.Documents) {
		return nil, false
	}
	return o.Documents, true
}

// HasDocuments returns a boolean if a field has been set.
func (o *PartnerListEdiDocuments200Response) HasDocuments() bool {
	if o != nil && !IsNil(o.Documents) {
		return true
	}

	return false
}

// SetDocuments gets a reference to the given []PartnerEdiDocument and assigns it to the Documents field.
func (o *PartnerListEdiDocuments200Response) SetDocuments(v []PartnerEdiDocument) {
	o.Documents = v
}

func (o PartnerListEdiDocuments200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerListEdiDocuments200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Documents) {
		toSerialize["documents"] = o.Documents
	}
	return toSerialize, nil
}

type NullablePartnerListEdiDocuments200Response struct {
	value *PartnerListEdiDocuments200Response
	isSet bool
}

func (v NullablePartnerListEdiDocuments200Response) Get() *PartnerListEdiDocuments200Response {
	return v.value
}

func (v *NullablePartnerListEdiDocuments200Response) Set(val *PartnerListEdiDocuments200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerListEdiDocuments200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerListEdiDocuments200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerListEdiDocuments200Response(val *PartnerListEdiDocuments200Response) *NullablePartnerListEdiDocuments200Response {
	return &NullablePartnerListEdiDocuments200Response{value: val, isSet: true}
}

func (v NullablePartnerListEdiDocuments200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerListEdiDocuments200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


