/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
)

// checks if the PartnerCoaMapUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerCoaMapUpdate{}

// PartnerCoaMapUpdate struct for PartnerCoaMapUpdate
type PartnerCoaMapUpdate struct {
	AccountAr *string `json:"account_ar,omitempty"`
	AccountRevenue *string `json:"account_revenue,omitempty"`
	AccountBankCash *string `json:"account_bank_cash,omitempty"`
}

// NewPartnerCoaMapUpdate instantiates a new PartnerCoaMapUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerCoaMapUpdate() *PartnerCoaMapUpdate {
	this := PartnerCoaMapUpdate{}
	return &this
}

// NewPartnerCoaMapUpdateWithDefaults instantiates a new PartnerCoaMapUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerCoaMapUpdateWithDefaults() *PartnerCoaMapUpdate {
	this := PartnerCoaMapUpdate{}
	return &this
}

// GetAccountAr returns the AccountAr field value if set, zero value otherwise.
func (o *PartnerCoaMapUpdate) GetAccountAr() string {
	if o == nil || IsNil(o.AccountAr) {
		var ret string
		return ret
	}
	return *o.AccountAr
}

// GetAccountArOk returns a tuple with the AccountAr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCoaMapUpdate) GetAccountArOk() (*string, bool) {
	if o == nil || IsNil(o.AccountAr) {
		return nil, false
	}
	return o.AccountAr, true
}

// HasAccountAr returns a boolean if a field has been set.
func (o *PartnerCoaMapUpdate) HasAccountAr() bool {
	if o != nil && !IsNil(o.AccountAr) {
		return true
	}

	return false
}

// SetAccountAr gets a reference to the given string and assigns it to the AccountAr field.
func (o *PartnerCoaMapUpdate) SetAccountAr(v string) {
	o.AccountAr = &v
}

// GetAccountRevenue returns the AccountRevenue field value if set, zero value otherwise.
func (o *PartnerCoaMapUpdate) GetAccountRevenue() string {
	if o == nil || IsNil(o.AccountRevenue) {
		var ret string
		return ret
	}
	return *o.AccountRevenue
}

// GetAccountRevenueOk returns a tuple with the AccountRevenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCoaMapUpdate) GetAccountRevenueOk() (*string, bool) {
	if o == nil || IsNil(o.AccountRevenue) {
		return nil, false
	}
	return o.AccountRevenue, true
}

// HasAccountRevenue returns a boolean if a field has been set.
func (o *PartnerCoaMapUpdate) HasAccountRevenue() bool {
	if o != nil && !IsNil(o.AccountRevenue) {
		return true
	}

	return false
}

// SetAccountRevenue gets a reference to the given string and assigns it to the AccountRevenue field.
func (o *PartnerCoaMapUpdate) SetAccountRevenue(v string) {
	o.AccountRevenue = &v
}

// GetAccountBankCash returns the AccountBankCash field value if set, zero value otherwise.
func (o *PartnerCoaMapUpdate) GetAccountBankCash() string {
	if o == nil || IsNil(o.AccountBankCash) {
		var ret string
		return ret
	}
	return *o.AccountBankCash
}

// GetAccountBankCashOk returns a tuple with the AccountBankCash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCoaMapUpdate) GetAccountBankCashOk() (*string, bool) {
	if o == nil || IsNil(o.AccountBankCash) {
		return nil, false
	}
	return o.AccountBankCash, true
}

// HasAccountBankCash returns a boolean if a field has been set.
func (o *PartnerCoaMapUpdate) HasAccountBankCash() bool {
	if o != nil && !IsNil(o.AccountBankCash) {
		return true
	}

	return false
}

// SetAccountBankCash gets a reference to the given string and assigns it to the AccountBankCash field.
func (o *PartnerCoaMapUpdate) SetAccountBankCash(v string) {
	o.AccountBankCash = &v
}

func (o PartnerCoaMapUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerCoaMapUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountAr) {
		toSerialize["account_ar"] = o.AccountAr
	}
	if !IsNil(o.AccountRevenue) {
		toSerialize["account_revenue"] = o.AccountRevenue
	}
	if !IsNil(o.AccountBankCash) {
		toSerialize["account_bank_cash"] = o.AccountBankCash
	}
	return toSerialize, nil
}

type NullablePartnerCoaMapUpdate struct {
	value *PartnerCoaMapUpdate
	isSet bool
}

func (v NullablePartnerCoaMapUpdate) Get() *PartnerCoaMapUpdate {
	return v.value
}

func (v *NullablePartnerCoaMapUpdate) Set(val *PartnerCoaMapUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerCoaMapUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerCoaMapUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerCoaMapUpdate(val *PartnerCoaMapUpdate) *NullablePartnerCoaMapUpdate {
	return &NullablePartnerCoaMapUpdate{value: val, isSet: true}
}

func (v NullablePartnerCoaMapUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerCoaMapUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


