/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerPriceUpsertRequestItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerPriceUpsertRequestItemsInner{}

// PartnerPriceUpsertRequestItemsInner struct for PartnerPriceUpsertRequestItemsInner
type PartnerPriceUpsertRequestItemsInner struct {
	ExternalId string `json:"external_id"`
	PriceMinor int32 `json:"price_minor"`
	Currency *string `json:"currency,omitempty"`
	RetailerId NullableString `json:"retailer_id,omitempty"`
}

type _PartnerPriceUpsertRequestItemsInner PartnerPriceUpsertRequestItemsInner

// NewPartnerPriceUpsertRequestItemsInner instantiates a new PartnerPriceUpsertRequestItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerPriceUpsertRequestItemsInner(externalId string, priceMinor int32) *PartnerPriceUpsertRequestItemsInner {
	this := PartnerPriceUpsertRequestItemsInner{}
	this.ExternalId = externalId
	this.PriceMinor = priceMinor
	return &this
}

// NewPartnerPriceUpsertRequestItemsInnerWithDefaults instantiates a new PartnerPriceUpsertRequestItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerPriceUpsertRequestItemsInnerWithDefaults() *PartnerPriceUpsertRequestItemsInner {
	this := PartnerPriceUpsertRequestItemsInner{}
	return &this
}

// GetExternalId returns the ExternalId field value
func (o *PartnerPriceUpsertRequestItemsInner) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *PartnerPriceUpsertRequestItemsInner) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *PartnerPriceUpsertRequestItemsInner) SetExternalId(v string) {
	o.ExternalId = v
}

// GetPriceMinor returns the PriceMinor field value
func (o *PartnerPriceUpsertRequestItemsInner) GetPriceMinor() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PriceMinor
}

// GetPriceMinorOk returns a tuple with the PriceMinor field value
// and a boolean to check if the value has been set.
func (o *PartnerPriceUpsertRequestItemsInner) GetPriceMinorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceMinor, true
}

// SetPriceMinor sets field value
func (o *PartnerPriceUpsertRequestItemsInner) SetPriceMinor(v int32) {
	o.PriceMinor = v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *PartnerPriceUpsertRequestItemsInner) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerPriceUpsertRequestItemsInner) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *PartnerPriceUpsertRequestItemsInner) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *PartnerPriceUpsertRequestItemsInner) SetCurrency(v string) {
	o.Currency = &v
}

// GetRetailerId returns the RetailerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PartnerPriceUpsertRequestItemsInner) GetRetailerId() string {
	if o == nil || IsNil(o.RetailerId.Get()) {
		var ret string
		return ret
	}
	return *o.RetailerId.Get()
}

// GetRetailerIdOk returns a tuple with the RetailerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PartnerPriceUpsertRequestItemsInner) GetRetailerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetailerId.Get(), o.RetailerId.IsSet()
}

// HasRetailerId returns a boolean if a field has been set.
func (o *PartnerPriceUpsertRequestItemsInner) HasRetailerId() bool {
	if o != nil && o.RetailerId.IsSet() {
		return true
	}

	return false
}

// SetRetailerId gets a reference to the given NullableString and assigns it to the RetailerId field.
func (o *PartnerPriceUpsertRequestItemsInner) SetRetailerId(v string) {
	o.RetailerId.Set(&v)
}
// SetRetailerIdNil sets the value for RetailerId to be an explicit nil
func (o *PartnerPriceUpsertRequestItemsInner) SetRetailerIdNil() {
	o.RetailerId.Set(nil)
}

// UnsetRetailerId ensures that no value is present for RetailerId, not even an explicit nil
func (o *PartnerPriceUpsertRequestItemsInner) UnsetRetailerId() {
	o.RetailerId.Unset()
}

func (o PartnerPriceUpsertRequestItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerPriceUpsertRequestItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["external_id"] = o.ExternalId
	toSerialize["price_minor"] = o.PriceMinor
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if o.RetailerId.IsSet() {
		toSerialize["retailer_id"] = o.RetailerId.Get()
	}
	return toSerialize, nil
}

func (o *PartnerPriceUpsertRequestItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"external_id",
		"price_minor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerPriceUpsertRequestItemsInner := _PartnerPriceUpsertRequestItemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerPriceUpsertRequestItemsInner)

	if err != nil {
		return err
	}

	*o = PartnerPriceUpsertRequestItemsInner(varPartnerPriceUpsertRequestItemsInner)

	return err
}

type NullablePartnerPriceUpsertRequestItemsInner struct {
	value *PartnerPriceUpsertRequestItemsInner
	isSet bool
}

func (v NullablePartnerPriceUpsertRequestItemsInner) Get() *PartnerPriceUpsertRequestItemsInner {
	return v.value
}

func (v *NullablePartnerPriceUpsertRequestItemsInner) Set(val *PartnerPriceUpsertRequestItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerPriceUpsertRequestItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerPriceUpsertRequestItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerPriceUpsertRequestItemsInner(val *PartnerPriceUpsertRequestItemsInner) *NullablePartnerPriceUpsertRequestItemsInner {
	return &NullablePartnerPriceUpsertRequestItemsInner{value: val, isSet: true}
}

func (v NullablePartnerPriceUpsertRequestItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerPriceUpsertRequestItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


