/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerCreateExportRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerCreateExportRequest{}

// PartnerCreateExportRequest struct for PartnerCreateExportRequest
type PartnerCreateExportRequest struct {
	Resource string `json:"resource"`
	Format *string `json:"format,omitempty"`
	// RFC3339 or YYYY-MM-DD
	From *string `json:"from,omitempty"`
	// RFC3339 or YYYY-MM-DD
	To *string `json:"to,omitempty"`
}

type _PartnerCreateExportRequest PartnerCreateExportRequest

// NewPartnerCreateExportRequest instantiates a new PartnerCreateExportRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerCreateExportRequest(resource string) *PartnerCreateExportRequest {
	this := PartnerCreateExportRequest{}
	this.Resource = resource
	var format string = "csv"
	this.Format = &format
	return &this
}

// NewPartnerCreateExportRequestWithDefaults instantiates a new PartnerCreateExportRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerCreateExportRequestWithDefaults() *PartnerCreateExportRequest {
	this := PartnerCreateExportRequest{}
	var format string = "csv"
	this.Format = &format
	return &this
}

// GetResource returns the Resource field value
func (o *PartnerCreateExportRequest) GetResource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *PartnerCreateExportRequest) GetResourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *PartnerCreateExportRequest) SetResource(v string) {
	o.Resource = v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *PartnerCreateExportRequest) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateExportRequest) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *PartnerCreateExportRequest) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *PartnerCreateExportRequest) SetFormat(v string) {
	o.Format = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *PartnerCreateExportRequest) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateExportRequest) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *PartnerCreateExportRequest) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *PartnerCreateExportRequest) SetFrom(v string) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *PartnerCreateExportRequest) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerCreateExportRequest) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *PartnerCreateExportRequest) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *PartnerCreateExportRequest) SetTo(v string) {
	o.To = &v
}

func (o PartnerCreateExportRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerCreateExportRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource"] = o.Resource
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

func (o *PartnerCreateExportRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerCreateExportRequest := _PartnerCreateExportRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerCreateExportRequest)

	if err != nil {
		return err
	}

	*o = PartnerCreateExportRequest(varPartnerCreateExportRequest)

	return err
}

type NullablePartnerCreateExportRequest struct {
	value *PartnerCreateExportRequest
	isSet bool
}

func (v NullablePartnerCreateExportRequest) Get() *PartnerCreateExportRequest {
	return v.value
}

func (v *NullablePartnerCreateExportRequest) Set(val *PartnerCreateExportRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerCreateExportRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerCreateExportRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerCreateExportRequest(val *PartnerCreateExportRequest) *NullablePartnerCreateExportRequest {
	return &NullablePartnerCreateExportRequest{value: val, isSet: true}
}

func (v NullablePartnerCreateExportRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerCreateExportRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


