/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"time"
)

// checks if the PartnerExportJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerExportJob{}

// PartnerExportJob struct for PartnerExportJob
type PartnerExportJob struct {
	JobId *string `json:"job_id,omitempty"`
	TenantType *string `json:"tenant_type,omitempty"`
	TenantId *string `json:"tenant_id,omitempty"`
	Resource *string `json:"resource,omitempty"`
	Format *string `json:"format,omitempty"`
	Status *string `json:"status,omitempty"`
	RowCount *int32 `json:"row_count,omitempty"`
	SftpStatus *string `json:"sftp_status,omitempty"`
	Error *string `json:"error,omitempty"`
	DownloadUrl *string `json:"download_url,omitempty"`
	ObjectPath *string `json:"object_path,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
}

// NewPartnerExportJob instantiates a new PartnerExportJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerExportJob() *PartnerExportJob {
	this := PartnerExportJob{}
	return &this
}

// NewPartnerExportJobWithDefaults instantiates a new PartnerExportJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerExportJobWithDefaults() *PartnerExportJob {
	this := PartnerExportJob{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *PartnerExportJob) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *PartnerExportJob) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *PartnerExportJob) SetJobId(v string) {
	o.JobId = &v
}

// GetTenantType returns the TenantType field value if set, zero value otherwise.
func (o *PartnerExportJob) GetTenantType() string {
	if o == nil || IsNil(o.TenantType) {
		var ret string
		return ret
	}
	return *o.TenantType
}

// GetTenantTypeOk returns a tuple with the TenantType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetTenantTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TenantType) {
		return nil, false
	}
	return o.TenantType, true
}

// HasTenantType returns a boolean if a field has been set.
func (o *PartnerExportJob) HasTenantType() bool {
	if o != nil && !IsNil(o.TenantType) {
		return true
	}

	return false
}

// SetTenantType gets a reference to the given string and assigns it to the TenantType field.
func (o *PartnerExportJob) SetTenantType(v string) {
	o.TenantType = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *PartnerExportJob) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *PartnerExportJob) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *PartnerExportJob) SetTenantId(v string) {
	o.TenantId = &v
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *PartnerExportJob) GetResource() string {
	if o == nil || IsNil(o.Resource) {
		var ret string
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetResourceOk() (*string, bool) {
	if o == nil || IsNil(o.Resource) {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *PartnerExportJob) HasResource() bool {
	if o != nil && !IsNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given string and assigns it to the Resource field.
func (o *PartnerExportJob) SetResource(v string) {
	o.Resource = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *PartnerExportJob) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *PartnerExportJob) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *PartnerExportJob) SetFormat(v string) {
	o.Format = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PartnerExportJob) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PartnerExportJob) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PartnerExportJob) SetStatus(v string) {
	o.Status = &v
}

// GetRowCount returns the RowCount field value if set, zero value otherwise.
func (o *PartnerExportJob) GetRowCount() int32 {
	if o == nil || IsNil(o.RowCount) {
		var ret int32
		return ret
	}
	return *o.RowCount
}

// GetRowCountOk returns a tuple with the RowCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetRowCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RowCount) {
		return nil, false
	}
	return o.RowCount, true
}

// HasRowCount returns a boolean if a field has been set.
func (o *PartnerExportJob) HasRowCount() bool {
	if o != nil && !IsNil(o.RowCount) {
		return true
	}

	return false
}

// SetRowCount gets a reference to the given int32 and assigns it to the RowCount field.
func (o *PartnerExportJob) SetRowCount(v int32) {
	o.RowCount = &v
}

// GetSftpStatus returns the SftpStatus field value if set, zero value otherwise.
func (o *PartnerExportJob) GetSftpStatus() string {
	if o == nil || IsNil(o.SftpStatus) {
		var ret string
		return ret
	}
	return *o.SftpStatus
}

// GetSftpStatusOk returns a tuple with the SftpStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetSftpStatusOk() (*string, bool) {
	if o == nil || IsNil(o.SftpStatus) {
		return nil, false
	}
	return o.SftpStatus, true
}

// HasSftpStatus returns a boolean if a field has been set.
func (o *PartnerExportJob) HasSftpStatus() bool {
	if o != nil && !IsNil(o.SftpStatus) {
		return true
	}

	return false
}

// SetSftpStatus gets a reference to the given string and assigns it to the SftpStatus field.
func (o *PartnerExportJob) SetSftpStatus(v string) {
	o.SftpStatus = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PartnerExportJob) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PartnerExportJob) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *PartnerExportJob) SetError(v string) {
	o.Error = &v
}

// GetDownloadUrl returns the DownloadUrl field value if set, zero value otherwise.
func (o *PartnerExportJob) GetDownloadUrl() string {
	if o == nil || IsNil(o.DownloadUrl) {
		var ret string
		return ret
	}
	return *o.DownloadUrl
}

// GetDownloadUrlOk returns a tuple with the DownloadUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetDownloadUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DownloadUrl) {
		return nil, false
	}
	return o.DownloadUrl, true
}

// HasDownloadUrl returns a boolean if a field has been set.
func (o *PartnerExportJob) HasDownloadUrl() bool {
	if o != nil && !IsNil(o.DownloadUrl) {
		return true
	}

	return false
}

// SetDownloadUrl gets a reference to the given string and assigns it to the DownloadUrl field.
func (o *PartnerExportJob) SetDownloadUrl(v string) {
	o.DownloadUrl = &v
}

// GetObjectPath returns the ObjectPath field value if set, zero value otherwise.
func (o *PartnerExportJob) GetObjectPath() string {
	if o == nil || IsNil(o.ObjectPath) {
		var ret string
		return ret
	}
	return *o.ObjectPath
}

// GetObjectPathOk returns a tuple with the ObjectPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetObjectPathOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectPath) {
		return nil, false
	}
	return o.ObjectPath, true
}

// HasObjectPath returns a boolean if a field has been set.
func (o *PartnerExportJob) HasObjectPath() bool {
	if o != nil && !IsNil(o.ObjectPath) {
		return true
	}

	return false
}

// SetObjectPath gets a reference to the given string and assigns it to the ObjectPath field.
func (o *PartnerExportJob) SetObjectPath(v string) {
	o.ObjectPath = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PartnerExportJob) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PartnerExportJob) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *PartnerExportJob) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise.
func (o *PartnerExportJob) GetFinishedAt() time.Time {
	if o == nil || IsNil(o.FinishedAt) {
		var ret time.Time
		return ret
	}
	return *o.FinishedAt
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerExportJob) GetFinishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FinishedAt) {
		return nil, false
	}
	return o.FinishedAt, true
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *PartnerExportJob) HasFinishedAt() bool {
	if o != nil && !IsNil(o.FinishedAt) {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given time.Time and assigns it to the FinishedAt field.
func (o *PartnerExportJob) SetFinishedAt(v time.Time) {
	o.FinishedAt = &v
}

func (o PartnerExportJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerExportJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobId) {
		toSerialize["job_id"] = o.JobId
	}
	if !IsNil(o.TenantType) {
		toSerialize["tenant_type"] = o.TenantType
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.RowCount) {
		toSerialize["row_count"] = o.RowCount
	}
	if !IsNil(o.SftpStatus) {
		toSerialize["sftp_status"] = o.SftpStatus
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.DownloadUrl) {
		toSerialize["download_url"] = o.DownloadUrl
	}
	if !IsNil(o.ObjectPath) {
		toSerialize["object_path"] = o.ObjectPath
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.FinishedAt) {
		toSerialize["finished_at"] = o.FinishedAt
	}
	return toSerialize, nil
}

type NullablePartnerExportJob struct {
	value *PartnerExportJob
	isSet bool
}

func (v NullablePartnerExportJob) Get() *PartnerExportJob {
	return v.value
}

func (v *NullablePartnerExportJob) Set(val *PartnerExportJob) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerExportJob) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerExportJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerExportJob(val *PartnerExportJob) *NullablePartnerExportJob {
	return &NullablePartnerExportJob{value: val, isSet: true}
}

func (v NullablePartnerExportJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerExportJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


