/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartnerStockUpsertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerStockUpsertRequest{}

// PartnerStockUpsertRequest struct for PartnerStockUpsertRequest
type PartnerStockUpsertRequest struct {
	Items []PartnerStockUpsertRequestItemsInner `json:"items"`
}

type _PartnerStockUpsertRequest PartnerStockUpsertRequest

// NewPartnerStockUpsertRequest instantiates a new PartnerStockUpsertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerStockUpsertRequest(items []PartnerStockUpsertRequestItemsInner) *PartnerStockUpsertRequest {
	this := PartnerStockUpsertRequest{}
	this.Items = items
	return &this
}

// NewPartnerStockUpsertRequestWithDefaults instantiates a new PartnerStockUpsertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerStockUpsertRequestWithDefaults() *PartnerStockUpsertRequest {
	this := PartnerStockUpsertRequest{}
	return &this
}

// GetItems returns the Items field value
func (o *PartnerStockUpsertRequest) GetItems() []PartnerStockUpsertRequestItemsInner {
	if o == nil {
		var ret []PartnerStockUpsertRequestItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PartnerStockUpsertRequest) GetItemsOk() ([]PartnerStockUpsertRequestItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PartnerStockUpsertRequest) SetItems(v []PartnerStockUpsertRequestItemsInner) {
	o.Items = v
}

func (o PartnerStockUpsertRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerStockUpsertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *PartnerStockUpsertRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartnerStockUpsertRequest := _PartnerStockUpsertRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartnerStockUpsertRequest)

	if err != nil {
		return err
	}

	*o = PartnerStockUpsertRequest(varPartnerStockUpsertRequest)

	return err
}

type NullablePartnerStockUpsertRequest struct {
	value *PartnerStockUpsertRequest
	isSet bool
}

func (v NullablePartnerStockUpsertRequest) Get() *PartnerStockUpsertRequest {
	return v.value
}

func (v *NullablePartnerStockUpsertRequest) Set(val *PartnerStockUpsertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerStockUpsertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerStockUpsertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerStockUpsertRequest(val *PartnerStockUpsertRequest) *NullablePartnerStockUpsertRequest {
	return &NullablePartnerStockUpsertRequest{value: val, isSet: true}
}

func (v NullablePartnerStockUpsertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerStockUpsertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


