/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
	"time"
)

// checks if the PartnerWebhookSubscription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerWebhookSubscription{}

// PartnerWebhookSubscription struct for PartnerWebhookSubscription
type PartnerWebhookSubscription struct {
	SubscriptionId *string `json:"subscription_id,omitempty"`
	Url *string `json:"url,omitempty"`
	EventTypes []string `json:"event_types,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	SecretPrefix *string `json:"secret_prefix,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewPartnerWebhookSubscription instantiates a new PartnerWebhookSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerWebhookSubscription() *PartnerWebhookSubscription {
	this := PartnerWebhookSubscription{}
	return &this
}

// NewPartnerWebhookSubscriptionWithDefaults instantiates a new PartnerWebhookSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerWebhookSubscriptionWithDefaults() *PartnerWebhookSubscription {
	this := PartnerWebhookSubscription{}
	return &this
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *PartnerWebhookSubscription) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerWebhookSubscription) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *PartnerWebhookSubscription) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *PartnerWebhookSubscription) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *PartnerWebhookSubscription) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerWebhookSubscription) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *PartnerWebhookSubscription) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *PartnerWebhookSubscription) SetUrl(v string) {
	o.Url = &v
}

// GetEventTypes returns the EventTypes field value if set, zero value otherwise.
func (o *PartnerWebhookSubscription) GetEventTypes() []string {
	if o == nil || IsNil(o.EventTypes) {
		var ret []string
		return ret
	}
	return o.EventTypes
}

// GetEventTypesOk returns a tuple with the EventTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerWebhookSubscription) GetEventTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.EventTypes) {
		return nil, false
	}
	return o.EventTypes, true
}

// HasEventTypes returns a boolean if a field has been set.
func (o *PartnerWebhookSubscription) HasEventTypes() bool {
	if o != nil && !IsNil(o.EventTypes) {
		return true
	}

	return false
}

// SetEventTypes gets a reference to the given []string and assigns it to the EventTypes field.
func (o *PartnerWebhookSubscription) SetEventTypes(v []string) {
	o.EventTypes = v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *PartnerWebhookSubscription) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerWebhookSubscription) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *PartnerWebhookSubscription) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *PartnerWebhookSubscription) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetSecretPrefix returns the SecretPrefix field value if set, zero value otherwise.
func (o *PartnerWebhookSubscription) GetSecretPrefix() string {
	if o == nil || IsNil(o.SecretPrefix) {
		var ret string
		return ret
	}
	return *o.SecretPrefix
}

// GetSecretPrefixOk returns a tuple with the SecretPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerWebhookSubscription) GetSecretPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.SecretPrefix) {
		return nil, false
	}
	return o.SecretPrefix, true
}

// HasSecretPrefix returns a boolean if a field has been set.
func (o *PartnerWebhookSubscription) HasSecretPrefix() bool {
	if o != nil && !IsNil(o.SecretPrefix) {
		return true
	}

	return false
}

// SetSecretPrefix gets a reference to the given string and assigns it to the SecretPrefix field.
func (o *PartnerWebhookSubscription) SetSecretPrefix(v string) {
	o.SecretPrefix = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PartnerWebhookSubscription) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerWebhookSubscription) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PartnerWebhookSubscription) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *PartnerWebhookSubscription) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o PartnerWebhookSubscription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerWebhookSubscription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscription_id"] = o.SubscriptionId
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.EventTypes) {
		toSerialize["event_types"] = o.EventTypes
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.SecretPrefix) {
		toSerialize["secret_prefix"] = o.SecretPrefix
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullablePartnerWebhookSubscription struct {
	value *PartnerWebhookSubscription
	isSet bool
}

func (v NullablePartnerWebhookSubscription) Get() *PartnerWebhookSubscription {
	return v.value
}

func (v *NullablePartnerWebhookSubscription) Set(val *PartnerWebhookSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerWebhookSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerWebhookSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerWebhookSubscription(val *PartnerWebhookSubscription) *NullablePartnerWebhookSubscription {
	return &NullablePartnerWebhookSubscription{value: val, isSet: true}
}

func (v NullablePartnerWebhookSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerWebhookSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


