/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
)

// checks if the IssuePartnerApiKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssuePartnerApiKeyRequest{}

// IssuePartnerApiKeyRequest struct for IssuePartnerApiKeyRequest
type IssuePartnerApiKeyRequest struct {
	TenantType *string `json:"tenant_type,omitempty"`
	TenantId *string `json:"tenant_id,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
}

// NewIssuePartnerApiKeyRequest instantiates a new IssuePartnerApiKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssuePartnerApiKeyRequest() *IssuePartnerApiKeyRequest {
	this := IssuePartnerApiKeyRequest{}
	return &this
}

// NewIssuePartnerApiKeyRequestWithDefaults instantiates a new IssuePartnerApiKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssuePartnerApiKeyRequestWithDefaults() *IssuePartnerApiKeyRequest {
	this := IssuePartnerApiKeyRequest{}
	return &this
}

// GetTenantType returns the TenantType field value if set, zero value otherwise.
func (o *IssuePartnerApiKeyRequest) GetTenantType() string {
	if o == nil || IsNil(o.TenantType) {
		var ret string
		return ret
	}
	return *o.TenantType
}

// GetTenantTypeOk returns a tuple with the TenantType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuePartnerApiKeyRequest) GetTenantTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TenantType) {
		return nil, false
	}
	return o.TenantType, true
}

// HasTenantType returns a boolean if a field has been set.
func (o *IssuePartnerApiKeyRequest) HasTenantType() bool {
	if o != nil && !IsNil(o.TenantType) {
		return true
	}

	return false
}

// SetTenantType gets a reference to the given string and assigns it to the TenantType field.
func (o *IssuePartnerApiKeyRequest) SetTenantType(v string) {
	o.TenantType = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *IssuePartnerApiKeyRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuePartnerApiKeyRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *IssuePartnerApiKeyRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *IssuePartnerApiKeyRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *IssuePartnerApiKeyRequest) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuePartnerApiKeyRequest) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *IssuePartnerApiKeyRequest) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *IssuePartnerApiKeyRequest) SetScopes(v []string) {
	o.Scopes = v
}

func (o IssuePartnerApiKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssuePartnerApiKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantType) {
		toSerialize["tenant_type"] = o.TenantType
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	return toSerialize, nil
}

type NullableIssuePartnerApiKeyRequest struct {
	value *IssuePartnerApiKeyRequest
	isSet bool
}

func (v NullableIssuePartnerApiKeyRequest) Get() *IssuePartnerApiKeyRequest {
	return v.value
}

func (v *NullableIssuePartnerApiKeyRequest) Set(val *IssuePartnerApiKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuePartnerApiKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuePartnerApiKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuePartnerApiKeyRequest(val *IssuePartnerApiKeyRequest) *NullableIssuePartnerApiKeyRequest {
	return &NullableIssuePartnerApiKeyRequest{value: val, isSet: true}
}

func (v NullableIssuePartnerApiKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuePartnerApiKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


