/*
PegasusX Partner API

Gate-3 machine integration surface (§8.9). Authenticate with a partner API key (`Authorization: Bearer pxk_…`) **or** a short-lived OAuth2 access token from `POST /partner/v1/oauth/token` (`grant_type=client_credentials`; `PartnerApiKeys` are the clients). Human JWT sessions issue keys via `/v1/admin/partner-keys` (supplier aliases under `/v1/supplier/…`). Wave 2A: bulk exports + webhook ops + SFTP. Wave 2B: EDI-lite. Wave 2C: GS1. Journals + configurable CoA. AS2 transport over EDI-lite (not Drummond-certified). Phase 2: master-data upsert (products/prices/stock), webhook secret rotation, POS demand feed, CONTRL/APERAK + inbound ORDRSP/INVOIC, SFTP host-key pinning, GS1 DataMatrix AI scaffolding. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package partnerclient

import (
	"encoding/json"
)

// checks if the PartnerListExports200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartnerListExports200Response{}

// PartnerListExports200Response struct for PartnerListExports200Response
type PartnerListExports200Response struct {
	Jobs []PartnerExportJob `json:"jobs,omitempty"`
}

// NewPartnerListExports200Response instantiates a new PartnerListExports200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartnerListExports200Response() *PartnerListExports200Response {
	this := PartnerListExports200Response{}
	return &this
}

// NewPartnerListExports200ResponseWithDefaults instantiates a new PartnerListExports200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartnerListExports200ResponseWithDefaults() *PartnerListExports200Response {
	this := PartnerListExports200Response{}
	return &this
}

// GetJobs returns the Jobs field value if set, zero value otherwise.
func (o *PartnerListExports200Response) GetJobs() []PartnerExportJob {
	if o == nil || IsNil(o.Jobs) {
		var ret []PartnerExportJob
		return ret
	}
	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartnerListExports200Response) GetJobsOk() ([]PartnerExportJob, bool) {
	if o == nil || IsNil(o.Jobs) {
		return nil, false
	}
	return o.Jobs, true
}

// HasJobs returns a boolean if a field has been set.
func (o *PartnerListExports200Response) HasJobs() bool {
	if o != nil && !IsNil(o.Jobs) {
		return true
	}

	return false
}

// SetJobs gets a reference to the given []PartnerExportJob and assigns it to the Jobs field.
func (o *PartnerListExports200Response) SetJobs(v []PartnerExportJob) {
	o.Jobs = v
}

func (o PartnerListExports200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartnerListExports200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Jobs) {
		toSerialize["jobs"] = o.Jobs
	}
	return toSerialize, nil
}

type NullablePartnerListExports200Response struct {
	value *PartnerListExports200Response
	isSet bool
}

func (v NullablePartnerListExports200Response) Get() *PartnerListExports200Response {
	return v.value
}

func (v *NullablePartnerListExports200Response) Set(val *PartnerListExports200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePartnerListExports200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePartnerListExports200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartnerListExports200Response(val *PartnerListExports200Response) *NullablePartnerListExports200Response {
	return &NullablePartnerListExports200Response{value: val, isSet: true}
}

func (v NullablePartnerListExports200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartnerListExports200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


