apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-worker-config
  labels:
    app: ai-worker
    app.kubernetes.io/name: ai-worker
    app.kubernetes.io/part-of: pegasusx
data:
  LOG_LEVEL: "info"
  HEALTH_PORT: "8081"
  SPANNER_PROJECT: "pegasusx-local"
  PEGASUSX_ENV: "staging"
  REDIS_ADDR: "10.251.238.236:6378"
  REDIS_TLS_ENABLED: "true"
  SPANNER_INSTANCE: "pegasusx-ssmr-spanner"
  SPANNER_DATABASE: "pegasusx-ssmr-db"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC_INVENTORY_IMPORT: "pegasusx-inventory-import"
  GCS_BUCKET_NAME: "pegasusx-prod-catalog"
  IMPORT_LOCAL_FILE_ROOT: "/var/pegasusx/import-local"