apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: pegasusx-gsm
  namespace: pegasusx
  labels:
    app.kubernetes.io/part-of: pegasusx
spec:
  provider:
    gcpsm:
      projectID: demo-project
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: backend-go
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-go-secrets
  namespace: pegasusx
  labels:
    app.kubernetes.io/part-of: pegasusx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pegasusx-gsm
    kind: SecretStore
  target:
    name: backend-go-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: pegasusx-prod-jwt-secret
    - secretKey: global-pay-webhook-secret
      remoteRef:
        key: pegasusx-prod-global-pay-webhook-secret
    - secretKey: adyen-webhook-secret
      remoteRef:
        key: pegasusx-prod-adyen-webhook-secret
    - secretKey: stripe-webhook-secret
      remoteRef:
        key: pegasusx-prod-stripe-webhook-secret
