apiVersion: v1
kind: Service
metadata:
  name: ai-worker
  namespace: void-system
  labels:
    app: ai-worker
spec:
  type: ClusterIP
  selector:
    app: ai-worker
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
