apiVersion: v1
kind: Service
metadata:
  name: ai-worker
  labels:
    app: ai-worker
    app.kubernetes.io/name: ai-worker
    app.kubernetes.io/part-of: pegasusx
spec:
  type: ClusterIP
  selector:
    app: ai-worker
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP