import type { InfraNode, HudTelemetryCard } from './types';

export const INFRA_NODES: InfraNode[] = [
  {
    id: 'data-core',
    name: 'Cloud Spanner & Event Mesh',
    subtitle: 'Globally Distributed Transaction Core',
    category: 'data',
    tech: ['Cloud Spanner', 'Kafka KRaft', 'Redis 7', 'PostgreSQL'],
    status: 'active',
    metrics: [
      { label: 'Multi-Region SLA', value: '99.999', unit: '%' },
      { label: 'Commit Latency', value: '< 8', unit: 'ms' },
      { label: 'Kafka Ingestion', value: '2.4M', unit: 'msg/s' },
    ],
    description:
      'Multi-region Google Cloud Spanner database providing external consensus and strict ACID order transaction locking, coupled with Confluent Kafka in KRaft mode for zero-loss telemetry streaming.',
    repoPath: 'infra/spanner, docker-compose.yml (kafka, redis, spanner)',
    gridX: 0,
    gridY: 0,
    height: 60,
  },
  {
    id: 'backend-go',
    name: 'Go Distributed State Engine',
    subtitle: 'Event-Driven Order Lifecycle Daemon',
    category: 'compute',
    tech: ['Go 1.22', 'gRPC', 'Protobuf', 'Kubernetes HPA'],
    status: 'optimal',
    metrics: [
      { label: 'Throughput', value: '18,500', unit: 'ops/s' },
      { label: 'Outbox Drop Rate', value: '0.000', unit: '%' },
      { label: 'Memory Footprint', value: '38', unit: 'MB' },
    ],
    description:
      'High-concurrency Go microservices executing the state machine transitions from dispatch offer to carrier acceptance, escrow locking, and automated route execution.',
    repoPath: 'apps/backend-go, backend-go',
    gridX: 3.5,
    gridY: -2.5,
    height: 140,
  },
  {
    id: 'optimizer-rust',
    name: 'Rust VRP Routing Solver',
    subtitle: 'Sub-Second Combinatorial Vehicle Routing',
    category: 'compute',
    tech: ['Rust 1.78', 'Rayon Parallelism', 'SIMD Math', 'OR-Tools'],
    status: 'active',
    metrics: [
      { label: 'Solve Duration', value: '118', unit: 'ms' },
      { label: 'Consolidation Ratio', value: '94.2', unit: '%' },
      { label: 'Order Capacity', value: '2,400', unit: 'orders/batch' },
    ],
    description:
      'Bare-metal Rust routing solver executing vehicle routing problem (VRP) algorithms with strict pallet weight distributions, cold-chain temperature thresholds, and dynamic driver rest windows.',
    repoPath: 'services/optimizer-core, services/deep-agents',
    gridX: 5.5,
    gridY: 1.5,
    height: 110,
  },
  {
    id: 'edge-portals',
    name: 'Unified Control Plane Towers',
    subtitle: 'Portal, Mobile & Desktop Microfrontends',
    category: 'edge',
    tech: ['Next.js 14', 'React 19', 'Tauri / Rust', 'Tailwind'],
    status: 'synced',
    metrics: [
      { label: 'Active Surfaces', value: '6', unit: 'roles' },
      { label: 'Live Sync Latency', value: '14', unit: 'ms' },
      { label: 'Client Uptime', value: '99.98', unit: '%' },
    ],
    description:
      'Role-governed operational cockpits across Supplier Control Plane, Warehouse WMS, Factory Inbound, and Retailer Desktop Commerce synchronized on a single shared order record.',
    repoPath: 'apps/admin-portal, apps/warehouse-portal, apps/retailer-app-desktop',
    gridX: -3.5,
    gridY: -3,
    height: 120,
  },
  {
    id: 'gate-security',
    name: 'Cryptographic Gate Terminal',
    subtitle: '3-Factor Outbound Tamper Verification',
    category: 'security',
    tech: ['Optical OCR', 'Ed25519 Keys', 'RFID Scanners', 'Secure SQLite'],
    status: 'locked',
    metrics: [
      { label: 'Gate Clearance', value: '11.4', unit: 'sec' },
      { label: 'Seal Verification', value: '100', unit: '%' },
      { label: 'Tamper Alarm Drift', value: '0', unit: 'err' },
    ],
    description:
      'Hardware-integrated gate kiosk inspecting driver cryptographic tokens, trailer registration plate OCR, and tamper-evident cable seals before physical gate clearance.',
    repoPath: 'apps/payload-terminal, apps/payload-app-android',
    gridX: -3.8,
    gridY: 2.8,
    height: 50,
  },
  {
    id: 'mobile-fleet',
    name: 'Driver & Warehouse Offline Mesh',
    subtitle: 'Local-First Encrypted Cellular Fallback',
    category: 'edge',
    tech: ['Kotlin Compose', 'Swift / UIKit', 'SQLite WAL', 'Idempotent Outbox'],
    status: 'active',
    metrics: [
      { label: 'Connected Devices', value: '1,420', unit: 'units' },
      { label: 'Offline Queueing', value: '100', unit: '% safe' },
      { label: 'Replay Sync', value: '< 1.2', unit: 's' },
    ],
    description:
      'Native Android and iOS mobile terminals supporting ruggedized laser scanners. Transactions buffer locally in encrypted SQLite and drain through cryptographic idempotency upon reconnect.',
    repoPath: 'apps/driver-app-android, apps/driverappios, apps/warehouse-app-android',
    gridX: 1.8,
    gridY: 4.8,
    height: 40,
  },
];

export const HUD_CARDS: HudTelemetryCard[] = [
  {
    id: 'card-clients',
    title: 'Distributed Network Core',
    status: 'LIVE CLUSTER',
    statusColor: '#10b981',
    metrics: [
      { label: 'Active Edge Nodes', value: '1,420 Online', color: '#ffffff' },
      { label: 'Cluster Uptime', value: '99.998%', color: '#a78bfa' },
      { label: 'Secure Data Flow', value: 'Stable · TLS 1.3', color: '#10b981' },
    ],
    anchorNodeId: 'backend-go',
    cardPos: { x: 42, y: 12 },
    leaderLine: { startX: 48, startY: 24, endX: 52, endY: 34 },
  },
  {
    id: 'card-storage',
    title: 'Cloud Spanner',
    status: 'ACID LOCKED',
    statusColor: '#34d399',
    metrics: [
      { label: 'Encrypted Storage', value: 'Active · Multi-Region', color: '#10b981' },
    ],
    anchorNodeId: 'data-core',
    cardPos: { x: 44, y: 28 },
    leaderLine: { startX: 49, startY: 35, endX: 50, endY: 52 },
  },
  {
    id: 'card-sync-left',
    title: 'Unified WMS & Portals',
    status: 'SYNCED',
    statusColor: '#10b981',
    metrics: [
      { icon: '✓', label: 'Surfaces', value: 'Connected (6/6)', color: '#ffffff' },
      { icon: '✓', label: 'Data Sync', value: 'Real-Time SSE', color: '#10b981' },
      { icon: '✓', label: 'Invoices', value: 'Instant Clearing', color: '#ffffff' },
    ],
    anchorNodeId: 'edge-portals',
    cardPos: { x: 18, y: 22 },
    leaderLine: { startX: 24, startY: 34, endX: 28, endY: 44 },
  },
  {
    id: 'card-tx-right',
    title: 'Rust Optimizer Core',
    status: 'SOLVING',
    statusColor: '#60a5fa',
    metrics: [
      { icon: '⇄', label: 'Dispatch Solver', value: '118ms VRP', color: '#60a5fa' },
      { icon: '✓', label: 'Client Access', value: 'Verified Key', color: '#10b981' },
    ],
    anchorNodeId: 'optimizer-rust',
    cardPos: { x: 74, y: 28 },
    leaderLine: { startX: 74, startY: 38, endX: 68, endY: 48 },
  },
  {
    id: 'card-mobile-sync',
    title: 'Gate & Driver Handhelds',
    status: 'OPERATIONAL',
    statusColor: '#10b981',
    metrics: [
      { icon: '✓', label: 'Field Scanners', value: 'Connected', color: '#ffffff' },
      { icon: '✓', label: 'Offline Store', value: 'SQLite WAL Active', color: '#10b981' },
      { icon: '✓', label: 'Gate Seals', value: 'Tamper Proof', color: '#34d399' },
    ],
    anchorNodeId: 'mobile-fleet',
    cardPos: { x: 62, y: 56 },
    leaderLine: { startX: 65, startY: 68, endX: 58, endY: 76 },
  },
];
