import type { InfraNode, HudTelemetryCard } from './types';

export const INFRA_NODES: InfraNode[] = [
  {
    id: 'data-core',
    name: 'Google Cloud Spanner & Redis',
    subtitle: 'Globally Distributed Data Plane',
    category: 'data',
    tech: ['Google Cloud', 'Cloud Spanner', 'Redis', 'BigQuery'],
    status: 'active',
    metrics: [
      { label: 'Multi-Region SLA', value: '99.999', unit: '%' },
      { label: 'Read Latency', value: '< 2', unit: 'ms' },
      { label: 'Cache Hit Rate', value: '98.4', unit: '%' },
    ],
    description:
      'The central data repository providing strict ACID consistency globally via Cloud Spanner, accelerated by high-speed in-memory caching through distributed Redis clusters.',
    repoPath: 'infra/data-plane, docker-compose.yml',
    gridX: 0,
    gridY: 0,
    height: 60,
  },
  {
    id: 'backend-go',
    name: 'Kafka & Go Backend Services',
    subtitle: 'Event-Driven Service Plane',
    category: 'compute',
    tech: ['Apache Kafka', 'Go 1.22', 'gRPC', 'Kubernetes'],
    status: 'optimal',
    metrics: [
      { label: 'Throughput', value: '25,000', unit: 'msg/s' },
      { label: 'Event Latency', value: '< 15', unit: 'ms' },
      { label: 'Memory Footprint', value: '45', unit: 'MB' },
    ],
    description:
      'Mission-critical distributed event streaming platform handling real-time telemetry, order state changes, and asynchronous messaging processed by high-concurrency Go microservices.',
    repoPath: 'apps/backend-go, infra/kafka-mesh',
    gridX: 3.5,
    gridY: -2.5,
    height: 140,
  },
  {
    id: 'optimizer-rust',
    name: 'Rust Optimizer Core',
    subtitle: 'Sub-Second Combinatorial Routing',
    category: 'compute',
    tech: ['Rust 1.78', 'Rayon Parallelism', 'SIMD Math', 'OR-Tools'],
    status: 'active',
    metrics: [
      { label: 'Solve Duration', value: '118', unit: 'ms' },
      { label: 'Consolidation Ratio', value: '94.2', unit: '%' },
      { label: 'Order Capacity', value: '2,400', unit: 'orders/batch' },
    ],
    description:
      'Bare-metal Rust routing solver executing complex vehicle routing problem (VRP) algorithms with strict pallet weight distributions and dynamic delivery windows.',
    repoPath: 'services/optimizer-core',
    gridX: 5.5,
    gridY: 1.5,
    height: 110,
  },
  {
    id: 'edge-portals',
    name: 'Enterprise Web Apps',
    subtitle: 'Admin, Fleet & Supplier Portals',
    category: 'edge',
    tech: ['Next.js 14', 'React 19', 'Tailwind', 'Vercel'],
    status: 'synced',
    metrics: [
      { label: 'Active Surfaces', value: '3', unit: 'portals' },
      { label: 'LCP Score', value: '0.8', unit: 's' },
      { label: 'Global Edge Ping', value: '22', unit: 'ms' },
    ],
    description:
      'Comprehensive enterprise web applications providing dedicated operational cockpits for network administrators, fleet managers, and external suppliers.',
    repoPath: 'apps/admin-portal, apps/fleet-portal',
    gridX: -3.5,
    gridY: -3,
    height: 120,
  },
  {
    id: 'gate-security',
    name: 'Firebase Edge Services',
    subtitle: 'Real-Time Sync & Notifications',
    category: 'security',
    tech: ['Firebase', 'WebSockets', 'FCM', 'Firestore'],
    status: 'locked',
    metrics: [
      { label: 'Live Connections', value: '15.4', unit: 'k' },
      { label: 'Sync Latency', value: '< 50', unit: 'ms' },
      { label: 'Delivery Rate', value: '99.9', unit: '%' },
    ],
    description:
      'Handles instant live-tracking updates, push notifications, and real-time state synchronization across all connected mobile clients and web dashboards.',
    repoPath: 'infra/firebase-edge',
    gridX: -3.8,
    gridY: 2.8,
    height: 50,
  },
  {
    id: 'mobile-fleet',
    name: 'Mobile Fleet Applications',
    subtitle: 'Driver, Warehouse, Factory, Retailer',
    category: 'edge',
    tech: ['iOS', 'Android', 'React Native', 'SQLite'],
    status: 'active',
    metrics: [
      { label: 'Connected Devices', value: '4,250', unit: 'units' },
      { label: 'Offline Queueing', value: '100', unit: '% safe' },
      { label: 'Crash-Free Rate', value: '99.8', unit: '%' },
    ],
    description:
      'A unified fleet of native and cross-platform mobile applications empowering truck drivers, warehouse pickers, factory floors, and retail store managers with real-time operational tools.',
    repoPath: 'apps/mobile-driver, apps/mobile-warehouse',
    gridX: 1.8,
    gridY: 4.8,
    height: 40,
  },
];

export const HUD_CARDS: HudTelemetryCard[] = [
  {
    id: 'card-clients',
    title: 'Distributed Network Core',
    status: 'LIVE CLUSTER',
    statusColor: '#10b981',
    metrics: [
      { label: 'Active Edge Nodes', value: '1,420 Online', color: '#ffffff' },
      { label: 'Cluster Uptime', value: '99.998%', color: '#a78bfa' },
      { label: 'Secure Data Flow', value: 'Stable · TLS 1.3', color: '#10b981' },
    ],
    anchorNodeId: 'backend-go',
    cardPos: { x: 42, y: 12 },
    leaderLine: { startX: 48, startY: 24, endX: 52, endY: 34 },
  },
  {
    id: 'card-storage',
    title: 'Cloud Spanner',
    status: 'ACID LOCKED',
    statusColor: '#34d399',
    metrics: [
      { label: 'Encrypted Storage', value: 'Active · Multi-Region', color: '#10b981' },
    ],
    anchorNodeId: 'data-core',
    cardPos: { x: 44, y: 28 },
    leaderLine: { startX: 49, startY: 35, endX: 50, endY: 52 },
  },
  {
    id: 'card-sync-left',
    title: 'Unified WMS & Portals',
    status: 'SYNCED',
    statusColor: '#10b981',
    metrics: [
      { icon: '✓', label: 'Surfaces', value: 'Connected (6/6)', color: '#ffffff' },
      { icon: '✓', label: 'Data Sync', value: 'Real-Time SSE', color: '#10b981' },
      { icon: '✓', label: 'Invoices', value: 'Instant Clearing', color: '#ffffff' },
    ],
    anchorNodeId: 'edge-portals',
    cardPos: { x: 18, y: 22 },
    leaderLine: { startX: 24, startY: 34, endX: 28, endY: 44 },
  },
  {
    id: 'card-tx-right',
    title: 'Rust Optimizer Core',
    status: 'SOLVING',
    statusColor: '#60a5fa',
    metrics: [
      { icon: '⇄', label: 'Dispatch Solver', value: '118ms VRP', color: '#60a5fa' },
      { icon: '✓', label: 'Client Access', value: 'Verified Key', color: '#10b981' },
    ],
    anchorNodeId: 'optimizer-rust',
    cardPos: { x: 74, y: 28 },
    leaderLine: { startX: 74, startY: 38, endX: 68, endY: 48 },
  },
  {
    id: 'card-mobile-sync',
    title: 'Gate & Driver Handhelds',
    status: 'OPERATIONAL',
    statusColor: '#10b981',
    metrics: [
      { icon: '✓', label: 'Field Scanners', value: 'Connected', color: '#ffffff' },
      { icon: '✓', label: 'Offline Store', value: 'SQLite WAL Active', color: '#10b981' },
      { icon: '✓', label: 'Gate Seals', value: 'Tamper Proof', color: '#34d399' },
    ],
    anchorNodeId: 'mobile-fleet',
    cardPos: { x: 62, y: 56 },
    leaderLine: { startX: 65, startY: 68, endX: 58, endY: 76 },
  },
];
