#!/usr/bin/env bash
# Export K8s render env from pegasusX/infra/terraform outputs, then render manifests.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${ROOT}/infra/terraform"
TAG="${IMAGE_TAG:-latest}"

if ! command -v jq >/dev/null 2>&1; then
  echo "render_k8s_from_terraform: jq required (brew install jq)" >&2
  exit 1
fi

cd "$TF_DIR"
OUT="$(terraform output -json 2>/dev/null || echo '{}')"

if [[ "$OUT" == "{}" ]] || [[ "$(echo "$OUT" | jq 'length')" -eq 0 ]]; then
  cat <<EOF >&2
render_k8s_from_terraform: no terraform outputs — run terraform apply first.

  cd pegasusX/infra/terraform
  terraform apply -var="project_id=v-o-i-d" -var="tenant_slug=prod" -var="enable_gke=true" ...

Then push images to Artifact Registry and re-run this script.
EOF
  exit 1
fi

GAR_URL="$(echo "$OUT" | jq -r '.artifact_registry_url.value // empty')"
RUNTIME_SA="$(echo "$OUT" | jq -r '.backend_runtime_service_account.value // empty')"
JWT_GSM="$(echo "$OUT" | jq -r '.jwt_secret_id.value // empty')"
GLOBAL_PAY_GSM="$(echo "$OUT" | jq -r '.global_pay_webhook_secret_id.value // empty')"
ADYEN_GSM="$(echo "$OUT" | jq -r '.adyen_webhook_secret_id.value // empty')"
STRIPE_GSM="$(echo "$OUT" | jq -r '.stripe_webhook_secret_id.value // empty')"
MAPS_GSM="$(echo "$OUT" | jq -r '.google_maps_api_key_secret_id.value // empty')"
SPANNER_URI="$(echo "$OUT" | jq -r '.spanner_database_uri.value // empty')"
REDIS_HOST="$(echo "$OUT" | jq -r '.redis_host.value // empty')"
REDIS_PORT="$(echo "$OUT" | jq -r '.redis_port.value // empty')"
KAFKA_GSM="$(echo "$OUT" | jq -r '.kafka_bootstrap_secret.value // empty')"

if [[ -z "$GAR_URL" || -z "$RUNTIME_SA" ]]; then
  echo "render_k8s_from_terraform: artifact_registry_url or backend_runtime_service_account missing — was enable_gke=true on apply?" >&2
  exit 1
fi

# project id is the third path segment: ...pkg.dev/PROJECT/repo
GCP_PROJECT_ID="$(echo "$GAR_URL" | awk -F/ '{print $(NF-1)}')"

export GCP_PROJECT_ID
export GCP_RUNTIME_SA_EMAIL="$RUNTIME_SA"
export BACKEND_IMAGE="${GAR_URL}/backend-go:${TAG}"
export AI_WORKER_IMAGE="${GAR_URL}/ai-worker:${TAG}"
export JWT_SECRET_GSM="$JWT_GSM"
export GLOBAL_PAY_GSM="$GLOBAL_PAY_GSM"
export ADYEN_GSM="$ADYEN_GSM"
export STRIPE_GSM="$STRIPE_GSM"
export GOOGLE_MAPS_GSM="$MAPS_GSM"

if [[ -n "$SPANNER_URI" ]]; then
	export SPANNER_PROJECT="$(echo "$SPANNER_URI" | awk -F/ '{print $2}')"
	export SPANNER_INSTANCE="$(echo "$SPANNER_URI" | awk -F/ '{print $4}')"
	export SPANNER_DATABASE="$(echo "$SPANNER_URI" | awk -F/ '{print $6}')"
fi
if [[ -n "$REDIS_HOST" && -n "$REDIS_PORT" ]]; then
	export REDIS_ADDR="${REDIS_HOST}:${REDIS_PORT}"
fi

ENV_GEN="${ROOT}/.env.k8s.generated"
cat >"$ENV_GEN" <<EOF
# Auto-generated by render_k8s_from_terraform.sh — do not commit
GCP_PROJECT_ID=${GCP_PROJECT_ID}
GCP_RUNTIME_SA_EMAIL=${GCP_RUNTIME_SA_EMAIL}
BACKEND_IMAGE=${GAR_URL}/backend-go:${TAG}
AI_WORKER_IMAGE=${GAR_URL}/ai-worker:${TAG}
JWT_SECRET_GSM=${JWT_GSM}
GLOBAL_PAY_GSM=${GLOBAL_PAY_GSM}
ADYEN_GSM=${ADYEN_GSM}
STRIPE_GSM=${STRIPE_GSM}
GOOGLE_MAPS_GSM=${MAPS_GSM}
SPANNER_PROJECT=${SPANNER_PROJECT:-}
SPANNER_INSTANCE=${SPANNER_INSTANCE:-}
SPANNER_DATABASE=${SPANNER_DATABASE:-}
REDIS_ADDR=${REDIS_ADDR:-}
KAFKA_GSM=${KAFKA_GSM}
EOF
echo "  wrote ${ENV_GEN}"

echo "render_k8s_from_terraform: project=${GCP_PROJECT_ID} tag=${TAG}"
echo "  BACKEND_IMAGE=${BACKEND_IMAGE}"
echo "  AI_WORKER_IMAGE=${AI_WORKER_IMAGE}"
echo "  GCP_RUNTIME_SA_EMAIL=${GCP_RUNTIME_SA_EMAIL}"

bash "${ROOT}/scripts/render_k8s_manifests.sh"
